// Generated by `just fetch-notifiers` (src/spec/fetch-notifiers-cli.ts). Do not edit.
// Source: GET /api/alert-notifiers?version=2 on grafana/grafana:13.2.2 (commit 1bea008f); the same options on 12.4.11.
// The creatable (v1) options of each integration: names, value kinds, required and secure flags, select values.

/** DingDing: Sends HTTP POST request to DingDing */
export interface DingdingSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  url: string;
  msgType?: "link" | "actionCard";
  /** Templated title of the message. */
  title?: string;
  /** Custom DingDing message. You can use template variables. */
  message?: string;
}

/** Discord: Sends notifications to Discord */
export interface DiscordSettings {
  /** Templated title of the message. */
  title?: string;
  /** Mention a group using @ or a user using <@ID> when notifying in a channel. */
  message?: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  url: string;
  avatar_url?: string;
  /** Use the username configured in Discord's webhook settings. Otherwise, the username will be 'Grafana'. */
  use_discord_username?: boolean;
  /** Show the message inside the embed instead of above it. Note: mentions (@ or <@ID>) in the message will not trigger Discord notifications when this is enabled, as Discord only pings for mentions in the main message content. */
  use_embed_description?: boolean;
}

/** Email: Sends notifications using Grafana server configured SMTP settings */
export interface EmailSettings {
  /** Send a single email to all recipients. */
  singleEmail?: boolean;
  /** You can enter multiple email addresses using a ";", "\n" or "," separator. */
  addresses: string;
  /** Optional message. You can use templates to customize this field. Using a custom message will replace the default message. */
  message?: string;
  /** Optional subject. You can use templates to customize this field. */
  subject?: string;
}

/** Google Chat: Sends notifications to Google Chat via webhooks based on the official JSON message format */
export interface GooglechatSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  url: string;
  /** Templated title of the message. */
  title?: string;
  message?: string;
  /** Hide open URL button. */
  hide_open_button?: boolean;
  /** Hide version info. */
  hide_version_info?: boolean;
}

/** Jira: Creates Jira issues from alerts */
export interface JiraSettings {
  /** Supported v2 or v3 APIs. */
  api_url: string;
  /** Username to use for Jira authentication. Secret: write it as $__env{NAME} or $__file{/path}. */
  user?: string;
  /** Password to use for Jira authentication. Secret: write it as $__env{NAME} or $__file{/path}. */
  password?: string;
  /** Personal Access Token that is used as a bearer authorization header. Secret: write it as $__env{NAME} or $__file{/path}. */
  api_token?: string;
  /** The project key associated with the relevant Jira project. */
  project: string;
  /** The type of the Jira issue (e.g., Bug, Task, Story). You can use templates to customize this field. */
  issue_type: string;
  /** The summary of the Jira issue. You can use templates to customize this field. Maximum length is 255 characters. */
  summary?: string;
  /** The description of the Jira issue. You can use templates to customize this field. Maximum length is 32767 characters. */
  description?: string;
  /** Labels to assign to the Jira issue. You can use templates to customize this field. */
  labels?: string[];
  /** The priority of the Jira issue (e.g., High, Medium, Low). You can use templates to customize this field. */
  priority?: string;
  /** Name of the workflow transition to resolve an issue. The target status must have the category "done". If not set, the issue will not be resolved. */
  resolve_transition?: string;
  /** Name of the workflow transition to resolve an issue. The target status must not have the category "done". If not set, the issue will not be reopened. */
  reopen_transition?: string;
  /** Reopen the issue when it is not older than this value in minutes. Otherwise, create a new issue. */
  reopen_duration?: string;
  /** If reopen transition is defined, ignore issues with that resolution. */
  wont_fix_resolution?: string;
  /** Id of the custom field where the deduplication key should be stored. Otherwise, it is added to labels in format 'ALERT($KEY).'. */
  dedup_key_field?: string;
  /** Custom field data to set on the Jira issue. */
  fields?: Record<string, string>;
}

/** Kafka REST Proxy: Sends notifications to Kafka Rest Proxy */
export interface KafkaSettings {
  /** Hint: If you are directly using v3 APIs hosted on a Confluent Kafka Server, you must append /kafka to the URL here. Example: https://localhost:8082/kafka. */
  kafkaRestProxy: string;
  kafkaTopic: string;
  username?: string;
  /** The password to use when making a call to the Kafka REST Proxy. Secret: write it as $__env{NAME} or $__file{/path}. */
  password?: string;
  /** The API version to use when contacting the Kafka REST Server. By default v2 will be used. */
  apiVersion?: "v2" | "v3";
  /** v3 APIs require a clusterID to be specified. */
  kafkaClusterId?: string;
  /** Templated description of the Kafka message. */
  description?: string;
  /** Custom details to include with the message. You can use template variables. */
  details?: string;
}

/** LINE: Send notifications to LINE notify. This integration is deprecated and will be removed in a future release. */
export interface LineSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  token: string;
  /** Templated title of the message. */
  title?: string;
  /** Templated description of the message. */
  description?: string;
}

/** TLS configuration options */
export interface MqttSettingsTlsConfig {
  /** Do not verify the broker's certificate chain and host name. */
  insecureSkipVerify?: boolean;
  /** Certificate in PEM format to use when verifying the broker's certificate chain. Secret: write it as $__env{NAME} or $__file{/path}. */
  caCertificate?: string;
  /** Client certificate in PEM format to use when connecting to the broker. Secret: write it as $__env{NAME} or $__file{/path}. */
  clientCertificate?: string;
  /** Client key in PEM format to use when connecting to the broker. Secret: write it as $__env{NAME} or $__file{/path}. */
  clientKey?: string;
}

/** MQTT: Sends notifications to an MQTT broker */
export interface MqttSettings {
  /** The URL of the MQTT broker. */
  brokerUrl: string;
  /** The topic to which the message will be sent. */
  topic: string;
  /** If set to 'json', the notification message is the default JSON payload, and the Message field sets only the message field in the payload. If set to 'text', the Message field defines the entire payload. The default is 'json'. */
  messageFormat?: "json" | "text";
  /** The client ID to use when connecting to the MQTT broker. If blank, a random client ID is used. */
  clientId?: string;
  /** In 'json' Message format, sets the message field of the default JSON payload. In 'text' Message format, defines the entire payload. */
  message?: string;
  /** The username to use when connecting to the MQTT broker. */
  username?: string;
  /** The password to use when connecting to the MQTT broker. Secret: write it as $__env{NAME} or $__file{/path}. */
  password?: string;
  /** The quality of service to use when sending the message. */
  qos?: "0" | "1" | "2" | 0 | 1 | 2;
  /** If set to true, the message will be retained by the broker. */
  retain?: boolean;
  /** TLS configuration options. */
  tlsConfig?: MqttSettingsTlsConfig;
}

/** Grafana IRM: Sends alerts to Grafana IRM */
export interface OncallSettings {
  url: string;
  httpMethod?: "POST" | "PUT";
  username?: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  password?: string;
  /** Optionally provide a scheme for the Authorization Request Header. Default is Bearer. */
  authorization_scheme?: string;
  /** Credentials for the Authorization Request header. Only one of HTTP Basic Authentication or Authorization Request Header can be set. Secret: write it as $__env{NAME} or $__file{/path}. */
  authorization_credentials?: string;
  /** Max alerts to include in a notification. Remaining alerts in the same batch will be ignored above this number. 0 means no limit. */
  maxAlerts?: string;
  /** Templated title of the message. */
  title?: string;
  /** Custom message. You can use template variables. */
  message?: string;
}

/** If the API key belongs to a team, this field is ignored. */
export interface OpsgenieSettingsRespondersItem {
  /** team, teams, user, escalation, schedule or a template. */
  type: string;
  /** Name of the responder. Must be specified if ID and Username are empty or if the type is 'teams'. */
  name?: string;
  /** ID of the responder. Must be specified if name and Username are empty. */
  id?: string;
  /** User name of the responder. Must be specified if ID and Name are empty. */
  username?: string;
}

/** OpsGenie: Sends notifications to OpsGenie */
export interface OpsgenieSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  apiKey: string;
  apiUrl: string;
  /** Alert text limited to 130 characters. */
  message?: string;
  /** A description of the incident. */
  description?: string;
  /** Automatically close alerts in OpsGenie once the alert goes back to ok. */
  autoClose?: boolean;
  /** Allow the alert priority to be set using the og_priority label. */
  overridePriority?: boolean;
  /** Send the common annotations to Opsgenie as either Extra Properties, Tags or both. */
  sendTagsAs?: "tags" | "details" | "both";
  /** If the API key belongs to a team, this field is ignored. */
  responders?: OpsgenieSettingsRespondersItem[];
}

/** PagerDuty: Sends notifications to PagerDuty */
export interface PagerdutySettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  integrationKey: string;
  /** Severity of the event. It must be critical, error, warning, info - otherwise, the default is set which is critical. You can use templates. */
  severity?: string;
  /** The class/type of the event, for example 'ping failure' or 'cpu load'. */
  class?: string;
  /** Component of the source machine that is responsible for the event, for example mysql or eth0. */
  component?: string;
  /** Logical grouping of components of a service, for example 'app-stack'. */
  group?: string;
  /** You can use templates for summary. */
  summary?: string;
  /** The unique location of the affected system, preferably a hostname or FQDN. You can use templates. */
  source?: string;
  /** The name of the monitoring client that is triggering this event. You can use templates. */
  client?: string;
  /** The URL of the monitoring client that is triggering this event. You can use templates. */
  client_url?: string;
  /** A set of arbitrary key/value pairs that provide further detail about the incident. */
  details?: Record<string, string>;
  /** The URL to send API requests to. */
  url?: string;
}

/** Alertmanager: Sends notifications to Alertmanager */
export interface PrometheusAlertmanagerSettings {
  url: string;
  basicAuthUser?: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  basicAuthPassword?: string;
}

/** Pushover: Sends HTTP POST request to the Pushover API */
export interface PushoverSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  apiToken: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  userKey: string;
  device?: string;
  priority?: "2" | "1" | "0" | "-1" | "-2" | 2 | 1 | 0 | -1 | -2;
  okPriority?: "2" | "1" | "0" | "-1" | "-2" | 2 | 1 | 0 | -1 | -2;
  /** How often (in seconds) the Pushover servers will send the same alerting or OK notification to the user. */
  retry?: string;
  /** How many seconds the alerting or OK notification will continue to be retried. */
  expire?: string;
  sound?: "default" | "pushover" | "bike" | "bugle" | "cashregister" | "classical" | "cosmic" | "falling" | "gamelan" | "incoming" | "intermission" | "magic" | "mechanical" | "pianobar" | "siren" | "spacealarm" | "tugboat" | "alien" | "climb" | "persistent" | "echo" | "updown" | "none";
  okSound?: "default" | "pushover" | "bike" | "bugle" | "cashregister" | "classical" | "cosmic" | "falling" | "gamelan" | "incoming" | "intermission" | "magic" | "mechanical" | "pianobar" | "siren" | "spacealarm" | "tugboat" | "alien" | "climb" | "persistent" | "echo" | "updown" | "none";
  title?: string;
  message?: string;
}

/** Sensu Go: Sends HTTP POST request to a Sensu Go API */
export interface SensugoSettings {
  url: string;
  /** API key to auth to Sensu Go backend. Secret: write it as $__env{NAME} or $__file{/path}. */
  apikey: string;
  entity?: string;
  check?: string;
  handler?: string;
  namespace?: string;
  message?: string;
}

/** Slack: Sends notifications to Slack */
export interface SlackSettings {
  /** Specify channel, private group, or IM channel (can be an encoded ID or a name) - required unless you provide a webhook. */
  recipient?: string;
  /** Provide a Slack API token (starts with "xoxb") - required unless you provide a webhook. Secret: write it as $__env{NAME} or $__file{/path}. */
  token?: string;
  /** Set the username for the bot's message. */
  username?: string;
  /** Provide an emoji to use as the icon for the bot's message. Overrides the icon URL. */
  icon_emoji?: string;
  /** Provide a URL to an image to use as the icon for the bot's message. */
  icon_url?: string;
  /** Mention one or more users (comma separated) when notifying in a channel, by ID (you can copy this from the user's Slack profile). */
  mentionUsers?: string;
  /** Mention one or more groups (comma separated) when notifying in a channel (you can copy this from the group's Slack profile URL). */
  mentionGroups?: string;
  /** Mention whole channel or just active members when notifying. */
  mentionChannel?: "" | "here" | "channel";
  /** Optionally provide a Slack incoming webhook URL for sending messages, in this case the token isn't necessary. Secret: write it as $__env{NAME} or $__file{/path}. */
  url?: string;
  /** Optionally provide a custom Slack message API endpoint for non-webhook requests, default is https://slack.com/api/chat.postMessage. */
  endpointUrl?: string;
  /** Templated color of the slack message. */
  color?: string;
  /** Templated title of the slack message. */
  title?: string;
  /** Body of the slack message. */
  text?: string;
  /** Templated footer of the slack message. */
  footer?: string;
}

/** Configures AWS's Signature Verification 4 signing process to sign requests */
export interface SnsSettingsSigv4 {
  /** The AWS region. If blank, the region from the default credentials chain is used. */
  region?: string;
  /** The AWS API access key. Secret: write it as $__env{NAME} or $__file{/path}. */
  access_key?: string;
  /** The AWS API secret key. Secret: write it as $__env{NAME} or $__file{/path}. */
  secret_key?: string;
  /** Named AWS profile used to authenticate. */
  profile?: string;
  /** AWS Role ARN, an alternative to using AWS API keys. */
  role_arn?: string;
}

/** AWS SNS: Sends notifications to AWS Simple Notification Service */
export interface SnsSettings {
  api_url?: string;
  /** Configures AWS's Signature Verification 4 signing process to sign requests. */
  sigv4?: SnsSettingsSigv4;
  /** If you don't specify this value, you must specify a value for the phone_number or target_arn. If you are using a FIFO SNS topic you should set a message group interval longer than 5 minutes to prevent messages with the same group key being deduplicated by the SNS default deduplication window. */
  topic_arn?: string;
  /** Phone number if message is delivered via SMS in E.164 format. If you don't specify this value, you must specify a value for the topic_arn or target_arn. */
  phone_number?: string;
  /** The mobile platform endpoint ARN if message is delivered via mobile notifications. If you don't specify this value, you must specify a value for the topic_arn or phone_number. */
  target_arn?: string;
  /** Optional subject. By default, this field uses the default title template and can be customized with templates and custom messages. It cannot be an empty string. */
  subject?: string;
  /** Optional message. By default, this field uses the default message template and can be customized with templates and custom messages. */
  message?: string;
  /** SNS message attributes. */
  attributes?: Record<string, string>;
}

/** Microsoft Teams: Sends notifications using Incoming Webhook connector to Microsoft Teams */
export interface TeamsSettings {
  url: string;
  /** Templated title of the Teams message. */
  title?: string;
  /** Section title for the Teams message. Leave blank for none. */
  sectiontitle?: string;
  message?: string;
}

/** Telegram: Sends notifications to Telegram */
export interface TelegramSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  bottoken: string;
  /** Integer Telegram Chat Identifier. */
  chatid: string;
  /** Integer Telegram Message Thread Identifier. */
  message_thread_id?: string;
  message?: string;
  /** Mode for parsing entities in the message text. Default is 'HTML'. */
  parse_mode?: "None" | "HTML" | "Markdown" | "MarkdownV2";
  /** Disables link previews for links in this message. */
  disable_web_page_preview?: boolean;
  /** Protects the contents of the sent message from forwarding and saving. */
  protect_content?: boolean;
  /** Sends the message silently. Users will receive a notification with no sound. */
  disable_notifications?: boolean;
}

/** Threema Gateway: Sends notifications to Threema using Threema Gateway (Basic IDs) */
export interface ThreemaSettings {
  /** Your 8 character Threema Gateway Basic ID (starting with a *). */
  gateway_id: string;
  /** The 8 character Threema ID that should receive the alerts. */
  recipient_id: string;
  /** Your Threema Gateway API secret. Secret: write it as $__env{NAME} or $__file{/path}. */
  api_secret: string;
  /** Templated title of the message. */
  title?: string;
  /** Templated description of the message. */
  description?: string;
}

/** VictorOps: Sends notifications to VictorOps */
export interface VictoropsSettings {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  url: string;
  messageType?: "CRITICAL" | "WARNING";
  /** Templated title to display. */
  title?: string;
  /** Templated description of the message. */
  description?: string;
}

/** Cisco Webex Teams: Sends notifications to Cisco Webex Teams */
export interface WebexSettings {
  /** API endpoint at which we'll send webhooks to. */
  api_url?: string;
  /** The room ID to send messages to. */
  room_id: string;
  /** Non-expiring access token of the bot that will post messages on our behalf. Secret: write it as $__env{NAME} or $__file{/path}. */
  bot_token: string;
  /** Notification template to use. Markdown is supported. */
  message?: string;
}

/** Optionally provide a templated payload. Overrides 'Message' and 'Title' field. */
export interface WebhookSettingsPayload {
  /** Custom payload template. */
  template: string;
  /** Optionally provide a variables to be used in the payload template. They will be available in the template as `.Vars.<variable_name>`. */
  vars?: Record<string, string>;
}

/** TLS configuration options */
export interface WebhookSettingsTlsConfig {
  /** Do not verify the server's certificate chain and host name. */
  insecureSkipVerify?: boolean;
  /** Certificate in PEM format to use when verifying the server's certificate chain. Secret: write it as $__env{NAME} or $__file{/path}. */
  caCertificate?: string;
  /** Client certificate in PEM format to use when connecting to the server. Secret: write it as $__env{NAME} or $__file{/path}. */
  clientCertificate?: string;
  /** Client key in PEM format to use when connecting to the server. Secret: write it as $__env{NAME} or $__file{/path}. */
  clientKey?: string;
}

/** HMAC signature configuration options */
export interface WebhookSettingsHmacConfig {
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  secret: string;
  /** The header in which the HMAC signature will be included. */
  header?: string;
  /** If set, the timestamp will be included in the HMAC signature. The value should be the name of the header to use. */
  timestampHeader?: string;
}

/** Optional TLS configuration options for OAuth2 requests. */
export interface WebhookSettingsHttpConfigOauth2TlsConfig {
  /** Do not verify the server's certificate chain and host name. */
  insecureSkipVerify?: boolean;
  /** Certificate in PEM format to use when verifying the server's certificate chain. Secret: write it as $__env{NAME} or $__file{/path}. */
  caCertificate?: string;
  /** Client certificate in PEM format to use when connecting to the server. Secret: write it as $__env{NAME} or $__file{/path}. */
  clientCertificate?: string;
  /** Client key in PEM format to use when connecting to the server. Secret: write it as $__env{NAME} or $__file{/path}. */
  clientKey?: string;
}

/** Optional proxy configuration. */
export interface WebhookSettingsHttpConfigOauth2ProxyConfig {
  /** HTTP proxy server to use to connect to the targets. */
  proxy_url?: string;
  /** Use environment HTTP_PROXY, HTTPS_PROXY and NO_PROXY to determine proxies. */
  proxy_from_environment?: boolean;
  /** Comma-separated list of addresses that should not use a proxy. */
  no_proxy?: string;
  /** Optional headers to send to proxies during CONNECT requests. */
  proxy_connect_header?: Record<string, string>;
}

/** OAuth2 configuration options */
export interface WebhookSettingsHttpConfigOauth2 {
  /** URL for the access token endpoint. */
  token_url: string;
  /** Client ID to use when authenticating. */
  client_id: string;
  /** Client secret to use when authenticating. Secret: write it as $__env{NAME} or $__file{/path}. */
  client_secret: string;
  /** Optional scopes to request when obtaining an access token. */
  scopes?: string[];
  /** Optional parameters to append to the access token request. */
  endpoint_params?: Record<string, string>;
  /** Optional TLS configuration options for OAuth2 requests. */
  tls_config?: WebhookSettingsHttpConfigOauth2TlsConfig;
  /** Optional proxy configuration. */
  proxy_config?: WebhookSettingsHttpConfigOauth2ProxyConfig;
}

/** Common HTTP client options. */
export interface WebhookSettingsHttpConfig {
  /** OAuth2 configuration options. */
  oauth2?: WebhookSettingsHttpConfigOauth2;
}

/** Webhook: Sends HTTP POST request to a URL */
export interface WebhookSettings {
  url: string;
  httpMethod?: "POST" | "PUT";
  username?: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  password?: string;
  /** Optionally provide a scheme for the Authorization Request Header. Default is Bearer. */
  authorization_scheme?: string;
  /** Credentials for the Authorization Request header. Only one of HTTP Basic Authentication or Authorization Request Header can be set. Secret: write it as $__env{NAME} or $__file{/path}. */
  authorization_credentials?: string;
  /** Optionally provide extra headers to be used in the request. */
  headers?: Record<string, string>;
  /** Max alerts to include in a notification. Remaining alerts in the same batch will be ignored above this number. 0 means no limit. */
  maxAlerts?: string;
  /** Templated title of the message. */
  title?: string;
  /** Templated message to be used in the payload's "message" field. */
  message?: string;
  /** Optionally provide a templated payload. Overrides 'Message' and 'Title' field. */
  payload?: WebhookSettingsPayload;
  /** TLS configuration options. */
  tlsConfig?: WebhookSettingsTlsConfig;
  /** HMAC signature configuration options. */
  hmacConfig?: WebhookSettingsHmacConfig;
  /** Common HTTP client options. */
  http_config?: WebhookSettingsHttpConfig;
}

/** Sets the `Authorization` header with the configured username and password. */
export interface WechatSettingsHttpConfigBasicAuth {
  username?: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  password?: string;
}

/** The HTTP authorization credentials for the targets. */
export interface WechatSettingsHttpConfigAuthorization {
  type?: string;
  /** Secret: write it as $__env{NAME} or $__file{/path}. */
  credentials?: string;
}

/** Configures the TLS settings. */
export interface WechatSettingsHttpConfigTlsConfig {
  /** ServerName extension to indicate the name of the server. */
  server_name?: string;
  /** Disable validation of the server certificate. */
  insecure_skip_verify?: boolean;
  min_version?: string;
  max_version?: string;
}

/** Configures the TLS settings. */
export interface WechatSettingsHttpConfigOauth2TlsConfig {
  /** ServerName extension to indicate the name of the server. */
  server_name?: string;
  /** Disable validation of the server certificate. */
  insecure_skip_verify?: boolean;
  min_version?: string;
  max_version?: string;
}

/** Configures the OAuth2 settings. */
export interface WechatSettingsHttpConfigOauth2 {
  /** The OAuth2 client ID. */
  client_id: string;
  /** The OAuth2 client secret. Secret: write it as $__env{NAME} or $__file{/path}. */
  client_secret: string;
  /** The OAuth2 token exchange URL. */
  token_url: string;
  /** Comma-separated list of scopes. */
  scopes?: string[];
  endpoint_params?: Record<string, string>;
  /** Configures the TLS settings. */
  tls_config?: WechatSettingsHttpConfigOauth2TlsConfig;
  /** HTTP proxy server to use to connect to the targets. */
  proxy_url?: string;
  /** Comma-separated list of domains for which the proxy should not be used. */
  no_proxy?: string;
  /** Makes use of net/http ProxyFromEnvironment function to determine proxies. */
  proxy_from_environment?: boolean;
  /** Headers to send to proxies during CONNECT requests. */
  proxy_connect_header?: Record<string, string>;
}

/** Note that `basic_auth` and `bearer_token` options are mutually exclusive. */
export interface WechatSettingsHttpConfig {
  /** Sets the `Authorization` header with the configured username and password. */
  basic_auth?: WechatSettingsHttpConfigBasicAuth;
  /** The HTTP authorization credentials for the targets. */
  authorization?: WechatSettingsHttpConfigAuthorization;
  /** Whether the client should follow HTTP 3xx redirects. */
  follow_redirects?: boolean;
  /** Whether the client should configure HTTP2. */
  enable_http2?: boolean;
  /** Headers to inject in the requests. */
  http_headers?: Record<string, string>;
  /** HTTP proxy server to use to connect to the targets. */
  proxy_url?: string;
  /** Comma-separated list of domains for which the proxy should not be used. */
  no_proxy?: string;
  /** Makes use of net/http ProxyFromEnvironment function to determine proxies. */
  proxy_from_environment?: boolean;
  /** Headers to send to proxies during CONNECT requests. */
  proxy_connect_header?: Record<string, string>;
  /** Configures the TLS settings. */
  tls_config?: WechatSettingsHttpConfigTlsConfig;
  /** Configures the OAuth2 settings. */
  oauth2?: WechatSettingsHttpConfigOauth2;
}

/** WeChat: Sends notifications to WeChat */
export interface WechatSettings {
  api_url?: string;
  /** The API key to use when talking to the WeChat API. Secret: write it as $__env{NAME} or $__file{/path}. */
  api_secret?: string;
  /** The corp id for authentication. */
  corp_id?: string;
  /** API request data as defined by the WeChat API. */
  message?: string;
  /** Type of the message type. */
  message_type?: "text" | "markdown";
  agent_id?: string;
  to_user?: string;
  to_party?: string;
  to_tag?: string;
  /** Note that `basic_auth` and `bearer_token` options are mutually exclusive. */
  http_config?: WechatSettingsHttpConfig;
}

/** WeCom: Send alerts generated by Grafana to WeCom */
export interface WecomSettings {
  /** Required if using GroupRobot. Secret: write it as $__env{NAME} or $__file{/path}. */
  url?: string;
  /** Required if using APIAPP, see https://work.weixin.qq.com/wework_admin/frame#apps create ApiApp. */
  agent_id?: string;
  /** Required if using APIAPP, see https://work.weixin.qq.com/wework_admin/frame#profile. */
  corp_id?: string;
  /** Required if using APIAPP. Secret: write it as $__env{NAME} or $__file{/path}. */
  secret?: string;
  msgtype?: "text" | "markdown";
  /** Custom WeCom message. You can use template variables. */
  message?: string;
  /** Templated title of the message. */
  title?: string;
  touser?: string;
}

/** The settings type of each integration, by the `type` a contact point receiver uses. */
export interface ContactPointSettingsByType {
  dingding: DingdingSettings;
  discord: DiscordSettings;
  email: EmailSettings;
  googlechat: GooglechatSettings;
  jira: JiraSettings;
  kafka: KafkaSettings;
  line: LineSettings;
  mqtt: MqttSettings;
  oncall: OncallSettings;
  opsgenie: OpsgenieSettings;
  pagerduty: PagerdutySettings;
  "prometheus-alertmanager": PrometheusAlertmanagerSettings;
  pushover: PushoverSettings;
  sensugo: SensugoSettings;
  slack: SlackSettings;
  sns: SnsSettings;
  teams: TeamsSettings;
  telegram: TelegramSettings;
  threema: ThreemaSettings;
  victorops: VictoropsSettings;
  webex: WebexSettings;
  webhook: WebhookSettings;
  wechat: WechatSettings;
  wecom: WecomSettings;
}

export type NotifierOptionKind = "string" | "number" | "boolean" | "select" | "map" | "strings" | "object" | "objects";

export interface NotifierOptionSchema {
  key: string;
  kind: NotifierOptionKind;
  /** Required whenever the integration is used (not only given another option). */
  required?: true;
  /** Grafana stores it encrypted: write it as `$__env{NAME}` or `$__file{/path}`. */
  secure?: true;
  values?: readonly string[];
  /** The keys of an `object` or `objects` option. */
  options?: readonly NotifierOptionSchema[];
}

export interface NotifierSchema {
  name: string;
  /** False when Grafana lists the integration but no longer creates it. */
  creatable: boolean;
  deprecated?: true;
  options: readonly NotifierOptionSchema[];
}

export const CONTACT_POINT_NOTIFIERS: Readonly<Record<keyof ContactPointSettingsByType, NotifierSchema>> = {
  dingding: {
    name: "DingDing",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true, secure: true },
      { key: "msgType", kind: "select", values: ["link","actionCard"] },
      { key: "title", kind: "string" },
      { key: "message", kind: "string" },
    ],
  },
  discord: {
    name: "Discord",
    creatable: true,
    options: [
      { key: "title", kind: "string" },
      { key: "message", kind: "string" },
      { key: "url", kind: "string", required: true, secure: true },
      { key: "avatar_url", kind: "string" },
      { key: "use_discord_username", kind: "boolean" },
      { key: "use_embed_description", kind: "boolean" },
    ],
  },
  email: {
    name: "Email",
    creatable: true,
    options: [
      { key: "singleEmail", kind: "boolean" },
      { key: "addresses", kind: "string", required: true },
      { key: "message", kind: "string" },
      { key: "subject", kind: "string" },
    ],
  },
  googlechat: {
    name: "Google Chat",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true, secure: true },
      { key: "title", kind: "string" },
      { key: "message", kind: "string" },
      { key: "hide_open_button", kind: "boolean" },
      { key: "hide_version_info", kind: "boolean" },
    ],
  },
  jira: {
    name: "Jira",
    creatable: true,
    options: [
      { key: "api_url", kind: "string", required: true },
      { key: "user", kind: "string", secure: true },
      { key: "password", kind: "string", secure: true },
      { key: "api_token", kind: "string", secure: true },
      { key: "project", kind: "string", required: true },
      { key: "issue_type", kind: "string", required: true },
      { key: "summary", kind: "string" },
      { key: "description", kind: "string" },
      { key: "labels", kind: "strings" },
      { key: "priority", kind: "string" },
      { key: "resolve_transition", kind: "string" },
      { key: "reopen_transition", kind: "string" },
      { key: "reopen_duration", kind: "string" },
      { key: "wont_fix_resolution", kind: "string" },
      { key: "dedup_key_field", kind: "string" },
      { key: "fields", kind: "map" },
    ],
  },
  kafka: {
    name: "Kafka REST Proxy",
    creatable: true,
    options: [
      { key: "kafkaRestProxy", kind: "string", required: true },
      { key: "kafkaTopic", kind: "string", required: true },
      { key: "username", kind: "string" },
      { key: "password", kind: "string", secure: true },
      { key: "apiVersion", kind: "select", values: ["v2","v3"] },
      { key: "kafkaClusterId", kind: "string" },
      { key: "description", kind: "string" },
      { key: "details", kind: "string" },
    ],
  },
  line: {
    name: "LINE",
    creatable: false,
    deprecated: true,
    options: [
      { key: "token", kind: "string", required: true, secure: true },
      { key: "title", kind: "string" },
      { key: "description", kind: "string" },
    ],
  },
  mqtt: {
    name: "MQTT",
    creatable: true,
    options: [
      { key: "brokerUrl", kind: "string", required: true },
      { key: "topic", kind: "string", required: true },
      { key: "messageFormat", kind: "select", values: ["json","text"] },
      { key: "clientId", kind: "string" },
      { key: "message", kind: "string" },
      { key: "username", kind: "string" },
      { key: "password", kind: "string", secure: true },
      { key: "qos", kind: "select", values: ["0","1","2"] },
      { key: "retain", kind: "boolean" },
      { key: "tlsConfig", kind: "object", options: [
        { key: "insecureSkipVerify", kind: "boolean" },
        { key: "caCertificate", kind: "string", secure: true },
        { key: "clientCertificate", kind: "string", secure: true },
        { key: "clientKey", kind: "string", secure: true },
      ] },
    ],
  },
  oncall: {
    name: "Grafana IRM",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true },
      { key: "httpMethod", kind: "select", values: ["POST","PUT"] },
      { key: "username", kind: "string" },
      { key: "password", kind: "string", secure: true },
      { key: "authorization_scheme", kind: "string" },
      { key: "authorization_credentials", kind: "string", secure: true },
      { key: "maxAlerts", kind: "string" },
      { key: "title", kind: "string" },
      { key: "message", kind: "string" },
    ],
  },
  opsgenie: {
    name: "OpsGenie",
    creatable: true,
    options: [
      { key: "apiKey", kind: "string", required: true, secure: true },
      { key: "apiUrl", kind: "string", required: true },
      { key: "message", kind: "string" },
      { key: "description", kind: "string" },
      { key: "autoClose", kind: "boolean" },
      { key: "overridePriority", kind: "boolean" },
      { key: "sendTagsAs", kind: "select", values: ["tags","details","both"] },
      { key: "responders", kind: "objects", options: [
        { key: "type", kind: "string", required: true },
        { key: "name", kind: "string" },
        { key: "id", kind: "string" },
        { key: "username", kind: "string" },
      ] },
    ],
  },
  pagerduty: {
    name: "PagerDuty",
    creatable: true,
    options: [
      { key: "integrationKey", kind: "string", required: true, secure: true },
      { key: "severity", kind: "string" },
      { key: "class", kind: "string" },
      { key: "component", kind: "string" },
      { key: "group", kind: "string" },
      { key: "summary", kind: "string" },
      { key: "source", kind: "string" },
      { key: "client", kind: "string" },
      { key: "client_url", kind: "string" },
      { key: "details", kind: "map" },
      { key: "url", kind: "string" },
    ],
  },
  "prometheus-alertmanager": {
    name: "Alertmanager",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true },
      { key: "basicAuthUser", kind: "string" },
      { key: "basicAuthPassword", kind: "string", secure: true },
    ],
  },
  pushover: {
    name: "Pushover",
    creatable: true,
    options: [
      { key: "apiToken", kind: "string", required: true, secure: true },
      { key: "userKey", kind: "string", required: true, secure: true },
      { key: "device", kind: "string" },
      { key: "priority", kind: "select", values: ["2","1","0","-1","-2"] },
      { key: "okPriority", kind: "select", values: ["2","1","0","-1","-2"] },
      { key: "retry", kind: "string" },
      { key: "expire", kind: "string" },
      { key: "sound", kind: "select", values: ["default","pushover","bike","bugle","cashregister","classical","cosmic","falling","gamelan","incoming","intermission","magic","mechanical","pianobar","siren","spacealarm","tugboat","alien","climb","persistent","echo","updown","none"] },
      { key: "okSound", kind: "select", values: ["default","pushover","bike","bugle","cashregister","classical","cosmic","falling","gamelan","incoming","intermission","magic","mechanical","pianobar","siren","spacealarm","tugboat","alien","climb","persistent","echo","updown","none"] },
      { key: "title", kind: "string" },
      { key: "message", kind: "string" },
    ],
  },
  sensugo: {
    name: "Sensu Go",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true },
      { key: "apikey", kind: "string", required: true, secure: true },
      { key: "entity", kind: "string" },
      { key: "check", kind: "string" },
      { key: "handler", kind: "string" },
      { key: "namespace", kind: "string" },
      { key: "message", kind: "string" },
    ],
  },
  slack: {
    name: "Slack",
    creatable: true,
    options: [
      { key: "recipient", kind: "string" },
      { key: "token", kind: "string", secure: true },
      { key: "username", kind: "string" },
      { key: "icon_emoji", kind: "string" },
      { key: "icon_url", kind: "string" },
      { key: "mentionUsers", kind: "string" },
      { key: "mentionGroups", kind: "string" },
      { key: "mentionChannel", kind: "select", values: ["","here","channel"] },
      { key: "url", kind: "string", secure: true },
      { key: "endpointUrl", kind: "string" },
      { key: "color", kind: "string" },
      { key: "title", kind: "string" },
      { key: "text", kind: "string" },
      { key: "footer", kind: "string" },
    ],
  },
  sns: {
    name: "AWS SNS",
    creatable: true,
    options: [
      { key: "api_url", kind: "string" },
      { key: "sigv4", kind: "object", options: [
        { key: "region", kind: "string" },
        { key: "access_key", kind: "string", secure: true },
        { key: "secret_key", kind: "string", secure: true },
        { key: "profile", kind: "string" },
        { key: "role_arn", kind: "string" },
      ] },
      { key: "topic_arn", kind: "string" },
      { key: "phone_number", kind: "string" },
      { key: "target_arn", kind: "string" },
      { key: "subject", kind: "string" },
      { key: "message", kind: "string" },
      { key: "attributes", kind: "map" },
    ],
  },
  teams: {
    name: "Microsoft Teams",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true },
      { key: "title", kind: "string" },
      { key: "sectiontitle", kind: "string" },
      { key: "message", kind: "string" },
    ],
  },
  telegram: {
    name: "Telegram",
    creatable: true,
    options: [
      { key: "bottoken", kind: "string", required: true, secure: true },
      { key: "chatid", kind: "string", required: true },
      { key: "message_thread_id", kind: "string" },
      { key: "message", kind: "string" },
      { key: "parse_mode", kind: "select", values: ["None","HTML","Markdown","MarkdownV2"] },
      { key: "disable_web_page_preview", kind: "boolean" },
      { key: "protect_content", kind: "boolean" },
      { key: "disable_notifications", kind: "boolean" },
    ],
  },
  threema: {
    name: "Threema Gateway",
    creatable: true,
    options: [
      { key: "gateway_id", kind: "string", required: true },
      { key: "recipient_id", kind: "string", required: true },
      { key: "api_secret", kind: "string", required: true, secure: true },
      { key: "title", kind: "string" },
      { key: "description", kind: "string" },
    ],
  },
  victorops: {
    name: "VictorOps",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true, secure: true },
      { key: "messageType", kind: "select", values: ["CRITICAL","WARNING"] },
      { key: "title", kind: "string" },
      { key: "description", kind: "string" },
    ],
  },
  webex: {
    name: "Cisco Webex Teams",
    creatable: true,
    options: [
      { key: "api_url", kind: "string" },
      { key: "room_id", kind: "string", required: true },
      { key: "bot_token", kind: "string", required: true, secure: true },
      { key: "message", kind: "string" },
    ],
  },
  webhook: {
    name: "Webhook",
    creatable: true,
    options: [
      { key: "url", kind: "string", required: true },
      { key: "httpMethod", kind: "select", values: ["POST","PUT"] },
      { key: "username", kind: "string" },
      { key: "password", kind: "string", secure: true },
      { key: "authorization_scheme", kind: "string" },
      { key: "authorization_credentials", kind: "string", secure: true },
      { key: "headers", kind: "map" },
      { key: "maxAlerts", kind: "string" },
      { key: "title", kind: "string" },
      { key: "message", kind: "string" },
      { key: "payload", kind: "object", options: [
        { key: "template", kind: "string", required: true },
        { key: "vars", kind: "map" },
      ] },
      { key: "tlsConfig", kind: "object", options: [
        { key: "insecureSkipVerify", kind: "boolean" },
        { key: "caCertificate", kind: "string", secure: true },
        { key: "clientCertificate", kind: "string", secure: true },
        { key: "clientKey", kind: "string", secure: true },
      ] },
      { key: "hmacConfig", kind: "object", options: [
        { key: "secret", kind: "string", required: true, secure: true },
        { key: "header", kind: "string" },
        { key: "timestampHeader", kind: "string" },
      ] },
      { key: "http_config", kind: "object", options: [
        { key: "oauth2", kind: "object", options: [
          { key: "token_url", kind: "string", required: true },
          { key: "client_id", kind: "string", required: true },
          { key: "client_secret", kind: "string", required: true, secure: true },
          { key: "scopes", kind: "strings" },
          { key: "endpoint_params", kind: "map" },
          { key: "tls_config", kind: "object", options: [
            { key: "insecureSkipVerify", kind: "boolean" },
            { key: "caCertificate", kind: "string", secure: true },
            { key: "clientCertificate", kind: "string", secure: true },
            { key: "clientKey", kind: "string", secure: true },
          ] },
          { key: "proxy_config", kind: "object", options: [
            { key: "proxy_url", kind: "string" },
            { key: "proxy_from_environment", kind: "boolean" },
            { key: "no_proxy", kind: "string" },
            { key: "proxy_connect_header", kind: "map" },
          ] },
        ] },
      ] },
    ],
  },
  wechat: {
    name: "WeChat",
    creatable: false,
    options: [
      { key: "api_url", kind: "string" },
      { key: "api_secret", kind: "string", secure: true },
      { key: "corp_id", kind: "string" },
      { key: "message", kind: "string" },
      { key: "message_type", kind: "select", values: ["text","markdown"] },
      { key: "agent_id", kind: "string" },
      { key: "to_user", kind: "string" },
      { key: "to_party", kind: "string" },
      { key: "to_tag", kind: "string" },
      { key: "http_config", kind: "object", options: [
        { key: "basic_auth", kind: "object", options: [
          { key: "username", kind: "string" },
          { key: "password", kind: "string", secure: true },
        ] },
        { key: "authorization", kind: "object", options: [
          { key: "type", kind: "string" },
          { key: "credentials", kind: "string", secure: true },
        ] },
        { key: "follow_redirects", kind: "boolean" },
        { key: "enable_http2", kind: "boolean" },
        { key: "http_headers", kind: "map" },
        { key: "proxy_url", kind: "string" },
        { key: "no_proxy", kind: "string" },
        { key: "proxy_from_environment", kind: "boolean" },
        { key: "proxy_connect_header", kind: "map" },
        { key: "tls_config", kind: "object", options: [
          { key: "server_name", kind: "string" },
          { key: "insecure_skip_verify", kind: "boolean" },
          { key: "min_version", kind: "string" },
          { key: "max_version", kind: "string" },
        ] },
        { key: "oauth2", kind: "object", options: [
          { key: "client_id", kind: "string", required: true },
          { key: "client_secret", kind: "string", required: true, secure: true },
          { key: "token_url", kind: "string", required: true },
          { key: "scopes", kind: "strings" },
          { key: "endpoint_params", kind: "map" },
          { key: "tls_config", kind: "object", options: [
            { key: "server_name", kind: "string" },
            { key: "insecure_skip_verify", kind: "boolean" },
            { key: "min_version", kind: "string" },
            { key: "max_version", kind: "string" },
          ] },
          { key: "proxy_url", kind: "string" },
          { key: "no_proxy", kind: "string" },
          { key: "proxy_from_environment", kind: "boolean" },
          { key: "proxy_connect_header", kind: "map" },
        ] },
      ] },
    ],
  },
  wecom: {
    name: "WeCom",
    creatable: true,
    options: [
      { key: "url", kind: "string", secure: true },
      { key: "agent_id", kind: "string" },
      { key: "corp_id", kind: "string" },
      { key: "secret", kind: "string", secure: true },
      { key: "msgtype", kind: "select", values: ["text","markdown"] },
      { key: "message", kind: "string" },
      { key: "title", kind: "string" },
      { key: "touser", kind: "string" },
    ],
  },
};
