/**
 * The composite catalog matches what this lexicon exports (#2662).
 *
 * `catalog.ts` is generated by `npm run generate:composite-catalogs` and is
 * what `chant serve mcp` lists.
 */

import { describe, expect, test } from "vitest";
import { isCompositeDefinition } from "@intentius/chant";
import * as composites from "./index";
import { compositeCatalog } from "./catalog";
import { otelPlugin } from "../plugin";

const exported = Object.entries(composites)
  .filter(([, value]) => isCompositeDefinition(value))
  .map(([name]) => name)
  .sort();
const catalogued = compositeCatalog.map((entry) => entry.name).sort();

describe("the otel composite catalog", () => {
  test("every exported composite has an entry, and every entry names an exported composite", () => {
    expect(exported).toEqual(["GenAiPipeline", "NodeAgent", "OtlpCollector", "RedMetrics", "TailSamplingTier"]);
    expect(catalogued, "regenerate with `npm run generate:composite-catalogs -- otel`").toEqual(exported);
  });

  test("every entry says what it is and names the components it bundles", () => {
    for (const entry of compositeCatalog) {
      expect(entry.lexicon, entry.name).toBe("otel");
      expect(entry.description.length, entry.name).toBeGreaterThan(0);
      expect(entry.bundles, entry.name).toContain("Pipeline");
      expect(entry.bundles, entry.name).toContain("OtlpReceiver");
    }
  });

  test("the plugin contributes it", () => {
    expect(otelPlugin.composites?.()).toBe(compositeCatalog);
  });
});
