// Generated by scripts/generate-composite-catalogs.ts (#2662) from this
// lexicon's composite exports. Do not edit by hand: run
// `npm run generate:composite-catalogs`. catalog.test.ts holds it to the exports.
import type { CompositeEntry } from "@intentius/chant/lexicon";

export const compositeCatalog: CompositeEntry[] = [
  {
    "name": "NodeAgent",
    "lexicon": "otel",
    "description": "The collector config of a per-node Kubernetes agent.",
    "bundles": [
      "BatchProcessor",
      "FileLogReceiver",
      "HealthCheckExtension",
      "HostMetricsReceiver",
      "K8sAttributesProcessor",
      "KubeletStatsReceiver",
      "MemoryLimiterProcessor",
      "OtlpReceiver",
      "Pipeline",
      "ResourceDetectionProcessor",
      "ResourceProcessor"
    ],
    "params": [
      {
        "name": "exporters",
        "type": "Exporter[]",
        "required": true,
        "description": "Where traces and logs go: usually the gateway (the k8s lexicon's `gatewayExporter()`), or an OTLP backend."
      },
      {
        "name": "metricExporters",
        "type": "Exporter[]",
        "required": false,
        "description": "Where metrics go, e.g. a `prometheus` exporter for a scrape on each node."
      },
      {
        "name": "clusterName",
        "type": "string",
        "required": false,
        "description": "Sets `k8s.cluster.name` on everything the agent sends."
      },
      {
        "name": "nodeNameEnv",
        "type": "string",
        "required": false,
        "description": "The environment variable holding this node's name, set from `spec.nodeName` (default `K8S_NODE_NAME`)."
      },
      {
        "name": "hostMetrics",
        "type": "boolean | { interval?: Duration; rootPath?: string }",
        "required": false,
        "description": "Node CPU, memory, load, filesystem and network from the host root at `/hostfs` (default: on, every 30s)."
      },
      {
        "name": "containerLogs",
        "type": "boolean | { selfContainer?: string }",
        "required": false,
        "description": "Container logs from `/var/log/pods` (default: on)."
      },
      {
        "name": "kubeletStats",
        "type": "boolean | { interval?: Duration }",
        "required": false,
        "description": "Pod and container resource metrics from this node's kubelet (default: off)."
      },
      {
        "name": "memoryLimitMib",
        "type": "number",
        "required": false,
        "description": "`memory_limiter`'s hard limit in MiB (default 400; the spike limit is a quarter of it)."
      },
      {
        "name": "healthCheck",
        "type": "boolean",
        "required": false,
        "description": "Serve `health_check` on 0.0.0.0:13133 (default: on)."
      }
    ]
  }
];
