import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterAll, describe, expect, test } from "vitest";
import { classifyFile, declaredFilesFor, IGNORED_DIRS, IMPLICIT_GENERATED, SEED_FILES } from "./generated-files";
import { declaredFilesAt, fileEntries, fileHash, LockError, type Lineage } from "./lineage-lock";
import { applyUpstream } from "./lineage-update";

const scratch: string[] = [];
afterAll(() => {
  for (const d of scratch) rmSync(d, { recursive: true, force: true });
});
function tree(files: Record<string, string>): string {
  const root = realpathSync(mkdtempSync(join(tmpdir(), "chant-generated-files-")));
  scratch.push(root);
  mkdirSync(join(root, ".git"));
  for (const [path, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), text);
  }
  return root;
}
const bytes = (o: Record<string, string>) => new Map(Object.entries(o).map(([k, v]) => [k, Buffer.from(v)]));

const DECLARATION = JSON.stringify({
  name: "acme",
  schema: 1,
  members: [
    {
      name: "app",
      dir: "apps/app",
      kind: "chant",
      generated: [
        { path: "ci.yml", generator: "chant build ci --lexicon github -o ci.yml" },
        { path: "skills/custom/SKILL.md", generator: "chant update", handWritten: { because: "trimmed by hand" } },
      ],
    },
  ],
});

describe("the D14 file classes (#2541)", () => {
  test("core's list: SKILL.md generated by chant update, .mcp.json a seed, .chant/types ignored", () => {
    expect(IMPLICIT_GENERATED.map((i) => [i.glob, i.command])).toEqual([["skills/*/SKILL.md", "chant update"]]);
    expect(SEED_FILES).toEqual([".mcp.json"]);
    expect(IGNORED_DIRS).toEqual([".chant/types"]);
    expect(classifyFile("skills/chant-aws/SKILL.md")).toEqual({ class: "generated", command: "chant update" });
    expect(classifyFile("skills/a/b/SKILL.md")).toEqual({ class: "owned" });
    expect(classifyFile(".mcp.json")).toEqual({ class: "seed" });
    expect(classifyFile(".chant/types/core/index.d.ts")).toEqual({ class: "ignored" });
    expect(classifyFile("src/main.ts")).toEqual({ class: "owned" });
  });

  test("a declared entry wins: generated by its generator, or owned when kept by hand", () => {
    const declared = new Map([
      ["ci.yml", { command: "chant build ci -o ci.yml", handWritten: false }],
      ["skills/custom/SKILL.md", { command: "chant update", handWritten: true }],
    ]);
    expect(classifyFile("ci.yml", declared)).toEqual({ class: "generated", command: "chant build ci -o ci.yml" });
    expect(classifyFile("skills/custom/SKILL.md", declared)).toEqual({ class: "owned" });
  });

  test("declaredFilesFor reads the declaration above a directory, relative to that directory", () => {
    const root = tree({ "chant.workspace.json": DECLARATION });
    expect([...declaredFilesFor(join(root, "apps/app"))]).toEqual([
      ["ci.yml", { command: "chant build ci --lexicon github -o ci.yml", handWritten: false }],
      ["skills/custom/SKILL.md", { command: "chant update", handWritten: true }],
    ]);
    expect([...declaredFilesFor(root)].map(([k]) => k)).toEqual(["apps/app/ci.yml", "apps/app/skills/custom/SKILL.md"]);
    expect(declaredFilesFor(join(root, "apps/other")).size).toBe(0);
    expect(declaredFilesFor(tree({})).size).toBe(0);
  });

  test("the lock's classes read the same list", () => {
    const root = tree({ "chant.workspace.json": DECLARATION });
    const files = fileEntries(
      bytes({ "ci.yml": "on: push", "skills/custom/SKILL.md": "mine", "skills/chant-aws/SKILL.md": "s", ".mcp.json": "{}", ".chant/types/x.d.ts": "", "src/a.ts": "a" }),
      declaredFilesAt(join(root, "apps/app")),
    );
    expect(files).toEqual({
      ".mcp.json": { class: "seed", sha256: fileHash("{}") },
      "ci.yml": { class: "generated", command: "chant build ci --lexicon github -o ci.yml", sha256: fileHash("on: push") },
      "skills/chant-aws/SKILL.md": { class: "generated", command: "chant update", sha256: fileHash("s") },
      "skills/custom/SKILL.md": { class: "owned", sha256: fileHash("mine") },
      "src/a.ts": { class: "owned", sha256: fileHash("a") },
    });
  });

  test("an unreadable declaration is a LockError, not an empty list", () => {
    const root = tree({ "chant.workspace.json": "{ nope" });
    expect(() => declaredFilesAt(root)).toThrow(LockError);
    expect(() => declaredFilesAt(root)).toThrow(/declaration-unparseable/);
  });

  test("an update rebuilds a file the member lists after the lock was written, instead of merging it", () => {
    const root = tree({ "chant.workspace.json": DECLARATION, "apps/app/ci.yml": "local", "apps/app/src/a.ts": "a" });
    const lineage: Lineage = {
      kind: "vendor",
      name: "app",
      template: "local:x",
      source: { type: "local", path: "x" },
      address: null,
      parameters: {},
      migrations: [],
      files: { "ci.yml": { class: "owned", sha256: fileHash("base") }, "src/a.ts": { class: "owned", sha256: fileHash("a") } },
      manualSteps: [],
    };
    const result = applyUpstream(join(root, "apps/app"), lineage, bytes({ "ci.yml": "upstream", "src/a.ts": "a2" }));
    expect(result.skipped).toEqual([{ path: "ci.yml", class: "generated", command: "chant build ci --lexicon github -o ci.yml" }]);
    expect(result.manualSteps).toEqual([]);
    expect(lineage.files["ci.yml"]).toEqual({ class: "generated", command: "chant build ci --lexicon github -o ci.yml", sha256: fileHash("base") });
    expect(readFileSync(join(root, "apps/app/ci.yml"), "utf-8")).toBe("local");
    expect(readFileSync(join(root, "apps/app/src/a.ts"), "utf-8")).toBe("a2");
  });
});
