import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import {
  LOCK_FILE,
  LockError,
  contentDigest,
  emptyLock,
  fileEntries,
  fileHash,
  readLock,
  renderLock,
  resolveManualStep,
  scopeKey,
  scopeStatus,
  writeLock,
  type Lineage,
} from "./lineage-lock";
import { applyUpstream } from "./lineage-update";
import { contentHash } from "../cli/commands/vendor";

let root: string;

function put(rel: string, content: string): void {
  const abs = join(root, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}
const read = (rel: string) => readFileSync(join(root, rel), "utf-8");
const files = (o: Record<string, string>) => new Map(Object.entries(o).map(([k, v]) => [k, Buffer.from(v)]));

function vendorLineage(overrides: Partial<Lineage> = {}): Lineage {
  return {
    kind: "vendor",
    name: "web",
    template: "local:shared/web",
    source: { type: "local", path: "shared/web" },
    ref: "v1",
    address: null,
    parameters: {},
    migrations: [],
    files: {},
    manualSteps: [],
    ...overrides,
  };
}

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "chant-lineage-"));
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("the lock file", () => {
  test("round-trips, with scopes, files and steps in sorted order", () => {
    const lock = emptyLock();
    lock.scopes["vendor/web"] = vendorLineage({
      address: { digest: contentDigest(files({ b: "2", a: "1" })) },
      files: fileEntries(files({ "z.ts": "z", "a.ts": "a" })),
    });
    lock.scopes["."] = { ...vendorLineage(), kind: "template", name: undefined, template: "lexicon:aws/default" };
    delete lock.scopes["."].name;
    writeLock(root, lock);
    const text = readFileSync(join(root, LOCK_FILE), "utf-8");
    expect(Object.keys(JSON.parse(text).scopes)).toEqual([".", "vendor/web"]);
    expect(Object.keys(JSON.parse(text).scopes["vendor/web"].files)).toEqual(["a.ts", "z.ts"]);
    expect(readLock(root)).toEqual(JSON.parse(text));
    expect(renderLock(readLock(root)!)).toBe(text);
  });

  test("no lock reads as null", () => {
    expect(readLock(root)).toBeNull();
  });

  test("a newer lockVersion is refused by name", () => {
    put(LOCK_FILE, JSON.stringify({ lockVersion: 2, scopes: {} }));
    expect(() => readLock(root)).toThrow(/lockVersion 2; this chant reads up to 1/);
  });

  test("an invalid lock names the field", () => {
    put(LOCK_FILE, JSON.stringify({ lockVersion: 1, scopes: { ".": { kind: "template" } } }));
    expect(() => readLock(root)).toThrow(LockError);
    expect(() => readLock(root)).toThrow(/scopes\.\.\.template/);
  });

  test("a scope key must be normal", () => {
    const lock = emptyLock();
    lock.scopes["./vendor/web/"] = vendorLineage();
    put(LOCK_FILE, JSON.stringify(lock));
    expect(() => readLock(root)).toThrow(/not in normal form/);
  });

  test("the digest is the vendor.json checksum", () => {
    const set = files({ "b.ts": "b", "a/x.ts": "x" });
    expect(contentDigest(set)).toBe(contentHash(set));
  });
});

describe("scopeKey", () => {
  test("normalises to posix relative form", () => {
    expect(scopeKey("")).toBe(".");
    expect(scopeKey("./")).toBe(".");
    expect(scopeKey("vendor/web/")).toBe("vendor/web");
    expect(scopeKey("./vendor//web")).toBe("vendor/web");
  });
  test("refuses paths outside the project", () => {
    expect(() => scopeKey("../x")).toThrow(LockError);
    expect(() => scopeKey("/abs")).toThrow(LockError);
  });
});

describe("file classes", () => {
  test("skills are generated by chant update, .mcp.json is a seed, the rest owned", () => {
    const entries = fileEntries(files({ "skills/a/SKILL.md": "s", ".mcp.json": "{}", "src/x.ts": "x" }));
    expect(entries["skills/a/SKILL.md"]).toMatchObject({ class: "generated", command: "chant update" });
    expect(entries[".mcp.json"].class).toBe("seed");
    expect(entries["src/x.ts"].class).toBe("owned");
  });

  test("status ignores generated files and reports edits and deletions", () => {
    put("skills/a/SKILL.md", "edited");
    put("src/x.ts", "x");
    put("src/y.ts", "edited");
    const lineage = vendorLineage({ files: fileEntries(files({ "skills/a/SKILL.md": "s", "src/x.ts": "x", "src/y.ts": "y", "src/z.ts": "z" })) });
    const st = scopeStatus(root, ".", lineage);
    expect(st.customised).toEqual(["src/y.ts"]);
    expect(st.missing).toEqual(["src/z.ts"]);
  });
});

describe("applyUpstream — local edits are never overwritten", () => {
  const base = { "same.ts": "1", "edited.ts": "1", "both.ts": "1", "gone.ts": "1", "gone-edited.ts": "1", "deleted.ts": "1", "deleted-changed.ts": "1" };

  function setup(): Lineage {
    for (const [k, v] of Object.entries(base)) put(`t/${k}`, v);
    const lineage = vendorLineage({ files: fileEntries(files(base)) });
    put("t/edited.ts", "mine");
    put("t/both.ts", "mine");
    put("t/gone-edited.ts", "mine");
    rmSync(join(root, "t/deleted.ts"));
    rmSync(join(root, "t/deleted-changed.ts"));
    put("t/untracked.ts", "mine");
    put("t/collides.ts", "mine");
    return lineage;
  }

  const upstream = files({
    "same.ts": "2",
    "edited.ts": "1",
    "both.ts": "2",
    "deleted.ts": "1",
    "deleted-changed.ts": "2",
    "collides.ts": "theirs",
    "new.ts": "new",
  });

  test("each case in the table", () => {
    const lineage = setup();
    const result = applyUpstream(join(root, "t"), lineage, upstream);

    expect(read("t/same.ts")).toBe("2");
    expect(read("t/edited.ts")).toBe("mine");
    expect(read("t/both.ts")).toBe("mine");
    expect(existsSync(join(root, "t/gone.ts"))).toBe(false);
    expect(read("t/gone-edited.ts")).toBe("mine");
    expect(existsSync(join(root, "t/deleted.ts"))).toBe(false);
    expect(existsSync(join(root, "t/deleted-changed.ts"))).toBe(false);
    expect(read("t/untracked.ts")).toBe("mine");
    expect(read("t/collides.ts")).toBe("mine");
    expect(read("t/new.ts")).toBe("new");

    expect(result.written.sort()).toEqual(["new.ts", "same.ts"]);
    expect(result.removed).toEqual(["gone.ts"]);
    expect(lineage.manualSteps.map((s) => [s.path, s.reason])).toEqual([
      ["both.ts", "changed-locally"],
      ["collides.ts", "exists-locally"],
      ["deleted-changed.ts", "deleted-locally"],
      ["gone-edited.ts", "removed-upstream"],
    ]);
    // Merge bases: advanced where the file was taken, kept where it was not.
    expect(lineage.files["same.ts"].sha256).toBe(fileHash("2"));
    expect(lineage.files["edited.ts"].sha256).toBe(fileHash("1"));
    expect(lineage.files["both.ts"].sha256).toBe(fileHash("1"));
    expect(lineage.files["gone.ts"]).toBeUndefined();
    expect(lineage.files["untracked.ts"]).toBeUndefined();
    expect(lineage.address?.digest).toBe(contentDigest(upstream));
  });

  test("a second pull of the same source changes nothing and keeps the steps", () => {
    const lineage = setup();
    applyUpstream(join(root, "t"), lineage, upstream);
    const before = JSON.stringify(lineage);
    const again = applyUpstream(join(root, "t"), lineage, upstream);
    expect(again.written).toEqual([]);
    expect(JSON.stringify(lineage)).toBe(before);
  });

  test("resolving a step moves the base to upstream, and the next pull keeps the file", () => {
    const lineage = setup();
    applyUpstream(join(root, "t"), lineage, upstream);
    const lock = emptyLock();
    lock.scopes["t"] = lineage;
    expect(resolveManualStep(lock, "t/both.ts")?.step.reason).toBe("changed-locally");
    expect(lineage.files["both.ts"].sha256).toBe(fileHash("2"));
    expect(resolveManualStep(lock, "t/gone-edited.ts")?.step.upstream).toBeNull();
    expect(lineage.files["gone-edited.ts"]).toBeUndefined();
    expect(resolveManualStep(lock, "t/collides.ts")).not.toBeNull();
    expect(lineage.files["collides.ts"].sha256).toBe(fileHash("theirs"));
    expect(resolveManualStep(lock, "t/nope.ts")).toBeNull();

    const again = applyUpstream(join(root, "t"), lineage, upstream);
    expect(again.manualSteps.map((s) => s.path)).toEqual(["deleted-changed.ts"]);
    expect(read("t/both.ts")).toBe("mine");
  });

  test("the deepest scope owns a path", () => {
    const lock = emptyLock();
    lock.scopes["."] = vendorLineage({ manualSteps: [{ path: "vendor/web/a.ts", reason: "changed-locally", upstream: fileHash("x") }] });
    lock.scopes["vendor/web"] = vendorLineage({ manualSteps: [{ path: "a.ts", reason: "changed-locally", upstream: fileHash("y") }] });
    expect(resolveManualStep(lock, "vendor/web/a.ts")?.scope).toBe("vendor/web");
  });
});
