/**
 * Per-member pipelines (#2542): which member a project belongs to, where its
 * pipeline goes, the command that regenerates it, and the interim record of
 * generated files (`.chant/generated.json`, until #2541).
 */

import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { existsSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { twoMemberWorkspace } from "./__fixtures__/two-member-workspace";
import { findWorkspaceRoot } from "../project-root";
import {
  GENERATED_RECORD_FILE,
  memberPipelineFile,
  planMemberComponentPipeline,
  planMemberOpPipelines,
  readGeneratedRecord,
  recordGeneratedFiles,
  resolveMemberContext,
  writeMemberComponentPipeline,
} from "./member-pipeline";

let repo: string;
beforeEach(() => {
  repo = twoMemberWorkspace();
});
afterEach(() => {
  rmSync(repo, { recursive: true, force: true });
});

function context(dir: string) {
  const found = findWorkspaceRoot(dir);
  expect(found).toBeDefined();
  return resolveMemberContext(dir, found!);
}

describe("which member a project belongs to", () => {
  test("the member's directory and anything under it", () => {
    expect(context(join(repo, "services/api"))?.pipeline).toEqual({ name: "api", dir: "services/api" });
    expect(context(join(repo, "services/api/src"))?.member.name).toBe("api");
    expect(context(join(repo, "apps/web"))?.pipeline).toEqual({ name: "web", dir: "apps/web" });
  });

  test("an example group's match and a directory no member holds are no member", () => {
    expect(context(join(repo, "examples/demo"))).toBeUndefined();
    expect(context(repo)).toBeUndefined();
  });

  test("a root member excludes the other members and the group matches", () => {
    rmSync(repo, { recursive: true, force: true });
    repo = twoMemberWorkspace({ root: true });
    expect(context(repo)?.pipeline).toEqual({ name: "platform", dir: ".", exclude: ["apps/web", "examples/demo", "services/api"] });
    expect(context(join(repo, "services/api"))?.member.name).toBe("api");
  });

  test("a workspace below the repository root gives repository-relative directories", () => {
    rmSync(repo, { recursive: true, force: true });
    repo = twoMemberWorkspace({ prefix: "estate" });
    const ctx = context(join(repo, "estate/services/api"));
    expect(ctx?.pipeline).toEqual({ name: "api", dir: "estate/services/api" });
    expect(ctx?.repoRoot).toBe(repo);
  });
});

describe("the component pipeline's file and command", () => {
  test("default files are named after the member and the environment, at the forge's path", () => {
    expect(memberPipelineFile("github", "api", "staging")).toBe(".github/workflows/chant-api-staging.yml");
    expect(memberPipelineFile("forgejo", "api", "staging")).toBe(".forgejo/workflows/chant-api-staging.yml");
    expect(memberPipelineFile("gitlab", "api", "staging")).toBe(".gitlab/ci/chant-api-staging.gitlab-ci.yml");
    expect(memberPipelineFile("jenkins", "api", "staging")).toBeUndefined();
  });

  test("the plan names the file, and the command runs in the member's directory", () => {
    const dir = join(repo, "services/api");
    const plan = planMemberComponentPipeline({ projectDir: dir, found: findWorkspaceRoot(dir)!, lexicon: "github", env: "staging", promoteTo: "prod" })!;
    expect(plan.file).toBe(".github/workflows/chant-api-staging.yml");
    expect(plan.target).toBe(join(repo, ".github/workflows/chant-api-staging.yml"));
    expect(plan.member).toEqual({ name: "api", dir: "services/api", file: ".github/workflows/chant-api-staging.yml" });
    expect(plan.command).toBe("chant build --components --generate github --env staging --promote-to prod");
  });

  test("--output keeps the path, relative to the member in the command", () => {
    const dir = join(repo, "services/api");
    const plan = planMemberComponentPipeline({
      projectDir: dir,
      found: findWorkspaceRoot(dir)!,
      lexicon: "gitlab",
      output: join(repo, "ci/api.yml"),
    })!;
    expect(plan.file).toBe("ci/api.yml");
    expect(plan.command).toBe("chant build --components --generate gitlab --env production --output ../../ci/api.yml");
  });

  test("a forge with no default path needs --output", () => {
    const dir = join(repo, "services/api");
    expect(() => planMemberComponentPipeline({ projectDir: dir, found: findWorkspaceRoot(dir)!, lexicon: "jenkins" })).toThrow(/pass --output/);
  });

  test("writing puts the header on the file and records it under the member", () => {
    const dir = join(repo, "services/api");
    const plan = planMemberComponentPipeline({ projectDir: dir, found: findWorkspaceRoot(dir)!, lexicon: "github", env: "staging" })!;
    writeMemberComponentPipeline(plan, "name: x\n");
    const written = readFileSync(plan.target, "utf-8");
    expect(written.split("\n")[0]).toBe(
      "# Generated by chant — do not edit directly. Regenerate with: chant build --components --generate github --env staging (in the member's directory)",
    );
    expect(written.endsWith("name: x\n")).toBe(true);
    expect(readGeneratedRecord(dir)).toEqual({
      schema: 1,
      files: [{ path: ".github/workflows/chant-api-staging.yml", command: "chant build --components --generate github --env staging", env: "staging" }],
    });
    expect(existsSync(join(dir, GENERATED_RECORD_FILE))).toBe(true);
  });
});

describe("the Op pipelines' directory and command", () => {
  test("files go to the forge's directory at the repository root", () => {
    const dir = join(repo, "apps/web");
    const plan = planMemberOpPipelines({ projectDir: dir, found: findWorkspaceRoot(dir)!, provider: "gitlab", specFile: join(dir, "ops.json") })!;
    expect(plan.outDir).toBe(join(repo, ".gitlab/ci"));
    expect(plan.member).toEqual({ name: "web", dir: "apps/web", fileDir: ".gitlab/ci" });
    expect(plan.command).toBe("chant run --generate gitlab --spec ops.json");
  });
});

describe("the generated-file record", () => {
  test("entries are keyed by path and sorted, so regenerating leaves the file unchanged", () => {
    const dir = join(repo, "apps/web");
    recordGeneratedFiles(dir, [{ path: "b.yml", command: "x" }, { path: "a.yml", command: "y" }]);
    const first = readFileSync(join(dir, GENERATED_RECORD_FILE), "utf-8");
    recordGeneratedFiles(dir, [{ path: "a.yml", command: "y" }]);
    expect(readFileSync(join(dir, GENERATED_RECORD_FILE), "utf-8")).toBe(first);
    expect(readGeneratedRecord(dir).files.map((f) => f.path)).toEqual(["a.yml", "b.yml"]);
  });
});
