# Generated by tools/largeset-gen (issue #1750). Do not edit; regenerate.
#
# The estate declaration for root e01 (role: producer). One estate per root: two
# roots sharing a tofu-estate value would each see the other's resources as
# undeclared and propose destroying them.
estate = "ls-e01"
