# Generated by tools/largeset-gen (issue #1750). Do not edit; regenerate.
#
# Root e01, role producer.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 6.59.0"
    }
  }
}

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true
}

module "shared" {
  source = "oci://localhost:4890/largeset/shared?tag=1.0.0"

  name   = "e01"
  prefix = "ls"
}

# The head of this block's cross-estate chain: the next estate reads this VPC
# through its markers.
resource "aws_vpc" "network" {
  cidr_block = "10.100.0.0/16"
}
