// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { tf001 } from "./tf001";
import { tf024 } from "./tf024";
import { tf025 } from "./tf025";

export const postSynthChecks: PostSynthCheck[] = [
  tf001,
  tf024,
  tf025,
];
