// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { tf001 } from "./tf001";
import { tf002 } from "./tf002";
import { tf003 } from "./tf003";
import { tf004 } from "./tf004";
import { tf005 } from "./tf005";
import { tf024 } from "./tf024";
import { tf025 } from "./tf025";

export const postSynthChecks: PostSynthCheck[] = [
  tf001,
  tf002,
  tf003,
  tf004,
  tf005,
  tf024,
  tf025,
];
