/**
 * The composite catalog matches what this lexicon exports (#2662).
 *
 * `catalog.ts` is generated by `npm run generate:composite-catalogs` and is
 * what `chant serve mcp` lists. A composite added without regenerating it would
 * be invisible to an agent asking what docker offers; one renamed or removed
 * would be offered and fail to import.
 */

import { describe, expect, test } from "vitest";
import { isCompositeDefinition } from "@intentius/chant";
import * as composites from "./index";
import { compositeCatalog } from "./catalog";
import { dockerPlugin } from "../plugin";

const exported = Object.entries(composites)
  .filter(([, value]) => isCompositeDefinition(value))
  .map(([name]) => name)
  .sort();
const catalogued = compositeCatalog.map((entry) => entry.name).sort();

describe("the docker composite catalog", () => {
  test("every exported composite has an entry, and every entry names an exported composite", () => {
    expect(exported.length).toBeGreaterThan(0);
    expect(catalogued, "regenerate with `npm run generate:composite-catalogs -- docker`").toEqual(exported);
  });

  test("every entry says what it is and what it bundles", () => {
    for (const entry of compositeCatalog) {
      expect(entry.lexicon, entry.name).toBe("docker");
      expect(entry.description.length, entry.name).toBeGreaterThan(0);
      expect(entry.bundles.length, entry.name).toBeGreaterThan(0);
    }
  });

  test("the plugin contributes it", () => {
    expect(dockerPlugin.composites?.()).toBe(compositeCatalog);
  });
});
