/**
 * TypeScript declaration file generator for Slurm REST resources.
 *
 * Produces index.d.ts with typed class declarations for Job, Reservation, QoS.
 */

import type { SlurmParseResult } from "../spec/parse";
import type { NamingStrategy } from "./naming";
import {
  writeResourceClass,
  type DtsProperty,
  type DtsAttribute,
} from "@intentius/chant/codegen/generate-typescript";

/**
 * Generate the complete .d.ts file content for Slurm REST resources.
 */
export function generateTypeScriptDeclarations(
  results: SlurmParseResult[],
  naming: NamingStrategy,
): string {
  const lines: string[] = [];
  lines.push("// Code generated by chant slurm generate. DO NOT EDIT generated sections.");
  lines.push("");
  lines.push('import type { ResourceAttributes } from "@intentius/chant/runtime";');

  for (const r of results) {
    const tsName = naming.resolve(r.resource.typeName);
    if (!tsName) continue;

    const dtsProps: DtsProperty[] = r.resource.properties.map((p) => ({
      name: p.name,
      type: p.tsType,
      required: p.required,
      description: p.description,
    }));

    const dtsAttrs: DtsAttribute[] = [];

    writeResourceClass(lines, tsName, dtsProps, dtsAttrs, undefined, "ResourceAttributes");
  }

  return lines.join("\n") + "\n";
}
