#!/usr/bin/env tsx
/**
 * `just fetch-units`: download Grafana's unit registry
 * (`packages/grafana-data/src/valueFormats/categories.ts`) at the tag in
 * `GRAFANA_UNITS_SOURCE`, pull out every unit id, and rewrite
 * `src/spec/units.gen.ts`. Run it when moving to a newer Grafana, then review
 * the diff: an id Grafana dropped is one GRAF115 starts warning about.
 */
import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { sha256 } from "./schemas";
import { GRAFANA_UNITS_SOURCE, LEGACY_UNIT_ALIASES } from "./units";

const { repo, ref, commit, path } = GRAFANA_UNITS_SOURCE;
const url = `https://raw.githubusercontent.com/${repo}/${commit}/${path}`;
const res = await fetch(url);
if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
const text = await res.text();

// Each format is `{ name: t(...), id: '<id>', fn: ... }`; ids are plain string literals.
const ids: string[] = [];
for (const m of text.matchAll(/\bid:\s*'([^']+)'/g)) if (!ids.includes(m[1])) ids.push(m[1]);
for (const alias of LEGACY_UNIT_ALIASES) if (!ids.includes(alias)) ids.push(alias);
if (ids.length < 200) throw new Error(`only ${ids.length} unit ids found in ${url}; has the file's shape changed?`);

const out = `// Generated by \`just fetch-units\` (src/spec/fetch-units-cli.ts). Do not edit.
// Source: https://github.com/${repo}/blob/${ref}/${path}
// Commit ${commit}, sha256 ${sha256(text)}.
// The ids Grafana's getValueFormat() indexes, plus the legacy aliases it resolves (valueFormats.ts).

export const GRAFANA_UNIT_IDS: readonly string[] = [
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
];
`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "units.gen.ts"), out);
console.error(`${ids.length} unit ids from ${repo}@${ref} written to src/spec/units.gen.ts`);
