// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { whm005 } from "./whm005-no-empty-wrapper";
import { whm101 } from "./whm101";
import { whm102 } from "./whm102";
import { whm103 } from "./whm103";
import { whm104 } from "./whm104";
import { whm105 } from "./whm105";
import { whm201 } from "./whm201";
import { whm202 } from "./whm202";
import { whm203 } from "./whm203";
import { whm204 } from "./whm204";
import { whm301 } from "./whm301";
import { whm302 } from "./whm302";
import { whm401 } from "./whm401";
import { whm402 } from "./whm402";
import { whm403 } from "./whm403";
import { whm404 } from "./whm404";
import { whm405 } from "./whm405";
import { whm406 } from "./whm406";
import { whm407 } from "./whm407";
import { whm501 } from "./whm501";
import { whm502 } from "./whm502";

export const postSynthChecks: PostSynthCheck[] = [
  whm005,
  whm101,
  whm102,
  whm103,
  whm104,
  whm105,
  whm201,
  whm202,
  whm203,
  whm204,
  whm301,
  whm302,
  whm401,
  whm402,
  whm403,
  whm404,
  whm405,
  whm406,
  whm407,
  whm501,
  whm502,
];
