// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { cor020 } from "./cor020";
import { ext001 } from "./ext001";
import { waw010 } from "./waw010";
import { waw011 } from "./waw011";
import { waw013 } from "./waw013";
import { waw014 } from "./waw014";
import { waw015 } from "./waw015";
import { waw016 } from "./waw016";
import { waw017 } from "./waw017";
import { waw018 } from "./waw018";
import { waw019 } from "./waw019";
import { waw020 } from "./waw020";
import { waw021 } from "./waw021";
import { waw022 } from "./waw022";
import { waw023 } from "./waw023";
import { waw024 } from "./waw024";
import { waw025 } from "./waw025";
import { waw026 } from "./waw026";
import { waw027 } from "./waw027";
import { waw028 } from "./waw028";
import { waw029 } from "./waw029";
import { waw030 } from "./waw030";
import { waw031 } from "./waw031";
import { waw032 } from "./waw032";
import { waw033 } from "./waw033";
import { waw034 } from "./waw034";
import { waw035 } from "./waw035";
import { waw036 } from "./waw036";
import { waw037 } from "./waw037";
import { waw038 } from "./waw038";
import { waw039 } from "./waw039";
import { waw040 } from "./waw040";
import { waw041 } from "./waw041";
import { waw042 } from "./waw042";
import { waw043 } from "./waw043";
import { waw044 } from "./waw044";
import { waw045 } from "./waw045";
import { waw046 } from "./waw046";
import { waw047 } from "./waw047";
import { waw048 } from "./waw048";
import { waw049 } from "./waw049";
import { waw050 } from "./waw050";
import { waw051 } from "./waw051";
import { waw052 } from "./waw052";
import { waw053 } from "./waw053";
import { waw054 } from "./waw054";
import { waw055 } from "./waw055";
import { waw056 } from "./waw056";
import { waw057 } from "./waw057";
import { waw058 } from "./waw058";
import { waw059 } from "./waw059";

export const postSynthChecks: PostSynthCheck[] = [
  cor020,
  ext001,
  waw010,
  waw011,
  waw013,
  waw014,
  waw015,
  waw016,
  waw017,
  waw018,
  waw019,
  waw020,
  waw021,
  waw022,
  waw023,
  waw024,
  waw025,
  waw026,
  waw027,
  waw028,
  waw029,
  waw030,
  waw031,
  waw032,
  waw033,
  waw034,
  waw035,
  waw036,
  waw037,
  waw038,
  waw039,
  waw040,
  waw041,
  waw042,
  waw043,
  waw044,
  waw045,
  waw046,
  waw047,
  waw048,
  waw049,
  waw050,
  waw051,
  waw052,
  waw053,
  waw054,
  waw055,
  waw056,
  waw057,
  waw058,
  waw059,
];
