/**
 * `chant run --generate` inside a workspace member (#2542). Discovery is
 * stubbed; the lexicon plugins are the real ones.
 */

import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { existsSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import type { ParsedArgs } from "../registry";
import type { OpConfig } from "../../op/types";
import { twoMemberWorkspace } from "../../workspace/__fixtures__/two-member-workspace";

const discovered = new Map<string, { config: Partial<OpConfig>; filePath: string; exportName: string }>();
vi.mock("../../op/discover", () => ({
  discoverOps: async () => ({ ops: discovered, errors: [] }),
}));

const { runOp } = await import("./run");
const { generateOpsPipeline } = await import("../../op/generate-pipeline");
const { parseArgs } = await import("../main");

function ctx(argv: string[]) {
  return { args: parseArgs(argv) as ParsedArgs, plugins: [], serializers: [] };
}

let repo: string;
let cwd: string;
let logs: string[];
beforeEach(() => {
  repo = twoMemberWorkspace();
  cwd = process.cwd();
  discovered.clear();
  discovered.set("nightly-audit", {
    config: { name: "nightly-audit", phases: [], schedule: { cron: "0 6 * * *" } } as Partial<OpConfig>,
    filePath: "nightly-audit.op.ts",
    exportName: "default",
  });
  logs = [];
  vi.spyOn(console, "error").mockImplementation(() => {});
  vi.spyOn(console, "log").mockImplementation((s: string) => {
    logs.push(s);
  });
});
afterEach(() => {
  process.chdir(cwd);
  vi.restoreAllMocks();
  rmSync(repo, { recursive: true, force: true });
});

describe("chant run --generate in a workspace member", () => {
  test("github: the file is named after the member, at the repository root, and recorded", async () => {
    process.chdir(join(repo, "services/api"));
    expect(await runOp(ctx(["run", "--generate", "github"]))).toBe(0);

    expect(readdirSync(join(repo, ".github/workflows"))).toEqual(["api-nightly-audit.yml"]);
    expect(existsSync(join(repo, "services/api/.github"))).toBe(false);
    const member = { name: "api", dir: "services/api", fileDir: ".github/workflows" };
    const direct = await generateOpsPipeline([{ name: "nightly-audit" }], "github", { member });
    const text = readFileSync(join(repo, ".github/workflows/api-nightly-audit.yml"), "utf-8");
    expect(text).toBe(
      "# Generated by chant — do not edit directly. Regenerate with: chant run --generate github (in the member's directory)\n" + direct.files![0].yaml,
    );
    const record = JSON.parse(readFileSync(join(repo, "services/api/.chant/generated.json"), "utf-8"));
    expect(record.files).toEqual([{ path: ".github/workflows/api-nightly-audit.yml", command: "chant run --generate github" }]);
  });

  test("gitlab: the member's file goes in .gitlab/ci", async () => {
    process.chdir(join(repo, "apps/web"));
    expect(await runOp(ctx(["run", "--generate", "gitlab"]))).toBe(0);
    const text = readFileSync(join(repo, ".gitlab/ci/web-ops.gitlab-ci.yml"), "utf-8");
    expect(text).toContain("web-nightly-audit:");
    expect(text).toContain("cd apps/web");
  });

  test("--format json names the member and writes nothing", async () => {
    process.chdir(join(repo, "services/api"));
    expect(await runOp(ctx(["run", "--generate", "forgejo", "--format", "json"]))).toBe(0);
    const out = JSON.parse(logs.join("\n"));
    expect(out.member).toBe("api");
    expect(out.files.map((f: { path: string }) => f.path)).toEqual([".forgejo/workflows/api-nightly-audit.yml"]);
    expect(existsSync(join(repo, ".forgejo"))).toBe(false);
  });
});
