import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { OpConfig } from "../../op/types";
import type { WorkflowExecutionDescription, WorkflowHistoryRaw, HistoryEvent } from "./run-client";
import { extractStepRecords } from "./op-progress";

interface ActivityRecord {
  name: string;
  durationMs?: number;
  status: "completed" | "failed" | "skipped";
  error?: string;
}

interface PhaseRecord {
  name: string;
  activities: ActivityRecord[];
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
  const mins = Math.floor(ms / 60_000);
  const secs = Math.round((ms % 60_000) / 1000);
  return secs > 0 ? `${mins}m ${secs}s` : `${mins}m`;
}

/**
 * Group `extractStepRecords`' flat, declared-order step list back into
 * per-phase rows for the markdown table. `final` (a closed workflow has
 * every settled step it's ever going to have) decides whether an unmatched
 * declared step is reported "skipped" or simply omitted for now — see
 * `extractStepRecords`'s own doc.
 */
function extractPhaseRecords(config: OpConfig, history: WorkflowHistoryRaw, final: boolean): PhaseRecord[] {
  const byPhase = new Map<string, ActivityRecord[]>();
  for (const phase of config.phases) byPhase.set(phase.name, []);

  for (const step of extractStepRecords(config, history, { final })) {
    const status = step.status === "ok" ? "completed" : step.status === "fail" ? "failed" : "skipped";
    const list = byPhase.get(step.phase) ?? (byPhase.set(step.phase, []), byPhase.get(step.phase)!);
    list.push({ name: step.fn, durationMs: step.durationMs, status, ...(step.error ? { error: step.error } : {}) });
  }

  return config.phases.map((phase) => ({ name: phase.name, activities: byPhase.get(phase.name) ?? [] }));
}

export function generateReport(
  opName: string,
  config: OpConfig,
  description: WorkflowExecutionDescription,
  history: WorkflowHistoryRaw,
): string {
  const lines: string[] = [];

  const status = description.status.name;
  const startTime = description.startTime;
  const closeTime = description.closeTime;
  const durationMs = closeTime ? closeTime.getTime() - startTime.getTime() : undefined;

  lines.push(`# Deployment Report: ${opName}`);
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Op | ${opName} |`);
  lines.push(`| Overview | ${config.overview} |`);
  lines.push(`| Status | **${status}** |`);
  lines.push(`| Workflow ID | ${description.workflowId} |`);
  lines.push(`| Run ID | ${description.runId} |`);
  lines.push(`| Start | ${startTime.toISOString()} |`);
  if (closeTime) lines.push(`| End | ${closeTime.toISOString()} |`);
  if (durationMs !== undefined) lines.push(`| Duration | ${formatDuration(durationMs)} |`);
  lines.push("");

  lines.push("## Timeline");
  lines.push("");
  lines.push("| Phase | Activity | Duration | Status |");
  lines.push("|---|---|---|---|");

  const phases = extractPhaseRecords(config, history, Boolean(closeTime));
  for (const phase of phases) {
    if (phase.activities.length === 0) {
      lines.push(`| ${phase.name} | — | — | — |`);
    }
    for (const act of phase.activities) {
      const dur = act.durationMs !== undefined ? formatDuration(act.durationMs) : "—";
      const statusEmoji = act.status === "completed" ? "✓" : act.status === "failed" ? "✗" : "○";
      lines.push(`| ${phase.name} | ${act.name} | ${dur} | ${statusEmoji} ${act.status} |`);
    }
  }
  lines.push("");

  // Errors section
  const failedEvents = (history.events ?? []).filter(
    (e): e is HistoryEvent & Required<Pick<HistoryEvent, "activityTaskFailedEventAttributes">> =>
      e.eventType === "ActivityTaskFailed" && !!e.activityTaskFailedEventAttributes,
  );

  if (failedEvents.length > 0) {
    lines.push("## Errors");
    lines.push("");
    for (const event of failedEvents) {
      const msg = event.activityTaskFailedEventAttributes?.failure?.message ?? "unknown";
      lines.push(`- ${msg}`);
    }
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`*Generated by chant at ${new Date().toISOString()}*`);
  lines.push("");

  return lines.join("\n");
}

export function writeReport(opName: string, markdown: string): string {
  const outPath = join("dist", `${opName}-report.md`);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, markdown, "utf-8");
  return outPath;
}
