/**
 * Head node: runs slurmctld + slurmdbd, provisions munge key, registers itself in SSM.
 *
 * UserData bootstrap sequence:
 *   1. Install Slurm + munge from SchedMD/OpenHPC repos (Amazon Linux 2)
 *   2. Fetch munge key from SSM Parameter Store (set by SSM Automation after first boot)
 *   3. Fetch Aurora endpoint from SSM, render /etc/slurm/slurmdbd.conf
 *   4. Install SuspendProgram/ResumeProgram hooks for GPU ASG scaling
 *   5. Register this instance ID in SSM (Lambda reads it for SSM Run Command)
 *   6. Start munge, slurmctld, slurmdbd
 *
 * CreationPolicy/ResourceSignal: CloudFormation waits up to 10 minutes for cfn-signal,
 * which is sent at the end of UserData after all services are healthy.
 */

import { Instance } from "@intentius/chant-lexicon-aws";
import { Sub, Join, Base64, Ref } from "@intentius/chant-lexicon-aws";
import { privateSubnet1 } from "./networking";
import { clusterSg } from "./security";
import { headNodeInstanceProfile } from "./iam";
import { scratchFs } from "./storage";
import { config } from "./config";

// Inline bash — runs on first boot via cloud-init.
// Base64(Join) lets us mix plain strings with Sub intrinsics for CFN attribute refs.
// Lines needing CFN variable resolution (AWS::StackName, FSx attrs) use Sub tagged template.
const HEAD_NODE_USERDATA = Base64(Join("\n", [
  "#!/bin/bash",
  "set -euo pipefail",
  "exec > >(tee /var/log/slurm-bootstrap.log) 2>&1",
  "",
  Sub`CLUSTER_NAME=\${AWS::StackName}`,
  "REGION=" + config.region,
  "",
  "# ── 0. Set stable hostname so ControlMachine=head01 resolves ────",
  "hostnamectl set-hostname head01",
  "",
  "# ── 1. Install dependencies ──────────────────────────────────────",
  "amazon-linux-extras install -y epel lustre",
  "yum install -y wget jq",
  "",
  "# SchedMD repo for Slurm 23.11",
  "wget -q https://www.schedmd.com/downloads/archive/23.11/slurm-23.11-latest.el7.noarch.rpm || true",
  "yum install -y munge munge-libs munge-devel",
  "yum install -y slurm slurm-slurmctld slurm-slurmdbd 2>/dev/null || \\",
  "  yum install -y --enablerepo=epel slurm slurm-slurmctld slurm-slurmdbd",
  "# EPEL Slurm 20.11.9 on AL2 omits the useradd %pre scriptlet — create it explicitly",
  "id slurm &>/dev/null || useradd -r -s /bin/false -d /var/lib/slurm slurm",
  "",
  "# ── 2. Mount FSx Lustre ──────────────────────────────────────────",
  "mkdir -p /scratch",
  Sub`mount -t lustre -o relatime,flock ${scratchFs.DNSName}@tcp:/${scratchFs.LustreMountName} /scratch`,
  "# Persist FSx mount across reboots (e.g., head node replacement by CFN update)",
  Sub`echo '${scratchFs.DNSName}@tcp:/${scratchFs.LustreMountName} /scratch lustre relatime,flock,_netdev 0 0' >> /etc/fstab`,
  "mkdir -p /scratch/slurm/state",
  "chown slurm:slurm /scratch/slurm/state",
  "",
  "# ── 3. Fetch munge key from SSM ─────────────────────────────────",
  "# Key is written by SSM Automation after the stack is deployed.",
  "# Retry for up to 10 minutes. If still absent, self-generate and publish",
  "# so the head node can start munge without blocking on automation ordering.",
  "MUNGE_KEY=\"\"",
  "for i in $(seq 1 20); do",
  "  MUNGE_KEY=$(aws ssm get-parameter \\",
  "    --name /$CLUSTER_NAME/munge/key \\",
  "    --with-decryption \\",
  "    --region $REGION \\",
  "    --query Parameter.Value \\",
  "    --output text 2>/dev/null) && break",
  "  echo \"Waiting for munge key in SSM (attempt $i/20)...\"",
  "  sleep 30",
  "done",
  "if [[ -z \"$MUNGE_KEY\" ]]; then",
  "  echo 'Munge key not in SSM after 10 min — self-generating and publishing'",
  "  MUNGE_KEY=$(dd if=/dev/urandom bs=1024 count=1 2>/dev/null | base64 -w 0)",
  "  aws ssm put-parameter \\",
  "    --name /$CLUSTER_NAME/munge/key \\",
  "    --value \"$MUNGE_KEY\" \\",
  "    --type SecureString \\",
  "    --overwrite \\",
  "    --region $REGION",
  "fi",
  "echo \"$MUNGE_KEY\" | base64 -d > /etc/munge/munge.key",
  "chown munge:munge /etc/munge/munge.key",
  "chmod 400 /etc/munge/munge.key",
  "",
  "# ── 4. Fetch Aurora endpoint and secret ARN from SSM, write slurmdbd.conf ────",
  "# Both SSM params are written by CloudFormation (database.ts) before this node starts.",
  "# Reading from SSM avoids rds:DescribeDBClusters and keeps IAM minimal.",
  "DB_HOST=$(aws ssm get-parameter \\",
  "  --name /$CLUSTER_NAME/slurmdbd/endpoint \\",
  "  --region $REGION \\",
  "  --query Parameter.Value --output text)",
  "SECRET_ARN=$(aws ssm get-parameter \\",
  "  --name /$CLUSTER_NAME/slurmdbd/secret-arn \\",
  "  --region $REGION \\",
  "  --query Parameter.Value --output text)",
  "DB_PASS=$(aws secretsmanager get-secret-value \\",
  "  --region $REGION \\",
  "  --secret-id \"$SECRET_ARN\" \\",
  "  --query SecretString --output text | jq -r '.password // .MasterUserPassword')",
  "if [[ -z \"$DB_PASS\" ]]; then",
  "  echo 'ERROR: could not retrieve Aurora DB password from Secrets Manager' >&2",
  "  exit 1",
  "fi",
  "cat > /etc/slurm/slurmdbd.conf << EOF",
  "AuthType=auth/munge",
  "DbdHost=localhost",
  "StorageType=accounting_storage/mysql",
  "StorageHost=$DB_HOST",
  "StorageLoc=slurm_acct_db",
  "StorageUser=slurm",
  "StoragePass=$DB_PASS",
  "LogFile=/var/log/slurmdbd.log",
  "PidFile=/var/run/slurmdbd.pid",
  "EOF",
  "chmod 600 /etc/slurm/slurmdbd.conf",
  "chown slurm:slurm /etc/slurm/slurmdbd.conf",
  "",
  "# ── 5. Install ec2 run-instances scaling hooks ────────────────────",
  "# ResumeProgram: expands nodelist, launches one EC2 instance per node via",
  "# the pre-configured launch template, tags each with slurm-node=<name>.",
  "# The compute UserData reads this tag from IMDS to self-assign its hostname.",
  "# SuspendProgram: terminates instance by slurm-node tag.",
  "",
  "# CPU resume: launch one c5.2xlarge per Slurm node name",
  "cat > /usr/local/bin/slurm_resume_cpu << 'SCRIPT'",
  "#!/bin/bash",
  "REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)",
  "CLUSTER_NAME=$(aws ssm get-parameter \\",
  "  --name /$(hostname -s | sed 's/[0-9]*$//')/cluster-name \\",
  "  --region $REGION --query Parameter.Value --output text 2>/dev/null)",
  "# Fall back: read cluster name from slurm.conf ClusterName line",
  "[ -z \"$CLUSTER_NAME\" ] && CLUSTER_NAME=$(awk -F= '/^ClusterName/{print $2}' /etc/slurm/slurm.conf | tr -d ' ')",
  "LT_ID=$(aws ssm get-parameter \\",
  "  --name /$CLUSTER_NAME/compute/cpu/launch-template-id \\",
  "  --region $REGION --query Parameter.Value --output text)",
  "for NODE in $(scontrol show hostnames \"$1\"); do",
  "  aws ec2 run-instances \\",
  "    --region \"$REGION\" \\",
  "    --launch-template \"LaunchTemplateId=$LT_ID,Version=\\$Latest\" \\",
  "    --tag-specifications \"ResourceType=instance,Tags=[{Key=cluster,Value=$CLUSTER_NAME},{Key=slurm-node,Value=$NODE},{Key=role,Value=compute-cpu}]\" \\",
  "    > /dev/null",
  "  echo \"Launched instance for Slurm node $NODE\"",
  "done",
  "SCRIPT",
  "chmod +x /usr/local/bin/slurm_resume_cpu",
  "",
  "# CPU suspend: terminate instance by slurm-node tag",
  "cat > /usr/local/bin/slurm_suspend_cpu << 'SCRIPT'",
  "#!/bin/bash",
  "REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)",
  "CLUSTER_NAME=$(awk -F= '/^ClusterName/{print $2}' /etc/slurm/slurm.conf | tr -d ' ')",
  "for NODE in $(scontrol show hostnames \"$1\"); do",
  "  INSTANCE_ID=$(aws ec2 describe-instances \\",
  "    --filters \"Name=tag:slurm-node,Values=$NODE\" \\",
  "              \"Name=tag:cluster,Values=$CLUSTER_NAME\" \\",
  "              \"Name=instance-state-name,Values=running,pending\" \\",
  "    --query 'Reservations[0].Instances[0].InstanceId' \\",
  "    --output text --region \"$REGION\")",
  "  if [[ \"$INSTANCE_ID\" != \"None\" && -n \"$INSTANCE_ID\" ]]; then",
  "    aws ec2 terminate-instances --instance-ids \"$INSTANCE_ID\" --region \"$REGION\" > /dev/null",
  "    echo \"Terminated instance $INSTANCE_ID for Slurm node $NODE\"",
  "  fi",
  "done",
  "SCRIPT",
  "chmod +x /usr/local/bin/slurm_suspend_cpu",
  "",
  "# GPU resume: launch one p4d.24xlarge spot instance per Slurm node name",
  "cat > /usr/local/bin/slurm_resume_gpu << 'SCRIPT'",
  "#!/bin/bash",
  "REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)",
  "CLUSTER_NAME=$(awk -F= '/^ClusterName/{print $2}' /etc/slurm/slurm.conf | tr -d ' ')",
  "LT_ID=$(aws ssm get-parameter \\",
  "  --name /$CLUSTER_NAME/compute/gpu/launch-template-id \\",
  "  --region $REGION --query Parameter.Value --output text)",
  "PG=$(aws ssm get-parameter \\",
  "  --name /$CLUSTER_NAME/compute/gpu/placement-group \\",
  "  --region $REGION --query Parameter.Value --output text)",
  "for NODE in $(scontrol show hostnames \"$1\"); do",
  "  aws ec2 run-instances \\",
  "    --region \"$REGION\" \\",
  "    --launch-template \"LaunchTemplateId=$LT_ID,Version=\\$Latest\" \\",
  "    --instance-market-options 'MarketType=spot,SpotOptions={SpotInstanceType=one-time}' \\",
  "    --placement \"GroupName=$PG\" \\",
  "    --tag-specifications \"ResourceType=instance,Tags=[{Key=cluster,Value=$CLUSTER_NAME},{Key=slurm-node,Value=$NODE},{Key=role,Value=compute-gpu}]\" \\",
  "    > /dev/null",
  "  echo \"Launched GPU spot instance for Slurm node $NODE\"",
  "done",
  "SCRIPT",
  "chmod +x /usr/local/bin/slurm_resume_gpu",
  "",
  "# GPU suspend: terminate instance by slurm-node tag",
  "cat > /usr/local/bin/slurm_suspend_gpu << 'SCRIPT'",
  "#!/bin/bash",
  "REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)",
  "CLUSTER_NAME=$(awk -F= '/^ClusterName/{print $2}' /etc/slurm/slurm.conf | tr -d ' ')",
  "for NODE in $(scontrol show hostnames \"$1\"); do",
  "  INSTANCE_ID=$(aws ec2 describe-instances \\",
  "    --filters \"Name=tag:slurm-node,Values=$NODE\" \\",
  "              \"Name=tag:cluster,Values=$CLUSTER_NAME\" \\",
  "              \"Name=instance-state-name,Values=running,pending\" \\",
  "    --query 'Reservations[0].Instances[0].InstanceId' \\",
  "    --output text --region \"$REGION\")",
  "  if [[ \"$INSTANCE_ID\" != \"None\" && -n \"$INSTANCE_ID\" ]]; then",
  "    aws ec2 terminate-instances --instance-ids \"$INSTANCE_ID\" --region \"$REGION\" > /dev/null",
  "    echo \"Terminated GPU instance $INSTANCE_ID for Slurm node $NODE\"",
  "  fi",
  "done",
  "SCRIPT",
  "chmod +x /usr/local/bin/slurm_suspend_gpu",
  "",
  "# Dispatch wrappers: Slurm calls these with nodelist as $1 (e.g. cpu[001-004])",
  "cat > /usr/local/bin/slurm_resume_node << 'SCRIPT'",
  "#!/bin/bash",
  "if echo \"$1\" | grep -q '^cpu'; then",
  "  /usr/local/bin/slurm_resume_cpu \"$1\"",
  "else",
  "  /usr/local/bin/slurm_resume_gpu \"$1\"",
  "fi",
  "SCRIPT",
  "chmod +x /usr/local/bin/slurm_resume_node",
  "",
  "cat > /usr/local/bin/slurm_suspend_node << 'SCRIPT'",
  "#!/bin/bash",
  "if echo \"$1\" | grep -q '^cpu'; then",
  "  /usr/local/bin/slurm_suspend_cpu \"$1\"",
  "else",
  "  /usr/local/bin/slurm_suspend_gpu \"$1\"",
  "fi",
  "SCRIPT",
  "chmod +x /usr/local/bin/slurm_suspend_node",
  "",
  "# ── 6. Register instance ID and private IP in SSM ────────────────",
  "INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)",
  "aws ssm put-parameter \\",
  "  --name /$CLUSTER_NAME/head-node/instance-id \\",
  "  --value \"$INSTANCE_ID\" \\",
  "  --type String \\",
  "  --overwrite \\",
  "  --region $REGION",
  "PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)",
  "aws ssm put-parameter \\",
  "  --name /$CLUSTER_NAME/head-node/private-ip \\",
  "  --value \"$PRIVATE_IP\" \\",
  "  --type String \\",
  "  --overwrite \\",
  "  --region $REGION",
  "",
  "# ── 7. Start services ────────────────────────────────────────────",
  "systemctl enable --now munge",
  "systemctl enable --now slurmdbd",
  "sleep 5   # let slurmdbd initialize before slurmctld connects",
  "systemctl enable --now slurmctld",
  "",
  "# Signal CloudFormation that bootstrap completed successfully",
  Sub`cfn-signal -e $? --stack \${AWS::StackName} --resource headNode --region \${AWS::Region}`,
]));

export const headNode = new Instance(
  {
    ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}",
    InstanceType: config.headNodeInstanceType,
    IamInstanceProfile: Ref(headNodeInstanceProfile),
    SubnetId: privateSubnet1.SubnetId,
    SecurityGroupIds: [clusterSg.GroupId],
    UserData: HEAD_NODE_USERDATA,
    Tags: [
      { Key: "Name", Value: Sub("\${AWS::StackName}-head") },
      { Key: "cluster", Value: Sub("\${AWS::StackName}") },
      { Key: "role", Value: "head" },
    ],
  },
  {
    CreationPolicy: { ResourceSignal: { Timeout: "PT30M" } },
  },
);
