import { Role, InstanceProfile } from "@intentius/chant-lexicon-aws";
import { Sub, Ref } from "@intentius/chant-lexicon-aws";
import { scratchFs } from "./storage";
import { dbCluster } from "./database";
import { config } from "./config";

const EC2_ASSUME_ROLE = {
  Version: "2012-10-17",
  Statement: [{ Effect: "Allow", Principal: { Service: "ec2.amazonaws.com" }, Action: "sts:AssumeRole" }],
};

// ── Compute node role ─────────────────────────────────────────────
// Compute nodes need: SSM (for fleet management), FSx access, CloudWatch metrics

export const computeRole = new Role({
  RoleName: Sub("\${AWS::StackName}-compute-role"),
  AssumeRolePolicyDocument: EC2_ASSUME_ROLE,
  ManagedPolicyArns: [
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
  ],
  Policies: [
    {
      PolicyName: "fsx-access",
      PolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Action: ["fsx:DescribeFileSystems", "fsx:CreateDataRepositoryTask"],
            Resource: [scratchFs.ResourceARN],
          },
        ],
      },
    },
    {
      PolicyName: "slurm-config-read",
      PolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            // Read munge key (SecureString), slurm.conf, topology/cgroup conf, head node IP
            Effect: "Allow",
            Action: ["ssm:GetParameter"],
            Resource: [
              Sub(`arn:aws:ssm:${config.region}:*:parameter/\${AWS::StackName}/munge/key`),
              Sub(`arn:aws:ssm:${config.region}:*:parameter/\${AWS::StackName}/slurm/*`),
              Sub(`arn:aws:ssm:${config.region}:*:parameter/\${AWS::StackName}/head-node/private-ip`),
            ],
          },
          {
            // Decrypt the munge key SecureString (uses AWS managed key aws/ssm)
            Effect: "Allow",
            Action: ["kms:Decrypt"],
            Resource: ["*"],
          },
        ],
      },
    },
  ],
});

export const computeInstanceProfile = new InstanceProfile({
  InstanceProfileName: Sub("\${AWS::StackName}-compute-profile"),
  Roles: [Ref(computeRole)],
});

// ── Head node role ────────────────────────────────────────────────
// Head node needs: Secrets Manager (slurmdbd), SSM, FSx, and EC2 permissions
// for the ResumeProgram/SuspendProgram (run-instances / terminate-instances).

export const headNodeRole = new Role({
  RoleName: Sub("\${AWS::StackName}-head-role"),
  AssumeRolePolicyDocument: EC2_ASSUME_ROLE,
  ManagedPolicyArns: [
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy",
  ],
  Policies: [
    {
      PolicyName: "slurmdbd-secrets",
      PolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Action: ["secretsmanager:GetSecretValue"],
            // Dotted CFN attribute: use underscore alias generated by chant (MasterUserSecret_SecretArn → Fn::GetAtt MasterUserSecret.SecretArn)
            Resource: [dbCluster.MasterUserSecret_SecretArn],
          },
          {
            Effect: "Allow",
            Action: ["ssm:GetParameter", "ssm:PutParameter"],
            Resource: [Sub(`arn:aws:ssm:${config.region}:*:parameter/\${AWS::StackName}/*`)],
          },
          {
            // SSM path for public AMI lookups (used by ResumeProgram to find latest AL2 AMI)
            Effect: "Allow",
            Action: ["ssm:GetParameter"],
            Resource: ["arn:aws:ssm:*::parameter/aws/service/ami-amazon-linux-latest/*"],
          },
          {
            Effect: "Allow",
            Action: ["fsx:DescribeFileSystems", "fsx:CreateDataRepositoryTask"],
            Resource: [scratchFs.ResourceARN],
          },
          {
            // ResumeProgram: launch compute instances via ec2 run-instances using launch template
            Effect: "Allow",
            Action: ["ec2:RunInstances"],
            Resource: ["*"],
          },
          {
            // SuspendProgram: terminate compute instances tagged with cluster name
            Effect: "Allow",
            Action: ["ec2:TerminateInstances"],
            Resource: ["arn:aws:ec2:*:*:instance/*"],
            Condition: {
              StringEquals: {
                "ec2:ResourceTag/cluster": Sub("\${AWS::StackName}"),
              },
            },
          },
          {
            Effect: "Allow",
            Action: ["ec2:DescribeInstances"],
            Resource: ["*"],
          },
          {
            // Required for ec2:RunInstances with --iam-instance-profile
            Effect: "Allow",
            Action: ["iam:PassRole"],
            Resource: [computeRole.Arn],
          },
        ],
      },
    },
  ],
});

export const headNodeInstanceProfile = new InstanceProfile({
  InstanceProfileName: Sub("\${AWS::StackName}-head-profile"),
  Roles: [Ref(headNodeRole)],
});

// ── Spot interruption Lambda role ─────────────────────────────────

const LAMBDA_ASSUME_ROLE = {
  Version: "2012-10-17",
  Statement: [{ Effect: "Allow", Principal: { Service: "lambda.amazonaws.com" }, Action: "sts:AssumeRole" }],
};

// ── SSM Automation role ────────────────────────────────────────────
// aws:executeScript steps run Lambda-like and need explicit IAM permissions
// to call other AWS services. aws:runCommand also needs ssm:SendCommand.

export const automationRole = new Role({
  RoleName: Sub("\${AWS::StackName}-automation-role"),
  AssumeRolePolicyDocument: {
    Version: "2012-10-17",
    Statement: [{ Effect: "Allow", Principal: { Service: "ssm.amazonaws.com" }, Action: "sts:AssumeRole" }],
  },
  ManagedPolicyArns: ["arn:aws:iam::aws:policy/AmazonSSMFullAccess"],
  Policies: [
    {
      PolicyName: "automation-kms",
      PolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Action: ["kms:Decrypt", "kms:GenerateDataKey"],
            Resource: ["*"],
          },
        ],
      },
    },
  ],
});

export const spotHandlerRole = new Role({
  RoleName: Sub("\${AWS::StackName}-spot-handler-role"),
  AssumeRolePolicyDocument: LAMBDA_ASSUME_ROLE,
  ManagedPolicyArns: ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"],
  Policies: [
    {
      PolicyName: "ssm-run-command",
      PolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Action: ["ssm:SendCommand", "ssm:GetCommandInvocation"],
            Resource: ["*"],
          },
          {
            Effect: "Allow",
            Action: ["ssm:GetParameter"],
            Resource: [Sub(`arn:aws:ssm:${config.region}:*:parameter/\${AWS::StackName}/head-node/*`)],
          },
          {
            Effect: "Allow",
            Action: ["ec2:DescribeInstances"],
            Resource: ["*"],
          },
          {
            Effect: "Allow",
            Action: ["autoscaling:CompleteLifecycleAction"],
            Resource: ["*"],
          },
        ],
      },
    },
  ],
});
