import { open } from "node:fs/promises";
import { relative, sep, isAbsolute } from "node:path";
// @ts-ignore — picomatch has no types declaration
import picomatch from "picomatch";
import { resolveDiscoveryGlobs, type DiscoveryGlobs } from "../config";
import { readHead, walkDiscovery, workspaceMemberDirs } from "./walk";

/**
 * Marker chant writes at the top of files it generates (a hosting lexicon's
 * worker/bootstrap output, and the like). Discovery must not treat these as
 * authored infra source: they hold no Declarables, they self-execute on import,
 * and they use runtime patterns the authored-source lint
 * rules forbid (dynamic `process.env[...]` access, spreads). Skipping them keeps
 * `chant lint`/`build` from importing or linting the tool's own output.
 */
export const GENERATED_MARKER = "Generated by chant — do not edit directly";

/**
 * Comment a hand-written file carries to keep discovery out of it (#2519): a
 * runnable script with top-level side effects, say, that lives next to the
 * project's declarations. It must be a comment of its own (`// chant-discovery-skip`
 * or inside a block comment) within the first {@link SKIP_MARKER_HEAD_BYTES}
 * bytes of the file. See {@link hasSkipMarker}.
 */
export const SKIP_MARKER = "chant-discovery-skip";

/** How much of a file's head {@link hasSkipMarker} reads: room for a shebang and a license header. */
const SKIP_MARKER_HEAD_BYTES = 1024;

/** {@link SKIP_MARKER} opening a `//`, `/*` or ` * ` comment line, as a whole word. */
const SKIP_MARKER_PATTERN = /^[ \t]*(?:\/\/|\/\*+|\*)[ \t]*chant-discovery-skip(?![\w-])/m;

/** True when `head`, the start of a file, carries the {@link SKIP_MARKER} comment. */
export function hasSkipMarker(head: string): boolean {
  return SKIP_MARKER_PATTERN.test(head.slice(0, SKIP_MARKER_HEAD_BYTES));
}

/**
 * Whether a file's head carries the {@link GENERATED_MARKER} or the
 * {@link SKIP_MARKER}. Reads only the head. The generated marker is looked for
 * in the first 256 bytes, as it always was.
 */
export async function hasDiscoveryMarker(file: string): Promise<boolean> {
  let fh;
  try {
    fh = await open(file, "r");
    const { buffer, bytesRead } = await fh.read({ buffer: Buffer.alloc(SKIP_MARKER_HEAD_BYTES), position: 0 });
    if (buffer.toString("utf8", 0, Math.min(bytesRead, 256)).includes(GENERATED_MARKER)) return true;
    return hasSkipMarker(buffer.toString("utf8", 0, bytesRead));
  } catch {
    return false;
  } finally {
    await fh?.close();
  }
}

/** Whether a file's head carries the {@link GENERATED_MARKER} or the {@link SKIP_MARKER}. The synchronous form of {@link hasDiscoveryMarker}. */
export function hasDiscoveryMarkerSync(file: string): boolean {
  const head = readHead(file, SKIP_MARKER_HEAD_BYTES);
  return head.slice(0, 256).includes(GENERATED_MARKER) || hasSkipMarker(head);
}

/**
 * Compile a project's `exclude`/`include` globs (#2519) into a predicate that
 * is true for a file discovery must skip, or `undefined` when there is nothing
 * to skip.
 *
 * Each pattern is matched, with picomatch and dot files included, against the
 * file's path relative to `globs.root` (forward slashes) and against the path
 * of every directory above it, so a pattern naming a directory covers
 * everything under it. A file is skipped when some `exclude` pattern matches
 * and no `include` pattern does: `include` always wins. Files outside
 * `globs.root` are never skipped. The discovery walk (`./walk.ts`) applies the
 * same rule, and also lets `include` re-admit what its default rules skip.
 */
export function compileDiscoveryFilter(globs: DiscoveryGlobs | undefined): ((file: string) => boolean) | undefined {
  if (!globs || globs.exclude.length === 0) return undefined;
  const excluded = picomatch(globs.exclude, { dot: true });
  const included = globs.include.length > 0 ? picomatch(globs.include, { dot: true }) : () => false;
  return (file: string): boolean => {
    const rel = relative(globs.root, file);
    if (rel === "" || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) return false;
    const parts = rel.split(sep);
    const candidates = parts.map((_, i) => parts.slice(0, i + 1).join("/"));
    return candidates.some((c) => excluded(c)) && !candidates.some((c) => included(c));
  };
}

/** Options for {@link findInfraFiles}. */
export interface FindInfraFilesOptions {
  /**
   * The project's discovery globs. Omitted, they are read from the project
   * config `path` belongs to ({@link resolveDiscoveryGlobs}); `null` applies none.
   */
  globs?: DiscoveryGlobs | null;
}

/** A TypeScript source file by name: `.ts`, not a test or spec. */
export function isSourceFileName(name: string): boolean {
  return name.endsWith(".ts") && !name.endsWith(".test.ts") && !name.endsWith(".spec.ts");
}

/**
 * Find every TypeScript infrastructure file under `path`, through the one
 * discovery walk (`./walk.ts`, #2527): test and spec files, chant-generated
 * files, skip-marked files and whatever the walk's rules and the project's
 * globs skip are left out.
 */
export async function findInfraFiles(path: string, options?: FindInfraFilesOptions): Promise<string[]> {
  const globs = options?.globs === null ? undefined : (options?.globs ?? (await resolveDiscoveryGlobs(path)));
  return walkDiscovery({
    walker: "source",
    root: path,
    globs,
    excludeDirs: await workspaceMemberDirs(path),
    accept: (name, full) => isSourceFileName(name) && !hasDiscoveryMarkerSync(full),
  });
}
