#!/usr/bin/env bash
set -euo pipefail

set -a; source .env; set +a

# Download the gitlab/gitlab chart dependency declared in gitlab-cell/Chart.yaml.
# helm dep update reads the repo URL from Chart.yaml — no `helm repo add` needed.
helm dependency update ./gitlab-cell/

# Deploy canary cells first (per-cell values-<name>.yaml files are generated by npm run build:helm into gitlab-cell/)
for VALUES_FILE in gitlab-cell/values-*.yaml; do
  [[ "$VALUES_FILE" == "gitlab-cell/values-base.yaml" ]] && continue
  [[ "$VALUES_FILE" == "gitlab-cell/values-runtime-slots.yaml" ]] && continue
  [[ "$VALUES_FILE" == "gitlab-cell/values.yaml" ]] && continue
  [ -f "$VALUES_FILE" ] || continue
  CELL=$(basename "$VALUES_FILE" .yaml | sed 's/values-//')
  IS_CANARY=$(kubectl get ns "cell-${CELL}" -o jsonpath='{.metadata.labels.gitlab\.example\.com/canary}' 2>/dev/null || echo "false")
  if [ "$IS_CANARY" = "true" ]; then
    echo "Deploying canary cell: ${CELL}"
    helm upgrade --install "gitlab-cell-${CELL}" ./gitlab-cell/ \
      -n "cell-${CELL}" -f gitlab-cell/values-base.yaml -f "$VALUES_FILE" --wait --timeout=900s
    kubectl -n "cell-${CELL}" rollout status "deploy/gitlab-cell-${CELL}-webservice-default" --timeout=300s
    echo "Canary cell ${CELL} deployed successfully"
  fi
done

# Deploy remaining cells
for VALUES_FILE in gitlab-cell/values-*.yaml; do
  [[ "$VALUES_FILE" == "gitlab-cell/values-base.yaml" ]] && continue
  [[ "$VALUES_FILE" == "gitlab-cell/values-runtime-slots.yaml" ]] && continue
  [[ "$VALUES_FILE" == "gitlab-cell/values.yaml" ]] && continue
  [ -f "$VALUES_FILE" ] || continue
  CELL=$(basename "$VALUES_FILE" .yaml | sed 's/values-//')
  IS_CANARY=$(kubectl get ns "cell-${CELL}" -o jsonpath='{.metadata.labels.gitlab\.example\.com/canary}' 2>/dev/null || echo "false")
  if [ "$IS_CANARY" != "true" ]; then
    echo "Deploying cell: ${CELL}"
    helm upgrade --install "gitlab-cell-${CELL}" ./gitlab-cell/ \
      -n "cell-${CELL}" -f gitlab-cell/values-base.yaml -f "$VALUES_FILE" --wait --timeout=900s
    kubectl -n "cell-${CELL}" rollout status "deploy/gitlab-cell-${CELL}-webservice-default" --timeout=300s
    echo "Cell ${CELL} deployed successfully"
  fi
done

echo "All cells deployed."
