// Throwaway spike for chant #3195: read a pinned clickhouse-server's system.* tables
// over the HTTP interface and write a types file plus the parsed catalog.
// Usage: CH_URL=http://127.0.0.1:8123 node generate.mjs <outDir>
// No dependencies; node >= 18 for fetch.
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const url = process.env.CH_URL ?? "http://127.0.0.1:8123";
const outDir = process.argv[2] ?? "out";

async function q(sql) {
  const res = await fetch(`${url}/?default_format=JSONEachRow`, { method: "POST", body: sql });
  if (!res.ok) throw new Error(`${sql}\n${await res.text()}`);
  const text = await res.text();
  return text.split("\n").filter(Boolean).map((l) => JSON.parse(l));
}

const version = (await q("select version() as v"))[0].v;

// Each table is read with an explicit ORDER BY: system tables have no stable row order.
// Columns that depend on the host or on server config (value, changed) are never selected.
const T = {
  engines: await q("select name, supports_settings, supports_skipping_indices, supports_projections, supports_sort_order, supports_ttl, supports_replication, supports_deduplication, supports_parallel_insert, syntax, description from system.table_engines order by name"),
  dbEngines: await q("select name, syntax, description from system.database_engines order by name"),
  types: await q("select name, case_insensitive, alias_to, syntax, description from system.data_type_families order by name"),
  settings: await q("select name, type, default, min, max, disallowed_values, readonly, is_obsolete, tier, alias_for, description from system.settings order by name"),
  mtSettings: await q("select name, type, default, min, max, disallowed_values, readonly, is_obsolete, tier, description from system.merge_tree_settings order by name"),
  functions: await q("select name, is_aggregate, case_insensitive, alias_to, syntax from system.functions where origin = 'System' order by name"),
  formats: await q("select name, is_input, is_output from system.formats order by name"),
  // Beyond the seven tables the issue lists:
  codecs: await q("select name, is_compression, is_generic_compression, is_encryption, is_timeseries_codec, is_experimental, description from system.codecs order by name"),
  indexTypes: await q("select name, syntax, description from system.data_skipping_index_types order by name"),
  combinators: await q("select name, is_internal, syntax from system.aggregate_function_combinators order by name"),
  tableFunctions: await q("select name from system.table_functions order by name"),
  keywords: await q("select keyword from system.keywords order by keyword").catch(() => []),
};

// Host-dependent defaults: max_threads is auto(<cores>) on every machine.
const norm = (d) => (typeof d === "string" ? d.replace(/auto\(\d+\)/g, "auto") : d);
const oneLine = (s) =>
  (s ?? "").split("\n").map((l) => l.trim()).find((l) => l && !l.startsWith("#") && !l.startsWith("```")) ?.replace(/\*\//g, "*\\/").slice(0, 200) ?? "";
const key = (n) => (/^[A-Za-z_$][\w$]*$/.test(n) ? n : JSON.stringify(n));
const lit = (names) => names.length ? names.map((n) => JSON.stringify(n)).join(" | ") : "never";

const TS_TYPE = {
  Bool: "boolean", BoolAuto: 'boolean | "auto"',
  UInt64: "number", Int64: "number", UInt32: "number", Int32: "number", Float: "number", Double: "number",
  Seconds: "number", Milliseconds: "number", NonZeroUInt64: "number", MaxThreads: "number",
  UInt64Auto: 'number | "auto"', FloatAuto: 'number | "auto"',
  String: "string", Char: "string", URI: "string",
};
const tsType = (t) => TS_TYPE[t] ?? "string"; // enum-typed settings: the catalog gives no member list
const enumTyped = (rows) => rows.filter((r) => !(r.type in TS_TYPE));

function settingsInterface(name, rows) {
  const lines = [`export interface ${name} {`];
  for (const r of rows) {
    const doc = [oneLine(r.description)];
    if (r.is_obsolete || r.tier === "Obsolete") doc.push("@deprecated obsolete");
    if (r.tier === "Experimental" || r.tier === "Beta") doc.push(`@tier ${r.tier}`);
    if (r.alias_for) doc.push(`@alias ${r.alias_for}`);
    doc.push(`@default ${JSON.stringify(norm(r.default))}`);
    lines.push(`  /** ${doc.filter(Boolean).join(" | ")} */`);
    lines.push(`  ${key(r.name)}?: ${tsType(r.type)};`);
  }
  lines.push("}");
  return lines.join("\n");
}

const mergeTree = T.engines.filter((e) => /MergeTree$/.test(e.name));
const canonicalTypes = T.types.filter((t) => !t.alias_to);
const aliasTypes = T.types.filter((t) => t.alias_to);

const dts = [
  `// Generated by spikes/sql-clickhouse-types from clickhouse-server ${version}. Do not edit.`,
  `export const CLICKHOUSE_VERSION = ${JSON.stringify(version)};`,
  ``,
  `export type TableEngineName = ${lit(T.engines.map((e) => e.name))};`,
  `export type MergeTreeEngineName = ${lit(mergeTree.map((e) => e.name))};`,
  `export type DatabaseEngineName = ${lit(T.dbEngines.map((e) => e.name))};`,
  `export type ColumnTypeFamily = ${lit(canonicalTypes.map((t) => t.name))};`,
  `export type ColumnTypeAlias = ${lit(aliasTypes.map((t) => t.name))};`,
  `export type CodecName = ${lit(T.codecs.map((c) => c.name))};`,
  `export type SkipIndexType = ${lit(T.indexTypes.map((c) => c.name))};`,
  `export type AggregateCombinator = ${lit(T.combinators.filter((c) => !c.is_internal).map((c) => c.name))};`,
  `export type TableFunctionName = ${lit(T.tableFunctions.map((c) => c.name))};`,
  `export type FormatName = ${lit(T.formats.map((f) => f.name))};`,
  `export type InputFormatName = ${lit(T.formats.filter((f) => f.is_input).map((f) => f.name))};`,
  `export type OutputFormatName = ${lit(T.formats.filter((f) => f.is_output).map((f) => f.name))};`,
  `export type AggregateFunctionName = ${lit(T.functions.filter((f) => f.is_aggregate).map((f) => f.name))};`,
  `export type ScalarFunctionName = ${lit(T.functions.filter((f) => !f.is_aggregate).map((f) => f.name))};`,
  ``,
  `/** Capability flags per table engine, as the server reports them. */`,
  `export interface TableEngineCapabilities { settings: boolean; skippingIndices: boolean; projections: boolean; sortOrder: boolean; ttl: boolean; replication: boolean; deduplication: boolean; parallelInsert: boolean; }`,
  ``,
  settingsInterface("MergeTreeSettings", T.mtSettings),
  ``,
  settingsInterface("QuerySettings", T.settings),
  ``,
].join("\n");

const catalog = {
  version,
  counts: Object.fromEntries(Object.entries(T).map(([k, v]) => [k, v.length])),
  enumTypedSettings: {
    mergeTree: enumTyped(T.mtSettings).map((r) => `${r.name}:${r.type}`),
    query: enumTyped(T.settings).map((r) => `${r.name}:${r.type}`),
  },
  tableEngines: T.engines.map((e) => ({
    name: e.name, syntax: e.syntax,
    capabilities: {
      settings: !!e.supports_settings, skippingIndices: !!e.supports_skipping_indices, projections: !!e.supports_projections,
      sortOrder: !!e.supports_sort_order, ttl: !!e.supports_ttl, replication: !!e.supports_replication,
      deduplication: !!e.supports_deduplication, parallelInsert: !!e.supports_parallel_insert,
    },
  })),
  databaseEngines: T.dbEngines.map((e) => ({ name: e.name, syntax: e.syntax })),
  typeFamilies: T.types.map((t) => ({ name: t.name, caseInsensitive: !!t.case_insensitive, aliasOf: t.alias_to || undefined })),
  codecs: T.codecs.map((c) => ({ name: c.name, compression: !!c.is_compression, generic: !!c.is_generic_compression, encryption: !!c.is_encryption, timeseries: !!c.is_timeseries_codec, experimental: !!c.is_experimental })),
  skipIndexTypes: T.indexTypes.map((c) => ({ name: c.name, syntax: c.syntax })),
  aggregateCombinators: T.combinators.map((c) => ({ name: c.name, internal: !!c.is_internal, syntax: c.syntax })),
  tableFunctions: T.tableFunctions.map((c) => c.name),
  formats: T.formats.map((f) => ({ name: f.name, input: !!f.is_input, output: !!f.is_output })),
  functions: T.functions.map((f) => ({ name: f.name, aggregate: !!f.is_aggregate, caseInsensitive: !!f.case_insensitive, aliasOf: f.alias_to || undefined })),
  keywords: T.keywords.map((k) => k.keyword),
  mergeTreeSettings: T.mtSettings.map((r) => ({ name: r.name, type: r.type, default: norm(r.default), min: r.min, max: r.max, tier: r.tier, obsolete: !!r.is_obsolete })),
  querySettings: T.settings.map((r) => ({ name: r.name, type: r.type, default: norm(r.default), min: r.min, max: r.max, tier: r.tier, obsolete: !!r.is_obsolete, aliasFor: r.alias_for || undefined })),
};

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "clickhouse-types.d.ts"), dts + "\n");
writeFileSync(join(outDir, "clickhouse-catalog.json"), JSON.stringify(catalog, null, 2) + "\n");
console.log(version, JSON.stringify(catalog.counts));
