// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { sqlch101 } from "./sqlch101";
import { sqlch102 } from "./sqlch102";
import { sqlch103 } from "./sqlch103";
import { sqlch104 } from "./sqlch104";
import { sqlch105 } from "./sqlch105";
import { sqlch106 } from "./sqlch106";
import { sqlch107 } from "./sqlch107";
import { sqlch108 } from "./sqlch108";
import { sqlch109 } from "./sqlch109";
import { sqlch110 } from "./sqlch110";
import { sqlch111 } from "./sqlch111";
import { sqlch112 } from "./sqlch112";
import { sqlch113 } from "./sqlch113";
import { sqlch114 } from "./sqlch114";
import { sqlch115 } from "./sqlch115";
import { sqlch116 } from "./sqlch116";
import { sqlch117 } from "./sqlch117";
import { sqlch118 } from "./sqlch118";
import { sqlch119 } from "./sqlch119";
import { sqlch120 } from "./sqlch120";

export const postSynthChecks: PostSynthCheck[] = [
  sqlch101,
  sqlch102,
  sqlch103,
  sqlch104,
  sqlch105,
  sqlch106,
  sqlch107,
  sqlch108,
  sqlch109,
  sqlch110,
  sqlch111,
  sqlch112,
  sqlch113,
  sqlch114,
  sqlch115,
  sqlch116,
  sqlch117,
  sqlch118,
  sqlch119,
  sqlch120,
];
