// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { otel101 } from "./otel101";
import { otel102 } from "./otel102";
import { otel103 } from "./otel103";
import { otel104 } from "./otel104";
import { otel105 } from "./otel105";
import { otel106 } from "./otel106";
import { otel107 } from "./otel107";
import { otel108 } from "./otel108";
import { otel109 } from "./otel109";
import { otel112 } from "./otel112";
import { otel113 } from "./otel113";
import { otel114 } from "./otel114";
import { otel115 } from "./otel115";
import { otel116 } from "./otel116";
import { otel117 } from "./otel117";

export const postSynthChecks: PostSynthCheck[] = [
  otel101,
  otel102,
  otel103,
  otel104,
  otel105,
  otel106,
  otel107,
  otel108,
  otel109,
  otel112,
  otel113,
  otel114,
  otel115,
  otel116,
  otel117,
];
