// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { otel101 } from "./otel101";
import { otel102 } from "./otel102";
import { otel103 } from "./otel103";
import { otel104 } from "./otel104";
import { otel105 } from "./otel105";
import { otel106 } from "./otel106";
import { otel107 } from "./otel107";
import { otel108 } from "./otel108";
import { otel109 } from "./otel109";

export const postSynthChecks: PostSynthCheck[] = [
  otel101,
  otel102,
  otel103,
  otel104,
  otel105,
  otel106,
  otel107,
  otel108,
  otel109,
];
