// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { otel101 } from "./otel101";
import { otel102 } from "./otel102";
import { otel103 } from "./otel103";
import { otel104 } from "./otel104";
import { otel105 } from "./otel105";
import { otel106 } from "./otel106";
import { otel107 } from "./otel107";
import { otel108 } from "./otel108";
import { otel109 } from "./otel109";
import { otel112 } from "./otel112";
import { otel113 } from "./otel113";
import { otel114 } from "./otel114";
import { otel115 } from "./otel115";
import { otel116 } from "./otel116";
import { otel117 } from "./otel117";
import { otel119 } from "./otel119";
import { otel120 } from "./otel120";
import { otel121 } from "./otel121";
import { otel122 } from "./otel122";
import { otel123 } from "./otel123";
import { otel124 } from "./otel124";
import { otel125 } from "./otel125";
import { otel126 } from "./otel126";
import { otel127 } from "./otel127";

export const postSynthChecks: PostSynthCheck[] = [
  otel101,
  otel102,
  otel103,
  otel104,
  otel105,
  otel106,
  otel107,
  otel108,
  otel109,
  otel112,
  otel113,
  otel114,
  otel115,
  otel116,
  otel117,
  otel119,
  otel120,
  otel121,
  otel122,
  otel123,
  otel124,
  otel125,
  otel126,
  otel127,
];
