// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { gha006 } from "./gha006";
import { gha009 } from "./gha009";
import { gha011 } from "./gha011";
import { gha013 } from "./gha013";
import { gha017 } from "./gha017";
import { gha018 } from "./gha018";
import { gha019 } from "./gha019";
import { gha021 } from "./gha021";
import { gha022 } from "./gha022";
import { gha023 } from "./gha023";
import { gha024 } from "./gha024";
import { gha025 } from "./gha025";
import { gha026 } from "./gha026";
import { gha027 } from "./gha027";
import { gha028 } from "./gha028";
import { gha029 } from "./gha029";
import { gha030 } from "./gha030";
import { gha031 } from "./gha031";
import { gha032 } from "./gha032";
import { gha033 } from "./gha033";
import { gha034 } from "./gha034";
import { gha035 } from "./gha035";
import { gha036 } from "./gha036";
import { gha037 } from "./gha037";
import { gha038 } from "./gha038";
import { gha039 } from "./gha039";
import { gha040 } from "./gha040";
import { gha041 } from "./gha041";
import { gha042 } from "./gha042";
import { gha043 } from "./gha043";
import { gha044 } from "./gha044";
import { gha045 } from "./gha045";
import { gha046 } from "./gha046";
import { gha047 } from "./gha047";
import { gha048 } from "./gha048";
import { gha049 } from "./gha049";
import { gha050 } from "./gha050";
import { gha051 } from "./gha051";
import { gha052 } from "./gha052";
import { gha053 } from "./gha053";
import { gha054 } from "./gha054";
import { gha055 } from "./gha055";
import { gha056 } from "./gha056";
import { gha057 } from "./gha057";
import { gha058 } from "./gha058";

export const postSynthChecks: PostSynthCheck[] = [
  gha006,
  gha009,
  gha011,
  gha013,
  gha017,
  gha018,
  gha019,
  gha021,
  gha022,
  gha023,
  gha024,
  gha025,
  gha026,
  gha027,
  gha028,
  gha029,
  gha030,
  gha031,
  gha032,
  gha033,
  gha034,
  gha035,
  gha036,
  gha037,
  gha038,
  gha039,
  gha040,
  gha041,
  gha042,
  gha043,
  gha044,
  gha045,
  gha046,
  gha047,
  gha048,
  gha049,
  gha050,
  gha051,
  gha052,
  gha053,
  gha054,
  gha055,
  gha056,
  gha057,
  gha058,
];
