/**
 * Codegen helpers shared between Op codegen (`./op/serializer.ts`,
 * `Temporal::Op` → `dist/ops/<name>/*`) and the durable component codegen
 * (`./component-op/serializer.ts`, #589 → `dist/components/<name>/*`).
 *
 * Factored out rather than duplicated so a future change to name-mangling or
 * worker bootstrap (TLS/apiKey handling, profile resolution) only needs to be
 * made once and both codegen paths pick it up identically.
 */

// ── Name helpers ──────────────────────────────────────────────────────────────

export function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/** "gate-dns-delegation" → "resumeDnsDelegation". Shared by both codegen paths' gate signal declarations. */
export function signalVarName(signalName: string): string {
  const withoutGate = signalName.startsWith("gate-") ? signalName.slice(5) : signalName;
  return "resume" + kebabToCamel(withoutGate).replace(/^./, (c) => c.toUpperCase());
}

/**
 * Guarantee the result is a syntactically valid JS identifier, regardless of
 * what characters `raw` contains. Strips everything but ASCII
 * letters/digits/underscore/dollar, then prefixes an underscore if the first
 * character would otherwise be a digit (or the whole string collapsed to
 * empty). Used by the component codegen (`../component-op/serializer.ts`) to
 * harden `workflowFnName`/`signalVarName` against schema-legal but
 * identifier-hostile input: a component `name` may start with a digit
 * (`^[a-z0-9]+(-[a-z0-9]+)*$` allows e.g. "3d-viewer"), and a `Gate.signalName`
 * has no pattern constraint at all (schema: `{ type: "string", minLength: 1 }`)
 * — so it may contain spaces, punctuation, or anything else a component
 * author writes. Without this guard, codegen could emit a syntax error (e.g.
 * `export async function 3dViewerComponentWorkflow()` or `const resumeGate
 * approve! = ...`) instead of a working workflow.
 */
export function safeIdentifier(raw: string): string {
  const stripped = raw.replace(/[^A-Za-z0-9_$]/g, "");
  return /^[A-Za-z_$]/.test(stripped) ? stripped : `_${stripped}`;
}

// ── Worker bootstrap ──────────────────────────────────────────────────────────

export interface WorkerBootstrapOptions {
  /** Directory segment under `dist/` the generated worker lives in, e.g. "ops" or "components". Used only for the `// Run: npx tsx <dir>/<name>/worker.ts` comment. */
  dir: string;
  /** Op or component name — the generated output directory. */
  name: string;
  /** Fallback task queue when the resolved Temporal profile names none. An Op may override this via its own `taskQueue` field; a component has no such field, so callers pass `name` directly. */
  taskQueue: string;
}

/**
 * Generate `worker.ts`'s content: reads the named Temporal profile from
 * `chant.config.ts`, connects, and starts a `Worker` polling the profile's
 * task queue (or `taskQueue` as the default). Identical for both Op and
 * component workers — the only per-caller difference is the `// Run:`
 * comment path and the default task queue's source.
 */
export function generateWorkerBootstrap({ dir, name, taskQueue }: WorkerBootstrapOptions): string {
  return [
    "// Generated by chant — do not edit directly.",
    `// Run: npx tsx ${dir}/${name}/worker.ts`,
    "import { Worker, NativeConnection } from '@temporalio/worker';",
    "import { fileURLToPath } from 'url';",
    "import * as activities from './activities.js';",
    "",
    "async function run(): Promise<void> {",
    "  const { default: chantConfig } = await import('../../chant.config.js');",
    "",
    `  const profileName = process.env.TEMPORAL_PROFILE ?? chantConfig.temporal?.defaultProfile ?? 'local';`,
    "  const profile = chantConfig.temporal?.profiles?.[profileName];",
    "",
    "  if (!profile) {",
    "    console.error(",
    `      \`Unknown Temporal profile "\${profileName}". Available: \${Object.keys(chantConfig.temporal?.profiles ?? {}).join(', ')}\`,`,
    "    );",
    "    process.exit(1);",
    "  }",
    "",
    "  const apiKey =",
    "    typeof profile.apiKey === 'object' && profile.apiKey !== null",
    "      ? process.env[(profile.apiKey as { env: string }).env]",
    "      : (profile.apiKey as string | undefined);",
    "",
    "  const connection = await NativeConnection.connect({",
    "    address: profile.address,",
    "    ...(profile.tls && {",
    "      tls: typeof profile.tls === 'object' ? profile.tls : {},",
    "      metadata: apiKey ? { Authorization: `Bearer ${apiKey}` } : {},",
    "    }),",
    "  });",
    "",
    "  const worker = await Worker.create({",
    "    connection,",
    "    namespace: profile.namespace,",
    `    taskQueue: profile.taskQueue ?? ${JSON.stringify(taskQueue)},`,
    "    workflowsPath: fileURLToPath(new URL('./workflow.js', import.meta.url)),",
    "    activities,",
    "  });",
    "",
    `  console.log(\`Worker ready — polling task queue: \${profile.taskQueue ?? ${JSON.stringify(taskQueue)}}\`);`,
    "  await worker.run();",
    "}",
    "",
    "run().catch((err: unknown) => {",
    "  console.error(err);",
    "  process.exit(1);",
    "});",
    "",
  ].join("\n");
}
