/**
 * Temporal serializer tests.
 */

import { describe, expect, it } from "vitest";
import { temporalSerializer } from "./serializer";
import { DECLARABLE_MARKER } from "@intentius/chant/declarable";

// ── Test helpers ───────────────────────────────────────────────────

function makeEntity(
  entityType: string,
  props: Record<string, unknown>,
): Record<string, unknown> {
  return {
    [DECLARABLE_MARKER]: true,
    entityType,
    lexicon: "temporal",
    kind: "resource",
    props,
    attributes: {},
  };
}

function makeServer(props: Record<string, unknown> = {}): [string, Record<string, unknown>] {
  return ["server", makeEntity("Temporal::Server", props)];
}

function makeNamespace(name: string, props: Record<string, unknown> = {}): [string, Record<string, unknown>] {
  return [name, makeEntity("Temporal::Namespace", { name, ...props })];
}

function makeSearchAttr(name: string, props: Record<string, unknown> = {}): [string, Record<string, unknown>] {
  return [name, makeEntity("Temporal::SearchAttribute", { name, type: "Text", ...props })];
}

function makeSchedule(name: string, props: Record<string, unknown> = {}): [string, Record<string, unknown>] {
  return [name, makeEntity("Temporal::Schedule", {
    scheduleId: name,
    spec: { intervals: [{ every: "1d" }] },
    action: { workflowType: "testWorkflow", taskQueue: "test-queue" },
    ...props,
  })];
}

// ── Tests ─────────────────────────────────────────────────────────

describe("temporal serializer", () => {
  it("has the correct name", () => {
    expect(temporalSerializer.name).toBe("temporal");
  });

  it("has rulePrefix TMP", () => {
    expect(temporalSerializer.rulePrefix).toBe("TMP");
  });

  it("serializes empty map to a string with header comment", () => {
    const result = temporalSerializer.serialize(new Map());
    expect(typeof result).toBe("string");
    expect(result as string).toContain("Generated by chant");
  });

  // ── TemporalServer ─────────────────────────────────────────────

  it("serializes TemporalServer dev mode to docker-compose with start-dev command", () => {
    const entities = new Map([makeServer({ mode: "dev" })]);
    const result = temporalSerializer.serialize(entities) as string;
    expect(typeof result).toBe("string");
    expect(result).toContain("temporal server start-dev");
    expect(result).toContain("temporalio/admin-tools");
    expect(result).toContain("7233");
    expect(result).toContain("8080");
  });

  it("uses default mode 'dev' when mode is not specified", () => {
    const entities = new Map([makeServer()]);
    const result = temporalSerializer.serialize(entities) as string;
    expect(result).toContain("temporal server start-dev");
  });

  it("serializes TemporalServer full mode with auto-setup + postgresql + UI", () => {
    const entities = new Map([makeServer({ mode: "full" })]);
    const result = temporalSerializer.serialize(entities) as string;
    expect(typeof result).toBe("string");
    expect(result).toContain("temporalio/auto-setup");
    expect(result).toContain("postgresql");
    expect(result).toContain("temporal-ui");
    expect(result).toContain("POSTGRES_USER=temporal");
    expect(result).not.toContain("temporal server start-dev");
  });

  it("embeds custom version in docker-compose image tag", () => {
    const entities = new Map([makeServer({ version: "1.25.0", mode: "dev" })]);
    const result = temporalSerializer.serialize(entities) as string;
    expect(result).toContain("1.25.0");
  });

  it("returns plain string (not SerializerResult) when only TemporalServer present", () => {
    const entities = new Map([makeServer()]);
    const result = temporalSerializer.serialize(entities);
    expect(typeof result).toBe("string");
  });

  // ── TemporalServer + Helm values ──────────────────────────────

  it("includes helm-values.yaml in files when server + namespace present", () => {
    const entities = new Map([
      makeServer({ version: "1.26.2" }),
      makeNamespace("default"),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(typeof result).toBe("object");
    expect(result.files["temporal-helm-values.yaml"]).toBeDefined();
    expect(result.files["temporal-helm-values.yaml"]).toContain("temporalio/server");
    expect(result.files["temporal-helm-values.yaml"]).toContain("1.26.2");
  });

  it("includes helm chart comment when helmChartVersion is set", () => {
    const entities = new Map([
      makeServer({ helmChartVersion: "0.42.0" }),
      makeNamespace("default"),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-helm-values.yaml"]).toContain("0.42.0");
  });

  // ── TemporalNamespace ─────────────────────────────────────────

  it("serializes TemporalNamespace to temporal-setup.sh with namespace create command", () => {
    const entities = new Map([makeNamespace("prod", { retention: "30d", description: "Production" })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(typeof result).toBe("object");
    const sh = result.files["temporal-setup.sh"];
    expect(sh).toBeDefined();
    expect(sh).toContain("temporal operator namespace create");
    expect(sh).toContain("--namespace \"prod\"");
    expect(sh).toContain("--retention \"30d\"");
    expect(sh).toContain("--description \"Production\"");
  });

  it("emits --global-namespace flag when isGlobalNamespace is true", () => {
    const entities = new Map([makeNamespace("global-ns", { isGlobalNamespace: true })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-setup.sh"]).toContain("--global-namespace");
  });

  it("uses default retention of 7d when not specified", () => {
    const entities = new Map([makeNamespace("ns")]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-setup.sh"]).toContain('"7d"');
  });

  // ── SearchAttribute ────────────────────────────────────────────

  it("serializes SearchAttribute to setup.sh with search-attribute create command", () => {
    const entities = new Map([makeSearchAttr("GcpProject", { type: "Text" })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    const sh = result.files["temporal-setup.sh"];
    expect(sh).toContain("temporal operator search-attribute create");
    expect(sh).toContain('--name "GcpProject"');
    expect(sh).toContain("--type Text");
  });

  it("includes --namespace flag when namespace is specified on SearchAttribute", () => {
    const entities = new Map([makeSearchAttr("Env", { type: "Keyword", namespace: "prod" })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-setup.sh"]).toContain('--namespace "prod"');
  });

  it("omits --namespace flag when namespace is not specified", () => {
    const entities = new Map([makeSearchAttr("Env", { type: "Keyword" })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-setup.sh"]).not.toContain("--namespace");
  });

  it("emits all search attributes in setup.sh", () => {
    const entities = new Map([
      makeSearchAttr("GcpProject", { type: "Text" }),
      makeSearchAttr("CrdbDomain", { type: "Keyword" }),
      makeSearchAttr("DeployPhase", { type: "Int" }),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    const sh = result.files["temporal-setup.sh"];
    expect(sh).toContain('"GcpProject"');
    expect(sh).toContain('"CrdbDomain"');
    expect(sh).toContain('"DeployPhase"');
  });

  it("combines namespaces and search attributes in a single temporal-setup.sh", () => {
    const entities = new Map([
      makeNamespace("deploy-ns"),
      makeSearchAttr("GcpProject", { type: "Text", namespace: "deploy-ns" }),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    const sh = result.files["temporal-setup.sh"];
    // Both namespace create and search-attribute create appear in one file
    expect(sh).toContain("temporal operator namespace create");
    expect(sh).toContain("temporal operator search-attribute create");
    // Namespaces before search attributes
    expect(sh.indexOf("namespace create")).toBeLessThan(sh.indexOf("search-attribute create"));
  });

  // ── TemporalSchedule ───────────────────────────────────────────

  it("serializes TemporalSchedule to schedules/<id>.ts with SDK schedule.create call", () => {
    const entities = new Map([makeSchedule("daily-backup")]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    const ts = result.files["schedules/daily-backup.ts"];
    expect(ts).toBeDefined();
    expect(ts).toContain("client.schedule.create");
    expect(ts).toContain('"daily-backup"');
  });

  it("embeds workflowType and taskQueue in schedule code", () => {
    const entities = new Map([makeSchedule("my-sched", {
      action: { workflowType: "myWorkflow", taskQueue: "my-queue" },
    })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    const ts = result.files["schedules/my-sched.ts"];
    expect(ts).toContain('"myWorkflow"');
    expect(ts).toContain('"my-queue"');
  });

  it("generates separate schedule files for each TemporalSchedule entity", () => {
    const entities = new Map([
      makeSchedule("schedule-a"),
      makeSchedule("schedule-b"),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["schedules/schedule-a.ts"]).toBeDefined();
    expect(result.files["schedules/schedule-b.ts"]).toBeDefined();
  });

  it("uses scheduleId from props as the file key", () => {
    const entities = new Map([
      ["myEntity", makeEntity("Temporal::Schedule", {
        scheduleId: "custom-id",
        spec: { intervals: [{ every: "1h" }] },
        action: { workflowType: "w", taskQueue: "q" },
      })],
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["schedules/custom-id.ts"]).toBeDefined();
  });

  it("includes overlap policy in schedule code when specified", () => {
    const entities = new Map([makeSchedule("with-policy", {
      policies: { overlap: "BufferOne" },
    })]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["schedules/with-policy.ts"]).toContain("BufferOne");
  });

  it("emits action.retry from workflowRetryPolicy, including nonRetryableErrorTypes", () => {
    const entities = new Map([makeSchedule("with-retry", {
      action: {
        workflowType: "w", taskQueue: "q",
        workflowRetryPolicy: {
          initialInterval: "10s",
          backoffCoefficient: 2,
          maximumAttempts: 5,
          maximumInterval: "5m",
          nonRetryableErrorTypes: ["ValidationError"],
        },
      },
    })]);
    const ts = (temporalSerializer.serialize(entities) as { files: Record<string, string> }).files["schedules/with-retry.ts"];
    expect(ts).toContain("retry:");
    expect(ts).toContain('"initialInterval": "10s"');
    expect(ts).toContain('"maximumAttempts": 5');
    expect(ts).toContain('"nonRetryableErrorTypes"');
    expect(ts).toContain('"ValidationError"');
  });

  it("omits action.retry when no workflowRetryPolicy is set", () => {
    const ts = (temporalSerializer.serialize(new Map([makeSchedule("no-retry")])) as { files: Record<string, string> }).files["schedules/no-retry.ts"];
    expect(ts).not.toContain("retry:");
  });

  it("emits action timeouts, memo, and searchAttributes when set", () => {
    const entities = new Map([makeSchedule("with-action-opts", {
      action: {
        workflowType: "w", taskQueue: "q",
        workflowExecutionTimeout: "1h",
        workflowRunTimeout: "30m",
        memo: { owner: "platform" },
        searchAttributes: { Env: "prod" },
      },
    })]);
    const ts = (temporalSerializer.serialize(entities) as { files: Record<string, string> }).files["schedules/with-action-opts.ts"];
    expect(ts).toContain('workflowExecutionTimeout: "1h"');
    expect(ts).toContain('workflowRunTimeout: "30m"');
    expect(ts).toContain("memo:");
    expect(ts).toContain('"owner": "platform"');
    expect(ts).toContain("searchAttributes:");
    expect(ts).toContain('"Env": "prod"');
  });

  it("omits action timeouts, memo, and searchAttributes when unset", () => {
    const ts = (temporalSerializer.serialize(new Map([makeSchedule("bare-action")])) as { files: Record<string, string> }).files["schedules/bare-action.ts"];
    expect(ts).not.toContain("workflowExecutionTimeout:");
    expect(ts).not.toContain("workflowRunTimeout:");
    expect(ts).not.toContain("memo:");
    expect(ts).not.toContain("searchAttributes:");
  });

  // ── Mixed entities ─────────────────────────────────────────────

  it("returns SerializerResult with all keys for mixed entities", () => {
    const entities = new Map([
      makeServer(),
      makeNamespace("default"),
      makeSearchAttr("Project", { type: "Keyword" }),
      makeSchedule("weekly"),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(typeof result).toBe("object");
    expect(result.primary).toContain("temporal server start-dev");
    expect(result.files["temporal-helm-values.yaml"]).toBeDefined();
    expect(result.files["temporal-setup.sh"]).toBeDefined();
    expect(result.files["schedules/weekly.ts"]).toBeDefined();
  });

  it("primary contains docker-compose content even in mixed mode", () => {
    const entities = new Map([
      makeServer({ mode: "full" }),
      makeNamespace("default"),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.primary).toContain("temporalio/auto-setup");
  });

  it("setup.sh uses TEMPORAL_ADDRESS env var", () => {
    const entities = new Map([makeNamespace("ns")]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-setup.sh"]).toContain("TEMPORAL_ADDRESS");
    expect(result.files["temporal-setup.sh"]).toContain("localhost:7233");
  });

  it("setup.sh has set -euo pipefail", () => {
    const entities = new Map([makeNamespace("ns")]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["temporal-setup.sh"]).toContain("set -euo pipefail");
  });

  // ── Temporal::Op ──────────────────────────────────────────────────

  function makeOp(name: string, phases: unknown[] = []): [string, Record<string, unknown>] {
    return [name, makeEntity("Temporal::Op", { name, overview: `${name} op`, phases })];
  }

  it("includes ops/<name>/workflow.ts when an Op entity is present", () => {
    const entities = new Map([makeOp("alb-deploy")]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(typeof result).toBe("object");
    expect(result.files["ops/alb-deploy/workflow.ts"]).toBeDefined();
  });

  it("includes ops/<name>/activities.ts and worker.ts for each Op", () => {
    const entities = new Map([makeOp("my-op")]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["ops/my-op/activities.ts"]).toBeDefined();
    expect(result.files["ops/my-op/worker.ts"]).toBeDefined();
  });

  it("still returns SerializerResult (not plain string) when only Op entities present", () => {
    const entities = new Map([makeOp("op")]);
    const result = temporalSerializer.serialize(entities);
    expect(typeof result).toBe("object");
  });

  it("combines Op files with schedule and namespace files in mixed entities", () => {
    const entities = new Map([
      makeServer(),
      makeNamespace("default"),
      makeSchedule("weekly"),
      makeOp("deploy-op"),
    ]);
    const result = temporalSerializer.serialize(entities) as { primary: string; files: Record<string, string> };
    expect(result.files["ops/deploy-op/workflow.ts"]).toBeDefined();
    expect(result.files["temporal-setup.sh"]).toBeDefined();
    expect(result.files["schedules/weekly.ts"]).toBeDefined();
  });
});
