/**
 * Temporal serializer.
 *
 * Routes entities by entityType:
 *   Temporal::Server        → docker-compose.yml (primary) + temporal-helm-values.yaml (file)
 *   Temporal::Namespace     → temporal-setup.sh (file)
 *   Temporal::SearchAttribute → temporal-setup.sh (file, appended after namespaces)
 *   Temporal::Schedule      → schedules/<scheduleId>.ts (file per schedule)
 *
 * Returns a plain string when only TemporalServer entities are present.
 * Returns SerializerResult for any other combination.
 */

import type { Declarable } from "@intentius/chant/declarable";
import type { Serializer, SerializerResult } from "@intentius/chant/serializer";
import type { TemporalServerProps, TemporalNamespaceProps, SearchAttributeProps, TemporalScheduleProps } from "./resources";
import { serializeOps } from "./op/serializer";

// ── Helpers ─────────────────────────────────────────────────────────

function getProps(entity: Declarable): Record<string, unknown> {
  if ("props" in entity && typeof entity.props === "object" && entity.props !== null) {
    return entity.props as Record<string, unknown>;
  }
  return {};
}

function entityType(entity: Declarable): string {
  return (entity as Record<string, unknown>).entityType as string;
}

// ── Docker Compose ───────────────────────────────────────────────────

const HEADER = "# Generated by chant — do not edit directly.\n# Source of truth: the chant TypeScript project.\n";

function serializeDockerCompose(servers: Map<string, Declarable>): string {
  const lines: string[] = [HEADER];

  if (servers.size === 0) {
    lines.push("# No TemporalServer resources defined.");
    return lines.join("\n") + "\n";
  }

  // Use the first server entity (a project should have exactly one)
  const [, serverEntity] = [...servers.entries()][0];
  const props = getProps(serverEntity) as TemporalServerProps;
  const version = props.version ?? "1.26.2";
  const mode = props.mode ?? "dev";
  const port = props.port ?? 7233;
  const uiPort = props.uiPort ?? 8080;
  const postgresVersion = props.postgresVersion ?? "16-alpine";

  lines.push("services:");

  if (mode === "dev") {
    lines.push(`  temporal:`);
    lines.push(`    image: temporalio/admin-tools:${version}`);
    lines.push(`    command: temporal server start-dev --namespace default --ui-port ${uiPort}`);
    lines.push(`    ports:`);
    lines.push(`      - "${port}:${port}"`);
    lines.push(`      - "${uiPort}:${uiPort}"`);
  } else {
    // full mode
    lines.push(`  temporal:`);
    lines.push(`    image: temporalio/auto-setup:${version}`);
    lines.push(`    ports:`);
    lines.push(`      - "${port}:7233"`);
    lines.push(`    environment:`);
    lines.push(`      - DB=postgresql`);
    lines.push(`      - DB_PORT=5432`);
    lines.push(`      - POSTGRES_USER=temporal`);
    lines.push(`      - POSTGRES_PWD=temporal`);
    lines.push(`      - POSTGRES_SEEDS=postgresql`);
    lines.push(`    depends_on:`);
    lines.push(`      - postgresql`);
    lines.push(`  temporal-ui:`);
    lines.push(`    image: temporalio/ui:${version}`);
    lines.push(`    environment:`);
    lines.push(`      - TEMPORAL_ADDRESS=temporal:7233`);
    lines.push(`      - TEMPORAL_CORS_ORIGINS=http://localhost:3000`);
    lines.push(`    ports:`);
    lines.push(`      - "${uiPort}:8080"`);
    lines.push(`  postgresql:`);
    lines.push(`    image: postgres:${postgresVersion}`);
    lines.push(`    environment:`);
    lines.push(`      - POSTGRES_USER=temporal`);
    lines.push(`      - POSTGRES_PASSWORD=temporal`);
    lines.push(`    volumes:`);
    lines.push(`      - temporal-db:/var/lib/postgresql/data`);
    lines.push(`volumes:`);
    lines.push(`  temporal-db: {}`);
  }

  return lines.join("\n") + "\n";
}

// ── Helm Values ──────────────────────────────────────────────────────

function serializeHelmValues(servers: Map<string, Declarable>): string {
  if (servers.size === 0) return "";

  const [, serverEntity] = [...servers.entries()][0];
  const props = getProps(serverEntity) as TemporalServerProps;
  const version = props.version ?? "1.26.2";
  const port = props.port ?? 7233;
  const chartVersion = props.helmChartVersion;

  const lines: string[] = [
    "# Generated by chant — do not edit directly.",
    "# Apply: helm install temporal temporal/temporal -f temporal-helm-values.yaml",
    "# Helm charts: https://github.com/temporalio/helm-charts",
  ];

  if (chartVersion) {
    lines.push(`# Chart version: ${chartVersion}`);
  }

  lines.push(
    "server:",
    "  replicaCount: 1",
    "  image:",
    "    repository: temporalio/server",
    `    tag: "${version}"`,
    "frontend:",
    "  replicaCount: 1",
    "  service:",
    `    port: ${port}`,
    "web:",
    "  enabled: true",
  );

  return lines.join("\n") + "\n";
}

// ── Setup Script ─────────────────────────────────────────────────────

function serializeSetupScript(
  namespaces: Map<string, Declarable>,
  searchAttrs: Map<string, Declarable>,
): string {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# Generated by chant — do not edit directly.",
    "# Run once after the Temporal server is ready.",
    "set -euo pipefail",
    "",
    'TEMPORAL_ADDRESS="${TEMPORAL_ADDRESS:-localhost:7233}"',
    "",
  ];

  if (namespaces.size > 0) {
    lines.push("# ── Namespaces ────────────────────────────────────────────────────────");
    lines.push("");
    for (const [, entity] of namespaces) {
      const props = getProps(entity) as TemporalNamespaceProps;
      const parts: string[] = [
        `temporal operator namespace create \\`,
        `  --address "\${TEMPORAL_ADDRESS}" \\`,
        `  --namespace "${props.name}" \\`,
        `  --retention "${props.retention ?? "7d"}"`,
      ];
      if (props.description) {
        // replace last line — remove trailing backslash, add it back with description
        parts[parts.length - 1] += " \\";
        parts.push(`  --description "${props.description}"`);
      }
      if (props.isGlobalNamespace) {
        parts[parts.length - 1] += " \\";
        parts.push(`  --global-namespace`);
      }
      lines.push(...parts);
      lines.push("");
    }
  }

  if (searchAttrs.size > 0) {
    lines.push("# ── Search Attributes ─────────────────────────────────────────────────");
    lines.push("");
    for (const [, entity] of searchAttrs) {
      const props = getProps(entity) as SearchAttributeProps;
      const parts: string[] = [
        `temporal operator search-attribute create \\`,
        `  --address "\${TEMPORAL_ADDRESS}" \\`,
      ];
      if (props.namespace) {
        parts.push(`  --namespace "${props.namespace}" \\`);
      }
      parts.push(
        `  --name "${props.name}" \\`,
        `  --type ${props.type}`,
      );
      lines.push(...parts);
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}

// ── Schedule Code ────────────────────────────────────────────────────

function serializeSchedule(scheduleId: string, props: TemporalScheduleProps): string {
  const lines: string[] = [
    `// Generated by chant — do not edit directly.`,
    `// Run: npx tsx schedules/${scheduleId}.ts`,
    `import { Client, Connection } from "@temporalio/client";`,
    ``,
    `async function createSchedule(): Promise<void> {`,
    `  const connection = await Connection.connect({`,
    `    address: process.env.TEMPORAL_ADDRESS ?? "localhost:7233",`,
    `  });`,
    `  const client = new Client({`,
    `    connection,`,
    `    namespace: process.env.TEMPORAL_NAMESPACE ?? "${props.namespace ?? "default"}",`,
    `  });`,
    ``,
    `  await client.schedule.create({`,
    `    scheduleId: ${JSON.stringify(props.scheduleId)},`,
    `    spec: ${JSON.stringify(props.spec, null, 6).replace(/^/gm, "    ").trimStart()},`,
    `    action: {`,
    `      type: "startWorkflow",`,
    `      workflowType: ${JSON.stringify(props.action.workflowType)},`,
    `      taskQueue: ${JSON.stringify(props.action.taskQueue)},`,
    `      args: ${JSON.stringify(props.action.args ?? [])},`,
    `    },`,
  ];

  if (props.policies) {
    lines.push(`    policies: ${JSON.stringify(props.policies, null, 6).replace(/^/gm, "    ").trimStart()},`);
  }

  if (props.state) {
    lines.push(`    state: ${JSON.stringify(props.state, null, 6).replace(/^/gm, "    ").trimStart()},`);
  }

  lines.push(
    `  });`,
    ``,
    `  console.log("Schedule created: ${scheduleId}");`,
    `  await connection.close();`,
    `}`,
    ``,
    `createSchedule().catch((err: unknown) => {`,
    `  console.error(err);`,
    `  process.exit(1);`,
    `});`,
    ``,
  );

  return lines.join("\n");
}

// ── Serializer ───────────────────────────────────────────────────────

export const temporalSerializer: Serializer = {
  name: "temporal",
  rulePrefix: "TMP",

  serialize(
    entities: Map<string, Declarable>,
    _outputs?: unknown,
  ): string | SerializerResult {
    const servers = new Map<string, Declarable>();
    const namespaces = new Map<string, Declarable>();
    const searchAttrs = new Map<string, Declarable>();
    const schedules = new Map<string, Declarable>();
    const ops = new Map<string, Declarable>();

    for (const [name, entity] of entities) {
      const et = entityType(entity);
      if (et === "Temporal::Server") servers.set(name, entity);
      else if (et === "Temporal::Namespace") namespaces.set(name, entity);
      else if (et === "Temporal::SearchAttribute") searchAttrs.set(name, entity);
      else if (et === "Temporal::Schedule") schedules.set(name, entity);
      else if (et === "Temporal::Op") ops.set(name, entity);
    }

    const primary = serializeDockerCompose(servers);

    // Only-server case with no Ops: no extra files needed beyond docker-compose → return string
    if (
      namespaces.size === 0 &&
      searchAttrs.size === 0 &&
      schedules.size === 0 &&
      ops.size === 0
    ) {
      return primary;
    }

    const files: Record<string, string> = {};

    if (servers.size > 0) {
      files["temporal-helm-values.yaml"] = serializeHelmValues(servers);
    }

    if (namespaces.size > 0 || searchAttrs.size > 0) {
      files["temporal-setup.sh"] = serializeSetupScript(namespaces, searchAttrs);
    }

    for (const [name, entity] of schedules) {
      const props = getProps(entity) as TemporalScheduleProps;
      const scheduleId = props.scheduleId ?? name;
      files[`schedules/${scheduleId}.ts`] = serializeSchedule(scheduleId, props);
    }

    if (ops.size > 0) {
      Object.assign(files, serializeOps(ops));
    }

    return { primary, files };
  },
};
