import { FargateService, Ref } from "@intentius/chant-lexicon-aws";
import {
  clusterArn,
  listenerArn,
  albSgId,
  executionRoleArn,
  vpcId,
  privateSubnet1,
  privateSubnet2,
  efsId,
  accessPointId,
  solrImage,
  solrCollection,
} from "./params";

export const solr = FargateService({
  clusterArn: Ref(clusterArn),
  listenerArn: Ref(listenerArn),
  albSecurityGroupId: Ref(albSgId),
  executionRoleArn: Ref(executionRoleArn),
  vpcId: Ref(vpcId),
  privateSubnetIds: [Ref(privateSubnet1), Ref(privateSubnet2)],
  image: Ref(solrImage),
  containerPort: 8983,
  cpu: "1024",
  memory: "2048",
  desiredCount: 1,
  priority: 100,
  pathPatterns: ["/solr", "/solr/*"],
  healthCheckPath: "/solr/",
  environment: { SOLR_HEAP: "1g" },
  command: ["solr-precreate", Ref(solrCollection)],
  efsMounts: [{ fileSystemId: Ref(efsId), accessPointId: Ref(accessPointId), containerPath: "/var/solr" }],
  autoscaling: { minCapacity: 1, maxCapacity: 6, cpuTarget: 60 },
});
