// Generated by scripts/generate-composite-catalogs.ts (#2662) from this
// lexicon's composite exports. Do not edit by hand: run
// `npm run generate:composite-catalogs`. catalog.test.ts holds it to the exports.
import type { CompositeEntry } from "@intentius/chant/lexicon";

export const compositeCatalog: CompositeEntry[] = [
  {
    "name": "AgentDashboard",
    "lexicon": "grafana",
    "description": "A dashboard for agents instrumented with GenAI spans.",
    "bundles": [
      "Dashboard"
    ],
    "params": [
      {
        "name": "genAi",
        "type": "GenAiMetrics | { metrics: GenAiMetrics }",
        "required": true,
        "description": "The preset's metrics: `genAiMetrics(options)` with the options the collector was built with, or `genAiComponents(options)`."
      },
      {
        "name": "quantile",
        "type": "number",
        "required": false,
        "description": "The latency quantile per model and per tool (default 0.95)."
      },
      {
        "name": "datasource",
        "type": "DatasourceInput<\"prometheus\">",
        "required": true,
        "description": "The Prometheus the metrics are queried from: a declared `Datasource`, or `{ type: \"prometheus\", uid }` for one declared elsewhere."
      },
      {
        "name": "title",
        "type": "string",
        "required": false
      },
      {
        "name": "uid",
        "type": "string",
        "required": false,
        "description": "The dashboard uid."
      },
      {
        "name": "description",
        "type": "string",
        "required": false
      },
      {
        "name": "tags",
        "type": "string[]",
        "required": false
      },
      {
        "name": "folder",
        "type": "string",
        "required": false,
        "description": "The Grafana folder to provision it into."
      },
      {
        "name": "time",
        "type": "{ from: string; to: string }",
        "required": false,
        "description": "Initial time range."
      },
      {
        "name": "refresh",
        "type": "string",
        "required": false,
        "description": "Auto-refresh interval, e.g. `30s`."
      },
      {
        "name": "links",
        "type": "DashboardLinkInput[]",
        "required": false
      }
    ]
  },
  {
    "name": "RedDashboard",
    "lexicon": "grafana",
    "description": "A RED dashboard (rate, errors, duration) per service, built from a `spanmetrics` connector declaration.",
    "bundles": [
      "Dashboard"
    ],
    "params": [
      {
        "name": "spanMetrics",
        "type": "OTelComponent<\"connector\", \"spanmetrics\", SpanMetricsConnectorConfig> | SpanMetricsNames",
        "required": true,
        "description": "The `spanmetrics` connector the metrics come from, or the names `spanMetricsNames()` returned for it."
      },
      {
        "name": "exporter",
        "type": "OTelComponent<\"exporter\", \"prometheus\", PrometheusExporterConfig> | PrometheusNaming",
        "required": false,
        "description": "The `prometheus` exporter that serves them, when its `namespace` or `add_metric_suffixes` changes the names."
      },
      {
        "name": "quantiles",
        "type": "number[]",
        "required": false,
        "description": "Duration quantiles, one panel each (default p50, p95 and p99)."
      },
      {
        "name": "datasource",
        "type": "DatasourceInput<\"prometheus\">",
        "required": true,
        "description": "The Prometheus the metrics are queried from: a declared `Datasource`, or `{ type: \"prometheus\", uid }` for one declared elsewhere."
      },
      {
        "name": "title",
        "type": "string",
        "required": false
      },
      {
        "name": "uid",
        "type": "string",
        "required": false,
        "description": "The dashboard uid."
      },
      {
        "name": "description",
        "type": "string",
        "required": false
      },
      {
        "name": "tags",
        "type": "string[]",
        "required": false
      },
      {
        "name": "folder",
        "type": "string",
        "required": false,
        "description": "The Grafana folder to provision it into."
      },
      {
        "name": "time",
        "type": "{ from: string; to: string }",
        "required": false,
        "description": "Initial time range."
      },
      {
        "name": "refresh",
        "type": "string",
        "required": false,
        "description": "Auto-refresh interval, e.g. `30s`."
      },
      {
        "name": "links",
        "type": "DashboardLinkInput[]",
        "required": false
      }
    ]
  },
  {
    "name": "SloDashboard",
    "lexicon": "grafana",
    "description": "A dashboard for one SLO: the SLI over its window against the objective, the error budget left, and each burn-rate alert's two windows with the rate it fires...",
    "bundles": [
      "Dashboard"
    ],
    "params": [
      {
        "name": "slo",
        "type": "SloInstance | RuleGroupEntity | SloMetrics",
        "required": true,
        "description": "The `Slo(...)` the dashboard reads, its rule group, or what `sloMetrics()` returned for it."
      },
      {
        "name": "datasource",
        "type": "DatasourceInput<\"prometheus\">",
        "required": true,
        "description": "The Prometheus the metrics are queried from: a declared `Datasource`, or `{ type: \"prometheus\", uid }` for one declared elsewhere."
      },
      {
        "name": "title",
        "type": "string",
        "required": false
      },
      {
        "name": "uid",
        "type": "string",
        "required": false,
        "description": "The dashboard uid."
      },
      {
        "name": "description",
        "type": "string",
        "required": false
      },
      {
        "name": "tags",
        "type": "string[]",
        "required": false
      },
      {
        "name": "folder",
        "type": "string",
        "required": false,
        "description": "The Grafana folder to provision it into."
      },
      {
        "name": "time",
        "type": "{ from: string; to: string }",
        "required": false,
        "description": "Initial time range."
      },
      {
        "name": "refresh",
        "type": "string",
        "required": false,
        "description": "Auto-refresh interval, e.g. `30s`."
      },
      {
        "name": "links",
        "type": "DashboardLinkInput[]",
        "required": false
      }
    ]
  }
];
