// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/azuremonitor.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export interface MonitorQuery {
  /**
   * A unique identifier for the query within the list of targets.
   * In server side expressions, the refId is used as a variable name to identify results.
   * By default, the UI will assign A->Z; however setting meaningful names may be useful.
   */
  refId?: string | null;
  /**
   * If hide is set to true, Grafana will filter out the response(s) associated with this query before returning it to the panel.
   */
  hide?: boolean;
  /**
   * Specify the query flavor
   * TODO make this required and give it a default
   */
  queryType?: string;
  /**
   * Azure subscription containing the resource(s) to be queried.
   * Also used for template variable queries
   */
  subscription?: string;
  /**
   * Subscriptions to be queried via Azure Resource Graph.
   */
  subscriptions?: string[];
  /**
   * Azure Monitor Metrics sub-query properties.
   */
  azureMonitor?: MetricQuery;
  /**
   * Azure Monitor Logs sub-query properties.
   */
  azureLogAnalytics?: LogsQuery;
  /**
   * Azure Resource Graph sub-query properties.
   */
  azureResourceGraph?: ResourceGraphQuery;
  /**
   * Application Insights Traces sub-query properties.
   */
  azureTraces?: TracesQuery;
  /**
   * @deprecated Legacy template variable support.
   */
  grafanaTemplateVariableFn?: GrafanaTemplateVariableQuery;
  /**
   * Resource group used in template variable queries
   */
  resourceGroup?: string;
  /**
   * Namespace used in template variable queries
   */
  namespace?: string;
  /**
   * Resource used in template variable queries
   */
  resource?: string;
  /**
   * Region used in template variable queries
   */
  region?: string;
  /**
   * Custom namespace used in template variable queries
   */
  customNamespace?: string;
  /**
   * For mixed data sources the selected datasource is on the query level.
   * For non mixed scenarios this is undefined.
   * TODO find a better way to do this ^ that's friendly to schema
   * TODO this shouldn't be unknown but DataSourceRef | null
   */
  datasource?: DataSourceRef;
  /**
   * Used only for exemplar queries from Prometheus
   */
  query?: string;
}

export interface MetricQuery {
  /**
   * Array of resource URIs to be queried.
   */
  resources?: MonitorResource[];
  /**
   * metricNamespace is used as the resource type (or resource namespace).
   * It's usually equal to the target metric namespace. e.g. microsoft.storage/storageaccounts
   * Kept the name of the variable as metricNamespace to avoid backward incompatibility issues.
   */
  metricNamespace?: string;
  /**
   * Used as the value for the metricNamespace property when it's different from the resource namespace.
   */
  customNamespace?: string;
  /**
   * The metric to query data for within the specified metricNamespace. e.g. UsedCapacity
   */
  metricName?: string;
  /**
   * The Azure region containing the resource(s).
   */
  region?: string;
  /**
   * The granularity of data points to be queried. Defaults to auto.
   */
  timeGrain?: string;
  /**
   * The aggregation to be used within the query. Defaults to the primaryAggregationType defined by the metric.
   */
  aggregation?: string;
  /**
   * Filters to reduce the set of data returned. Dimensions that can be filtered on are defined by the metric.
   */
  dimensionFilters?: MetricDimension[];
  /**
   * Maximum number of records to return. Defaults to 10.
   */
  top?: string;
  /**
   * Time grains that are supported by the metric.
   */
  allowedTimeGrainsMs?: number[];
  /**
   * Aliases can be set to modify the legend labels. e.g. {{ resourceGroup }}. See docs for more detail.
   */
  alias?: string;
  /**
   * @deprecated
   */
  timeGrainUnit?: string;
  /**
   * @deprecated This property was migrated to dimensionFilters and should only be accessed in the migration
   */
  dimension?: string;
  /**
   * @deprecated This property was migrated to dimensionFilters and should only be accessed in the migration
   */
  dimensionFilter?: string;
  /**
   * @deprecated Use metricNamespace instead
   */
  metricDefinition?: string;
  /**
   * @deprecated Use resourceGroup, resourceName and metricNamespace instead
   */
  resourceUri?: string;
  /**
   * @deprecated Use resources instead
   */
  resourceGroup?: string;
  /**
   * @deprecated Use resources instead
   */
  resourceName?: string;
}

export interface MonitorResource {
  subscription?: string;
  resourceGroup?: string;
  resourceName?: string;
  metricNamespace?: string;
  region?: string;
}

export interface MetricDimension {
  /**
   * Name of Dimension to be filtered on.
   */
  dimension?: string;
  /**
   * String denoting the filter operation. Supports 'eq' - equals,'ne' - not equals, 'sw' - starts with. Note that some dimensions may not support all operators.
   */
  operator?: string;
  /**
   * Values to match with the filter.
   */
  filters?: string[];
  /**
   * @deprecated filter is deprecated in favour of filters to support multiselect.
   */
  filter?: string;
}

/**
 * Azure Monitor Logs sub-query properties
 */
export interface LogsQuery {
  /**
   * KQL query to be executed.
   */
  query?: string;
  /**
   * Specifies the format results should be returned as.
   */
  resultFormat?: ResultFormat;
  /**
   * Array of resource URIs to be queried.
   */
  resources?: string[];
  /**
   * If set to true the dashboard time range will be used as a filter for the query. Otherwise the query time ranges will be used. Defaults to false.
   */
  dashboardTime?: boolean;
  /**
   * If dashboardTime is set to true this value dictates which column the time filter will be applied to. Defaults to the first tables timeSpan column, the first datetime column found, or TimeGenerated
   */
  timeColumn?: string;
  /**
   * If set to true the query will be run as a basic logs query
   */
  basicLogsQuery?: boolean;
  /**
   * Workspace ID. This was removed in Grafana 8, but remains for backwards compat.
   */
  workspace?: string;
  /**
   * @deprecated Use resources instead
   */
  resource?: string;
  /**
   * @deprecated Use dashboardTime instead
   */
  intersectTime?: boolean;
}

export type ResultFormat = "table" | "time_series" | "trace" | "logs";

export interface ResourceGraphQuery {
  /**
   * Azure Resource Graph KQL query to be executed.
   */
  query?: string;
  /**
   * Specifies the format results should be returned as. Defaults to table.
   */
  resultFormat?: string;
}

/**
 * Application Insights Traces sub-query properties
 */
export interface TracesQuery {
  /**
   * Specifies the format results should be returned as.
   */
  resultFormat?: ResultFormat;
  /**
   * Array of resource URIs to be queried.
   */
  resources?: string[];
  /**
   * Operation ID. Used only for Traces queries.
   */
  operationId?: string;
  /**
   * Types of events to filter by.
   */
  traceTypes?: string[];
  /**
   * Filters for property values.
   */
  filters?: TracesFilter[];
  /**
   * KQL query to be executed.
   */
  query?: string;
}

export interface TracesFilter {
  /**
   * Property name, auto-populated based on available traces.
   */
  property: string;
  /**
   * Comparison operator to use. Either equals or not equals.
   */
  operation: string;
  /**
   * Values to filter by.
   */
  filters: string[];
}

export type GrafanaTemplateVariableQuery = AppInsightsMetricNameQuery | AppInsightsGroupByQuery | SubscriptionsQuery | ResourceGroupsQuery | ResourceNamesQuery | MetricNamespaceQuery | MetricDefinitionsQuery | MetricNamesQuery | WorkspacesQuery | UnknownQuery;

export interface AppInsightsMetricNameQuery {
  rawQuery?: string;
  kind: "AppInsightsMetricNameQuery";
}

export interface AppInsightsGroupByQuery {
  rawQuery?: string;
  kind: "AppInsightsGroupByQuery";
  metricName: string;
}

export interface SubscriptionsQuery {
  rawQuery?: string;
  kind: "SubscriptionsQuery";
}

export interface ResourceGroupsQuery {
  rawQuery?: string;
  kind: "ResourceGroupsQuery";
  subscription: string;
}

export interface ResourceNamesQuery {
  rawQuery?: string;
  kind: "ResourceNamesQuery";
  subscription: string;
  resourceGroup: string;
  metricNamespace: string;
}

export interface MetricNamespaceQuery {
  rawQuery?: string;
  kind: "MetricNamespaceQuery";
  subscription: string;
  resourceGroup: string;
  metricNamespace?: string;
  resourceName?: string;
}

/**
 * @deprecated Use MetricNamespaceQuery instead
 */
export interface MetricDefinitionsQuery {
  rawQuery?: string;
  kind: "MetricDefinitionsQuery";
  subscription: string;
  resourceGroup: string;
  metricNamespace?: string;
  resourceName?: string;
}

export interface MetricNamesQuery {
  rawQuery?: string;
  kind: "MetricNamesQuery";
  subscription: string;
  resourceGroup: string;
  resourceName: string;
  metricNamespace: string;
}

export interface WorkspacesQuery {
  rawQuery?: string;
  kind: "WorkspacesQuery";
  subscription: string;
}

export interface UnknownQuery {
  rawQuery?: string;
  kind: "UnknownQuery";
}

/**
 * Defines the supported queryTypes. GrafanaTemplateVariableFn is deprecated
 */
export type QueryType = "Azure Monitor" | "Azure Log Analytics" | "Azure Resource Graph" | "Azure Traces" | "Azure Subscriptions" | "Azure Resource Groups" | "Azure Namespaces" | "Azure Resource Names" | "Azure Metric Names" | "Azure Workspaces" | "Azure Regions" | "Grafana Template Variable Function" | "traceql" | "Azure Custom Namespaces" | "Azure Custom Metric Names";

export type GrafanaTemplateVariableQueryType = "AppInsightsMetricNameQuery" | "AppInsightsGroupByQuery" | "SubscriptionsQuery" | "ResourceGroupsQuery" | "ResourceNamesQuery" | "MetricNamespaceQuery" | "MetricNamesQuery" | "WorkspacesQuery" | "UnknownQuery";

export interface BaseGrafanaTemplateVariableQuery {
  rawQuery?: string;
}

export interface DataSourceRef {
  /**
   * The plugin type-id
   */
  type?: string;
  /**
   * Specific datasource instance
   */
  uid?: string;
}
