// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/bigquery.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

/**
 * Manually converted from https://github.com/grafana/google-bigquery-datasource/blob/18680e42ba557791d109c7c540c2c3f2647592f0/src/types.ts#L75
 */
export interface Dataquery {
  dataset?: string;
  table?: string;
  project?: string;
  format: QueryFormat;
  rawQuery?: boolean;
  rawSql: string;
  location?: string;
  partitioned?: boolean;
  partitionedField?: string;
  convertToUTC?: boolean;
  sharded?: boolean;
  queryPriority?: QueryPriority;
  timeShift?: string;
  editorMode?: EditorMode;
  sql?: SQLExpression;
  /**
   * A unique identifier for the query within the list of targets.
   * In server side expressions, the refId is used as a variable name to identify results.
   * By default, the UI will assign A->Z; however setting meaningful names may be useful.
   */
  refId?: string | null;
  /**
   * If hide is set to true, Grafana will filter out the response(s) associated with this query before returning it to the panel.
   */
  hide?: boolean;
  /**
   * Specify the query flavor
   * TODO make this required and give it a default
   */
  queryType?: string;
  /**
   * For mixed data sources the selected datasource is on the query level.
   * For non mixed scenarios this is undefined.
   * TODO find a better way to do this ^ that's friendly to schema
   * TODO this shouldn't be unknown but DataSourceRef | null
   */
  datasource?: DataSourceRef;
}

export type QueryFormat = 0 | 1;

export type QueryPriority = "INTERACTIVE" | "BATCH";

export type EditorMode = "code" | "builder";

export interface SQLExpression {
  columns?: QueryEditorFunctionExpression[];
  from?: string;
  /**
   * whereJsonTree?: _
   */
  whereString?: string;
  groupBy?: QueryEditorGroupByExpression[];
  orderBy?: QueryEditorPropertyExpression;
  orderByDirection?: OrderByDirection;
  limit?: number;
  offset?: number;
}

export interface QueryEditorFunctionExpression {
  type: QueryEditorExpressionType;
  name?: string;
  parameters?: QueryEditorFunctionParameterExpression[];
}

export type QueryEditorExpressionType = "property" | "operator" | "or" | "and" | "groupBy" | "function" | "functionParameter";

export interface QueryEditorFunctionParameterExpression {
  type: QueryEditorExpressionType;
  name?: string;
}

export interface QueryEditorGroupByExpression {
  type: QueryEditorExpressionType;
  property: QueryEditorProperty;
}

export interface QueryEditorProperty {
  type: QueryEditorPropertyType;
  name?: string;
}

export type QueryEditorPropertyType = "string";

export interface QueryEditorPropertyExpression {
  type: QueryEditorExpressionType;
  property: QueryEditorProperty;
}

export type OrderByDirection = "ASC" | "DESC";

export interface DataSourceRef {
  /**
   * The plugin type-id
   */
  type?: string;
  /**
   * Specific datasource instance
   */
  uid?: string;
}
