// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/candlestick.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export type VizDisplayMode = "candles+volume" | "candles" | "volume";

export type CandleStyle = "candles" | "ohlcbars";

export type ColorStrategy = "open-close" | "close-close";

export interface CandlestickFieldMap {
  /**
   * Corresponds to the starting value of the given period
   */
  open?: string;
  /**
   * Corresponds to the highest value of the given period
   */
  high?: string;
  /**
   * Corresponds to the lowest value of the given period
   */
  low?: string;
  /**
   * Corresponds to the final (end) value of the given period
   */
  close?: string;
  /**
   * Corresponds to the sample count in the given period. (e.g. number of trades)
   */
  volume?: string;
}

export interface CandlestickColors {
  up: string;
  down: string;
  flat: string;
}

export interface Options {
  /**
   * Sets which dimensions are used for the visualization
   */
  mode: VizDisplayMode;
  /**
   * Sets the style of the candlesticks
   */
  candleStyle: CandleStyle;
  /**
   * Sets the color strategy for the candlesticks
   */
  colorStrategy: ColorStrategy;
  /**
   * Map fields to appropriate dimension
   */
  fields: CandlestickFieldMap;
  /**
   * Set which colors are used when the price movement is up or down
   */
  colors: CandlestickColors;
  legend: VizLegendOptions;
  tooltip: VizTooltipOptions;
  /**
   * When enabled, all fields will be sent to the graph
   */
  includeAllFields?: boolean;
  annotations?: VizAnnotations;
}

export type FieldConfig = GraphFieldConfig;

/**
 * TODO docs
 */
export interface VizLegendOptions {
  displayMode: LegendDisplayMode;
  placement: LegendPlacement;
  showLegend: boolean;
  asTable?: boolean;
  isVisible?: boolean;
  sortBy?: string;
  sortDesc?: boolean;
  width?: number;
  calcs: string[];
}

/**
 * TODO docs
 */
export interface VizTooltipOptions {
  mode: TooltipDisplayMode;
  sort: SortOrder;
  maxWidth?: number;
  maxHeight?: number;
  hideZeros?: boolean;
}

/**
 * TODO docs
 */
export interface GraphFieldConfig {
  drawStyle?: GraphDrawStyle;
  gradientMode?: GraphGradientMode;
  thresholdsStyle?: GraphThresholdsStyleConfig;
  transform?: GraphTransform;
  lineColor?: string;
  lineWidth?: number;
  lineInterpolation?: LineInterpolation;
  lineStyle?: LineStyle;
  fillColor?: string;
  fillOpacity?: number;
  showPoints?: VisibilityMode;
  pointSize?: number;
  pointColor?: string;
  axisPlacement?: AxisPlacement;
  axisColorMode?: AxisColorMode;
  axisLabel?: string;
  axisWidth?: number;
  axisSoftMin?: number;
  axisSoftMax?: number;
  axisGridShow?: boolean;
  scaleDistribution?: ScaleDistributionConfig;
  axisCenteredZero?: boolean;
  barAlignment?: BarAlignment;
  barWidthFactor?: number;
  stacking?: StackingConfig;
  hideFrom?: HideSeriesConfig;
  insertNulls?: boolean | number;
  /**
   * Indicate if null values should be treated as gaps or connected.
   * When the value is a number, it represents the maximum delta in the
   * X axis that should be considered connected.  For timeseries, this is milliseconds
   */
  spanNulls?: boolean | number;
  fillBelowTo?: string;
  pointSymbol?: string;
  axisBorderShow?: boolean;
  barMaxWidth?: number;
  /**
   * Show point values on the graph.
   */
  showValues?: boolean;
}

/**
 * TODO docs
 * Note: "hidden" needs to remain as an option for plugins compatibility
 */
export type LegendDisplayMode = "list" | "table" | "hidden";

/**
 * TODO docs
 */
export type LegendPlacement = "bottom" | "right";

/**
 * TODO docs
 */
export type TooltipDisplayMode = "single" | "multi" | "none";

/**
 * TODO docs
 */
export type SortOrder = "asc" | "desc" | "none";

/**
 * TODO docs
 */
export type GraphDrawStyle = "line" | "bars" | "points";

/**
 * TODO docs
 */
export type GraphGradientMode = "none" | "opacity" | "hue" | "scheme";

/**
 * TODO docs
 */
export interface GraphThresholdsStyleConfig {
  mode: GraphThresholdsStyleMode;
}

/**
 * TODO docs
 */
export type GraphTransform = "constant" | "negative-Y";

/**
 * TODO docs
 */
export type LineInterpolation = "linear" | "smooth" | "stepBefore" | "stepAfter";

/**
 * TODO docs
 */
export interface LineStyle {
  fill?: "solid" | "dash" | "dot" | "square" | "accessible";
  dash?: number[];
}

/**
 * TODO docs
 */
export type VisibilityMode = "auto" | "never" | "always";

/**
 * TODO docs
 */
export type AxisPlacement = "auto" | "top" | "right" | "bottom" | "left" | "hidden";

/**
 * TODO docs
 */
export type AxisColorMode = "text" | "series";

/**
 * TODO docs
 */
export interface ScaleDistributionConfig {
  type: ScaleDistribution;
  log?: number;
  linearThreshold?: number;
}

/**
 * TODO docs
 */
export type BarAlignment = -1 | 0 | 1;

/**
 * TODO docs
 */
export interface StackingConfig {
  mode?: StackingMode;
  group?: string;
}

/**
 * TODO docs
 */
export interface HideSeriesConfig {
  tooltip: boolean;
  legend: boolean;
  viz: boolean;
}

/**
 * TODO docs
 */
export type GraphThresholdsStyleMode = "off" | "line" | "dashed" | "area" | "line+area" | "dashed+area" | "series";

/**
 * TODO docs
 */
export type ScaleDistribution = "linear" | "log" | "ordinal" | "symlog";

/**
 * TODO docs
 */
export type StackingMode = "none" | "normal" | "percent";

export interface VizAnnotations {
  /**
   * Breaks out each annotation frame into multiple lanes on the x-axis
   */
  multiLane?: boolean;
  /**
   * Sets whether clustering is enabled. Any value > 0 will enable clustering.
   */
  clustering?: number;
  lines?: {
    width?: number;
  };
  regions?: {
    opacity?: number;
  };
}
