// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/dashboardlist.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export interface Options {
  keepTime: boolean;
  includeVars: boolean;
  showStarred: boolean;
  showRecentlyViewed: boolean;
  showSearch: boolean;
  showHeadings: boolean;
  showFolderNames: boolean;
  maxItems: number;
  query: string;
  tags: string[];
  /**
   * folderId is deprecated, and migrated to folderUid on panel init
   */
  folderId?: number;
  folderUID?: string;
}
