// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/datagrid.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export interface Options {
  selectedSeries: number;
}
