// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/elasticsearch.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export type BucketAggregation = DateHistogram | Histogram | Terms | Filters | GeoHashGrid | Nested;

export interface DateHistogram {
  field?: string;
  id: string;
  type: BucketAggregationType;
  settings?: {
    interval?: string;
    min_doc_count?: string;
    trimEdges?: string;
    offset?: string;
    timeZone?: string;
  };
}

export type BucketAggregationType = "terms" | "filters" | "geohash_grid" | "date_histogram" | "histogram" | "nested";

export interface Histogram {
  field?: string;
  id: string;
  type: BucketAggregationType;
  settings?: {
    interval?: string;
    min_doc_count?: string;
  };
}

export interface Terms {
  field?: string;
  id: string;
  type: BucketAggregationType;
  settings?: {
    order?: TermsOrder;
    size?: string;
    min_doc_count?: string;
    orderBy?: string;
    missing?: string;
  };
}

export type TermsOrder = "desc" | "asc";

export interface Filters {
  id: string;
  type: BucketAggregationType;
  settings?: {
    filters?: Filter[];
  };
}

export interface Filter {
  query: string;
  label: string;
}

export interface GeoHashGrid {
  field?: string;
  id: string;
  type: BucketAggregationType;
  settings?: {
    precision?: string;
  };
}

export interface Nested {
  field?: string;
  id: string;
  type: BucketAggregationType;
  settings?: Record<string, unknown>;
}

export type MetricAggregation = Count | PipelineMetricAggregation | MetricAggregationWithSettings;

export interface Count {
  type: MetricAggregationType;
  id: string;
  hide?: boolean;
}

export type MetricAggregationType = "count" | "avg" | "sum" | "min" | "max" | "extended_stats" | "percentiles" | "cardinality" | "raw_document" | "raw_data" | "logs" | "rate" | "top_metrics" | PipelineMetricAggregationType;

export type PipelineMetricAggregationType = "moving_avg" | "moving_fn" | "derivative" | "serial_diff" | "cumulative_sum" | "bucket_script";

export type PipelineMetricAggregation = MovingAverage | Derivative | CumulativeSum | BucketScript;

/**
 * #MovingAverage's settings are overridden in types.ts
 */
export interface MovingAverage {
  pipelineAgg?: string;
  field?: string;
  type: MetricAggregationType;
  id: string;
  settings?: Record<string, Record<string, unknown>>;
  hide?: boolean;
}

export interface Derivative {
  pipelineAgg?: string;
  field?: string;
  type: MetricAggregationType;
  id: string;
  settings?: {
    unit?: string;
  };
  hide?: boolean;
}

export interface CumulativeSum {
  pipelineAgg?: string;
  field?: string;
  type: MetricAggregationType;
  id: string;
  settings?: {
    format?: string;
  };
  hide?: boolean;
}

export interface BucketScript {
  type: MetricAggregationType;
  pipelineVariables?: PipelineVariable[];
  id: string;
  settings?: {
    script?: InlineScript;
  };
  hide?: boolean;
}

export interface PipelineVariable {
  name: string;
  pipelineAgg: string;
}

export type InlineScript = string | {
  inline?: string;
};

export type MetricAggregationWithSettings = BucketScript | CumulativeSum | Derivative | SerialDiff | RawData | RawDocument | UniqueCount | Percentiles | ExtendedStats | Min | Max | Sum | Average | MovingAverage | MovingFunction | Logs | Rate | TopMetrics;

export interface SerialDiff {
  pipelineAgg?: string;
  field?: string;
  type: MetricAggregationType;
  id: string;
  settings?: {
    lag?: string;
  };
  hide?: boolean;
}

export interface RawData {
  type: MetricAggregationType;
  id: string;
  settings?: {
    size?: string;
  };
  hide?: boolean;
}

export interface RawDocument {
  type: MetricAggregationType;
  id: string;
  settings?: {
    size?: string;
  };
  hide?: boolean;
}

export interface UniqueCount {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    precision_threshold?: string;
    missing?: string;
  };
  hide?: boolean;
}

export interface Percentiles {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    script?: InlineScript;
    missing?: string;
    percents?: string[];
  };
  hide?: boolean;
}

export interface ExtendedStats {
  type: MetricAggregationType;
  settings?: {
    script?: InlineScript;
    missing?: string;
    sigma?: string;
  };
  field?: string;
  id: string;
  meta?: Record<string, unknown>;
  hide?: boolean;
}

export interface Min {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    script?: InlineScript;
    missing?: string;
  };
  hide?: boolean;
}

export interface Max {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    script?: InlineScript;
    missing?: string;
  };
  hide?: boolean;
}

export interface Sum {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    script?: InlineScript;
    missing?: string;
  };
  hide?: boolean;
}

export interface Average {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    script?: InlineScript;
    missing?: string;
  };
  hide?: boolean;
}

export interface MovingFunction {
  pipelineAgg?: string;
  field?: string;
  type: MetricAggregationType;
  id: string;
  settings?: {
    window?: string;
    script?: InlineScript;
    shift?: string;
  };
  hide?: boolean;
}

export interface Logs {
  type: MetricAggregationType;
  id: string;
  settings?: {
    limit?: string;
  };
  hide?: boolean;
}

export interface Rate {
  type: MetricAggregationType;
  field?: string;
  id: string;
  settings?: {
    unit?: string;
    mode?: string;
  };
  hide?: boolean;
}

export interface TopMetrics {
  type: MetricAggregationType;
  id: string;
  settings?: {
    order?: string;
    orderBy?: string;
    metrics?: string[];
  };
  hide?: boolean;
}

export interface BaseBucketAggregation {
  id: string;
  type: BucketAggregationType;
  settings?: Record<string, unknown>;
}

export interface BucketAggregationWithField {
  field?: string;
  id: string;
  type: BucketAggregationType;
  settings?: Record<string, unknown>;
}

export interface DateHistogramSettings {
  interval?: string;
  min_doc_count?: string;
  trimEdges?: string;
  offset?: string;
  timeZone?: string;
}

export interface HistogramSettings {
  interval?: string;
  min_doc_count?: string;
}

export interface TermsSettings {
  order?: TermsOrder;
  size?: string;
  min_doc_count?: string;
  orderBy?: string;
  missing?: string;
}

export interface FiltersSettings {
  filters?: Filter[];
}

export interface GeoHashGridSettings {
  precision?: string;
}

export interface BaseMetricAggregation {
  type: MetricAggregationType;
  id: string;
  hide?: boolean;
}

export interface MetricAggregationWithField {
  field?: string;
  type: MetricAggregationType;
  id: string;
  hide?: boolean;
}

export interface MetricAggregationWithMissingSupport {
  settings?: {
    missing?: string;
  };
  type: MetricAggregationType;
  id: string;
  hide?: boolean;
}

export interface MetricAggregationWithInlineScript {
  settings?: {
    script?: InlineScript;
  };
  type: MetricAggregationType;
  id: string;
  hide?: boolean;
}

export type ExtendedStatMetaType = "avg" | "min" | "max" | "sum" | "count" | "std_deviation" | "std_deviation_bounds_upper" | "std_deviation_bounds_lower";

export interface ExtendedStat {
  label: string;
  value: ExtendedStatMetaType;
}

export interface BasePipelineMetricAggregation {
  pipelineAgg?: string;
  field?: string;
  type: string;
  id: string;
  hide?: boolean;
}

export interface PipelineMetricAggregationWithMultipleBucketPaths {
  pipelineVariables?: PipelineVariable[];
  type: MetricAggregationType;
  id: string;
  hide?: boolean;
}

export type MovingAverageModel = "simple" | "linear" | "ewma" | "holt" | "holt_winters";

export interface MovingAverageModelOption {
  label: string;
  value: MovingAverageModel;
}

export interface BaseMovingAverageModelSettings {
  model: MovingAverageModel;
  window: string;
  predict: string;
}

export interface MovingAverageSimpleModelSettings {
  model: MovingAverageModel;
  window: string;
  predict: string;
}

export interface MovingAverageLinearModelSettings {
  model: MovingAverageModel;
  window: string;
  predict: string;
}

export interface MovingAverageEWMAModelSettings {
  model: MovingAverageModel;
  settings?: {
    alpha?: string;
  };
  window: string;
  minimize: boolean;
  predict: string;
}

export interface MovingAverageHoltModelSettings {
  model: MovingAverageModel;
  settings: {
    alpha?: string;
    beta?: string;
  };
  window: string;
  minimize: boolean;
  predict: string;
}

export interface MovingAverageHoltWintersModelSettings {
  model: MovingAverageModel;
  settings: {
    alpha?: string;
    beta?: string;
    gamma?: string;
    period?: string;
    pad?: boolean;
  };
  window: string;
  minimize: boolean;
  predict: string;
}

export interface Dataquery {
  /**
   * Alias pattern
   */
  alias?: string;
  /**
   * Lucene query
   */
  query?: string;
  /**
   * Name of time field
   */
  timeField?: string;
  /**
   * List of bucket aggregations
   */
  bucketAggs?: BucketAggregation[];
  /**
   * List of metric aggregations
   */
  metrics?: MetricAggregation[];
  /**
   * A unique identifier for the query within the list of targets.
   * In server side expressions, the refId is used as a variable name to identify results.
   * By default, the UI will assign A->Z; however setting meaningful names may be useful.
   */
  refId?: string | null;
  /**
   * If hide is set to true, Grafana will filter out the response(s) associated with this query before returning it to the panel.
   */
  hide?: boolean;
  /**
   * Specify the query flavor
   * TODO make this required and give it a default
   */
  queryType?: string;
  /**
   * For mixed data sources the selected datasource is on the query level.
   * For non mixed scenarios this is undefined.
   * TODO find a better way to do this ^ that's friendly to schema
   * TODO this shouldn't be unknown but DataSourceRef | null
   */
  datasource?: DataSourceRef;
}

export interface DataSourceRef {
  /**
   * The plugin type-id
   */
  type?: string;
  /**
   * Specific datasource instance
   */
  uid?: string;
}
