// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/geomap.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export interface Options {
  view: MapViewConfig;
  controls: ControlsOptions;
  basemap: MapLayerOptions;
  layers: MapLayerOptions[];
  tooltip: TooltipOptions;
}

export interface MapViewConfig {
  id: string;
  lat?: number;
  lon?: number;
  zoom?: number;
  minZoom?: number;
  maxZoom?: number;
  padding?: number;
  allLayers?: boolean;
  lastOnly?: boolean;
  layer?: string;
  shared?: boolean;
  noRepeat?: boolean;
  dashboardVariable?: boolean;
  dashboardVariableName?: string;
}

export interface ControlsOptions {
  /**
   * Zoom (upper left)
   */
  showZoom?: boolean;
  /**
   * let the mouse wheel zoom
   */
  mouseWheelZoom?: boolean;
  /**
   * Lower right
   */
  showAttribution?: boolean;
  /**
   * Scale options
   */
  showScale?: boolean;
  /**
   * Show debug
   */
  showDebug?: boolean;
  /**
   * Show measure
   */
  showMeasure?: boolean;
}

export interface TooltipOptions {
  mode: TooltipMode;
}

export type TooltipMode = "none" | "details";

export type MapCenterID = "zero" | "coords" | "fit";

export interface MapLayerOptions {
  type: string;
  /**
   * configured unique display name
   */
  name: string;
  /**
   * Custom options depending on the type
   */
  config?: Record<string, unknown>;
  /**
   * Common method to define geometry fields
   */
  location?: FrameGeometrySource;
  /**
   * Defines a frame MatcherConfig that may filter data for the given layer
   */
  filterData?: Record<string, unknown>;
  /**
   * Common properties:
   * https://openlayers.org/en/latest/apidoc/module-ol_layer_Base-BaseLayer.html
   * Layer opacity (0-1)
   */
  opacity?: number;
  /**
   * Check tooltip (defaults to true)
   */
  tooltip?: boolean;
}

export interface FrameGeometrySource {
  mode: FrameGeometrySourceMode;
  /**
   * Field mappings
   */
  geohash?: string;
  latitude?: string;
  longitude?: string;
  wkt?: string;
  lookup?: string;
  /**
   * Path to Gazetteer
   */
  gazetteer?: string;
}

export type FrameGeometrySourceMode = "auto" | "geohash" | "coords" | "lookup";
