// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/histogram.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export interface Options {
  /**
   * Bucket count (approx)
   */
  bucketCount?: number;
  /**
   * Size of each bucket
   */
  bucketSize?: number;
  /**
   * Offset buckets by this amount
   */
  bucketOffset?: number;
  legend: VizLegendOptions;
  tooltip: VizTooltipOptions;
  /**
   * Combines multiple series into a single histogram
   */
  combine?: boolean;
}

export interface FieldConfig {
  /**
   * Controls line width of the bars.
   */
  lineWidth?: number;
  /**
   * Controls the fill opacity of the bars.
   */
  fillOpacity?: number;
  axisPlacement?: AxisPlacement;
  axisColorMode?: AxisColorMode;
  axisLabel?: string;
  axisWidth?: number;
  axisSoftMin?: number;
  axisSoftMax?: number;
  axisGridShow?: boolean;
  scaleDistribution?: ScaleDistributionConfig;
  axisCenteredZero?: boolean;
  hideFrom?: HideSeriesConfig;
  stacking?: StackingConfig;
  /**
   * Set the mode of the gradient fill. Fill gradient is based on the line color. To change the color, use the standard color scheme field option.
   * Gradient appearance is influenced by the Fill opacity setting.
   */
  gradientMode?: GraphGradientMode;
  axisBorderShow?: boolean;
}

/**
 * TODO docs
 */
export interface VizLegendOptions {
  displayMode: LegendDisplayMode;
  placement: LegendPlacement;
  showLegend: boolean;
  asTable?: boolean;
  isVisible?: boolean;
  sortBy?: string;
  sortDesc?: boolean;
  width?: number;
  calcs: string[];
}

/**
 * TODO docs
 */
export interface VizTooltipOptions {
  mode: TooltipDisplayMode;
  sort: SortOrder;
  maxWidth?: number;
  maxHeight?: number;
  hideZeros?: boolean;
}

/**
 * TODO docs
 */
export type AxisPlacement = "auto" | "top" | "right" | "bottom" | "left" | "hidden";

/**
 * TODO docs
 */
export type AxisColorMode = "text" | "series";

/**
 * TODO docs
 */
export interface ScaleDistributionConfig {
  type: ScaleDistribution;
  log?: number;
  linearThreshold?: number;
}

/**
 * TODO docs
 */
export interface HideSeriesConfig {
  tooltip: boolean;
  legend: boolean;
  viz: boolean;
}

/**
 * TODO docs
 */
export interface StackingConfig {
  mode?: StackingMode;
  group?: string;
}

/**
 * TODO docs
 */
export type GraphGradientMode = "none" | "opacity" | "hue" | "scheme";

/**
 * TODO docs
 * Note: "hidden" needs to remain as an option for plugins compatibility
 */
export type LegendDisplayMode = "list" | "table" | "hidden";

/**
 * TODO docs
 */
export type LegendPlacement = "bottom" | "right";

/**
 * TODO docs
 */
export type TooltipDisplayMode = "single" | "multi" | "none";

/**
 * TODO docs
 */
export type SortOrder = "asc" | "desc" | "none";

/**
 * TODO docs
 */
export type ScaleDistribution = "linear" | "log" | "ordinal" | "symlog";

/**
 * TODO docs
 */
export type StackingMode = "none" | "normal" | "percent";
