// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/loki.jsonschema.json (see src/pin.ts). DO NOT EDIT.
/* eslint-disable */

export type QueryEditorMode = "code" | "builder";

export type LokiQueryType = "range" | "instant" | "stream";

export type SupportingQueryType = "logsVolume" | "logsSample" | "dataSample" | "infiniteScroll";

export type LokiQueryDirection = "forward" | "backward" | "scan";

export interface Dataquery {
  /**
   * The LogQL query.
   */
  expr: string;
  /**
   * Used to override the name of the series.
   */
  legendFormat?: string;
  /**
   * Used to limit the number of log rows returned.
   */
  maxLines?: number;
  /**
   * @deprecated, now use step.
   */
  resolution?: number;
  editorMode?: QueryEditorMode;
  /**
   * @deprecated, now use queryType.
   */
  range?: boolean;
  /**
   * @deprecated, now use queryType.
   */
  instant?: boolean;
  /**
   * Used to set step value for range queries.
   */
  step?: string;
  /**
   * A unique identifier for the query within the list of targets.
   * In server side expressions, the refId is used as a variable name to identify results.
   * By default, the UI will assign A->Z; however setting meaningful names may be useful.
   */
  refId?: string | null;
  /**
   * If hide is set to true, Grafana will filter out the response(s) associated with this query before returning it to the panel.
   */
  hide?: boolean;
  /**
   * Specify the query flavor
   * TODO make this required and give it a default
   */
  queryType?: string;
  /**
   * For mixed data sources the selected datasource is on the query level.
   * For non mixed scenarios this is undefined.
   * TODO find a better way to do this ^ that's friendly to schema
   * TODO this shouldn't be unknown but DataSourceRef | null
   */
  datasource?: DataSourceRef;
  direction?: LokiQueryDirection;
}

export interface DataSourceRef {
  /**
   * The plugin type-id
   */
  type?: string;
  /**
   * Specific datasource instance
   */
  uid?: string;
}
