// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/piechart.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

/**
 * Select the pie chart display style.
 */
export type PieChartType = "pie" | "donut";

/**
 * Select labels to display on the pie chart.
 *  - Name - The series or field name.
 *  - Percent - The percentage of the whole.
 *  - Value - The raw numerical value.
 */
export type PieChartLabels = "name" | "value" | "percent";

/**
 * Select values to display in the legend.
 *  - Percent: The percentage of the whole.
 *  - Value: The raw numerical value.
 */
export type PieChartLegendValues = "value" | "percent";

export interface PieChartLegendOptions {
  values: PieChartLegendValues[];
  displayMode: LegendDisplayMode;
  placement: LegendPlacement;
  showLegend: boolean;
  asTable?: boolean;
  isVisible?: boolean;
  sortBy?: string;
  sortDesc?: boolean;
  width?: number;
  calcs: string[];
}

export interface Options {
  pieType: PieChartType;
  displayLabels?: PieChartLabels[] | null;
  tooltip: VizTooltipOptions;
  reduceOptions: ReduceDataOptions;
  text?: VizTextDisplayOptions;
  legend: PieChartLegendOptions;
  orientation: VizOrientation;
  /**
   * How slices are ordered.
   */
  sort?: SortOrder;
}

export type FieldConfig = HideableFieldConfig;

/**
 * TODO docs
 * Note: "hidden" needs to remain as an option for plugins compatibility
 */
export type LegendDisplayMode = "list" | "table" | "hidden";

/**
 * TODO docs
 */
export type LegendPlacement = "bottom" | "right";

/**
 * TODO docs
 */
export interface VizTooltipOptions {
  mode: TooltipDisplayMode;
  sort: SortOrder;
  maxWidth?: number;
  maxHeight?: number;
  hideZeros?: boolean;
}

/**
 * TODO docs
 */
export interface ReduceDataOptions {
  /**
   * If true show each row value
   */
  values?: boolean;
  /**
   * if showing all values limit
   */
  limit?: number;
  /**
   * When !values, pick one value for the whole field
   */
  calcs: string[];
  /**
   * Which fields to show.  By default this is only numeric fields
   */
  fields?: string;
}

/**
 * TODO docs
 */
export interface VizTextDisplayOptions {
  /**
   * Explicit title text size
   */
  titleSize?: number;
  /**
   * Explicit value text size
   */
  valueSize?: number;
  /**
   * Explicit percent text size
   */
  percentSize?: number;
}

/**
 * TODO docs
 */
export type VizOrientation = "auto" | "vertical" | "horizontal";

/**
 * TODO docs
 */
export interface HideableFieldConfig {
  hideFrom?: HideSeriesConfig;
}

/**
 * TODO docs
 */
export type TooltipDisplayMode = "single" | "multi" | "none";

/**
 * TODO docs
 */
export type SortOrder = "asc" | "desc" | "none";

/**
 * TODO docs
 */
export interface HideSeriesConfig {
  tooltip: boolean;
  legend: boolean;
  viz: boolean;
}
