// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/stat.jsonschema.json (see src/pin.ts). DO NOT EDIT.
/* eslint-disable */

export interface Options {
  graphMode: BigValueGraphMode;
  colorMode: BigValueColorMode;
  justifyMode: BigValueJustifyMode;
  textMode: BigValueTextMode;
  wideLayout: boolean;
  showPercentChange: boolean;
  reduceOptions: ReduceDataOptions;
  text?: VizTextDisplayOptions;
  percentChangeColorMode: PercentChangeColorMode;
  orientation: VizOrientation;
}

/**
 * TODO docs
 */
export type BigValueGraphMode = "none" | "line" | "area";

/**
 * TODO docs
 */
export type BigValueColorMode = "value" | "background" | "background_solid" | "none";

/**
 * TODO docs
 */
export type BigValueJustifyMode = "auto" | "center";

/**
 * TODO docs
 */
export type BigValueTextMode = "auto" | "value" | "value_and_name" | "name" | "none";

/**
 * TODO docs
 */
export interface ReduceDataOptions {
  /**
   * If true show each row value
   */
  values?: boolean;
  /**
   * if showing all values limit
   */
  limit?: number;
  /**
   * When !values, pick one value for the whole field
   */
  calcs: string[];
  /**
   * Which fields to show.  By default this is only numeric fields
   */
  fields?: string;
}

/**
 * TODO docs
 */
export interface VizTextDisplayOptions {
  /**
   * Explicit title text size
   */
  titleSize?: number;
  /**
   * Explicit value text size
   */
  valueSize?: number;
  /**
   * Explicit percent text size
   */
  percentSize?: number;
}

/**
 * TODO docs
 */
export type PercentChangeColorMode = "standard" | "inverted" | "same_as_value";

/**
 * TODO docs
 */
export type VizOrientation = "auto" | "vertical" | "horizontal";
