// Code generated by chant generate from the vendored Grafana schema
// src/spec/schemas/xychart.jsonschema.json (see src/pin.ts) and its correction
// overlay in src/spec/overlay/ (see src/spec/overlay.ts). DO NOT EDIT.
/* eslint-disable */

export type PointShape = "circle" | "square";

export type SeriesMapping = "auto" | "manual";

export type XYShowMode = "points" | "lines" | "points+lines";

/**
 * NOTE: (copied from dashboard_kind.cue, since not exported)
 * Matcher is a predicate configuration. Based on the config a set of field(s) or values is filtered in order to apply override / transformation.
 * It comes with in id ( to resolve implementation from registry) and a configuration that’s specific to a particular matcher type.
 */
export interface MatcherConfig {
  /**
   * The matcher id. This is used to find the matcher implementation from registry.
   */
  id: string;
  /**
   * The matcher options. This is specific to the matcher implementation: a field name for byName, a frame index for byIndex.
   */
  options?: unknown;
}

export interface FieldConfig {
  show?: XYShowMode;
  pointSize?: {
    fixed?: number;
    min?: number;
    max?: number;
  };
  pointShape?: PointShape;
  pointStrokeWidth?: number;
  fillOpacity?: number;
  lineWidth?: number;
  hideFrom?: HideSeriesConfig;
  axisPlacement?: AxisPlacement;
  axisColorMode?: AxisColorMode;
  axisLabel?: string;
  axisWidth?: number;
  axisSoftMin?: number;
  axisSoftMax?: number;
  axisGridShow?: boolean;
  scaleDistribution?: ScaleDistributionConfig;
  axisCenteredZero?: boolean;
  lineStyle?: LineStyle;
  axisBorderShow?: boolean;
}

export interface XYSeriesConfig {
  name?: {
    fixed?: string;
  };
  frame?: {
    matcher: MatcherConfig;
  };
  x?: {
    matcher: MatcherConfig;
  };
  y?: {
    matcher: MatcherConfig;
  };
  color?: {
    matcher: MatcherConfig;
  };
  size?: {
    matcher: MatcherConfig;
  };
}

export interface Options {
  mapping: SeriesMapping;
  legend: VizLegendOptions;
  tooltip: VizTooltipOptions;
  series: XYSeriesConfig[];
}

/**
 * TODO docs
 */
export interface HideSeriesConfig {
  tooltip: boolean;
  legend: boolean;
  viz: boolean;
}

/**
 * TODO docs
 */
export type AxisPlacement = "auto" | "top" | "right" | "bottom" | "left" | "hidden";

/**
 * TODO docs
 */
export type AxisColorMode = "text" | "series";

/**
 * TODO docs
 */
export interface ScaleDistributionConfig {
  type: ScaleDistribution;
  log?: number;
  linearThreshold?: number;
}

/**
 * TODO docs
 */
export interface LineStyle {
  fill?: "solid" | "dash" | "dot" | "square";
  dash?: number[];
}

/**
 * TODO docs
 */
export interface VizLegendOptions {
  displayMode: LegendDisplayMode;
  placement: LegendPlacement;
  showLegend: boolean;
  asTable?: boolean;
  isVisible?: boolean;
  sortBy?: string;
  sortDesc?: boolean;
  width?: number;
  calcs: string[];
}

/**
 * TODO docs
 */
export interface VizTooltipOptions {
  mode: TooltipDisplayMode;
  sort: SortOrder;
  maxWidth?: number;
  maxHeight?: number;
  hideZeros?: boolean;
}

/**
 * TODO docs
 */
export type ScaleDistribution = "linear" | "log" | "ordinal" | "symlog";

/**
 * TODO docs
 * Note: "hidden" needs to remain as an option for plugins compatibility
 */
export type LegendDisplayMode = "list" | "table" | "hidden";

/**
 * TODO docs
 */
export type LegendPlacement = "bottom" | "right";

/**
 * TODO docs
 */
export type TooltipDisplayMode = "single" | "multi" | "none";

/**
 * TODO docs
 */
export type SortOrder = "asc" | "desc" | "none";
