// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { cedc010 } from "./cedc010";
import { cedc011 } from "./cedc011";
import { cedc012 } from "./cedc012";
import { cedc013 } from "./cedc013";
import { cedc014 } from "./cedc014";
import { cede010 } from "./cede010";
import { cede011 } from "./cede011";
import { ceds010 } from "./ceds010";
import { ceds011 } from "./ceds011";
import { ceds012 } from "./ceds012";
import { dwdc010 } from "./dwdc010";
import { dwdc011 } from "./dwdc011";
import { dwdc012 } from "./dwdc012";
import { dwds010 } from "./dwds010";

export const postSynthChecks: PostSynthCheck[] = [
  cedc010,
  cedc011,
  cedc012,
  cedc013,
  cedc014,
  cede010,
  cede011,
  ceds010,
  ceds011,
  ceds012,
  dwdc010,
  dwdc011,
  dwdc012,
  dwds010,
];
