// Generated by chant — do not edit directly.
// Source: hello.op.ts
import { proxyActivities, condition, defineSignal, setHandler, upsertSearchAttributes } from '@temporalio/workflow';
import { TEMPORAL_ACTIVITY_PROFILES } from '@intentius/chant-lexicon-temporal';
import type * as activities from './activities';

const { shellCmd } = proxyActivities<typeof activities>(
  TEMPORAL_ACTIVITY_PROFILES.fastIdempotent,
);

export async function helloWorkflow(): Promise<void> {
  upsertSearchAttributes({"OpName":["hello"]});

  // Phase: Greet
  upsertSearchAttributes({ Phase: ["Greet"] });
  await shellCmd({"cmd":"echo hello from chant"});

}
