// Generated by chant — do not edit directly.
// Run: npx tsx ops/hello/worker.ts
import { Worker, NativeConnection } from '@temporalio/worker';
import { fileURLToPath } from 'url';
import * as activities from './activities.js';

async function run(): Promise<void> {
  const { default: chantConfig } = await import('../../chant.config.js');

  const profileName = process.env.TEMPORAL_PROFILE ?? chantConfig.temporal?.defaultProfile ?? 'local';
  const profile = chantConfig.temporal?.profiles?.[profileName];

  if (!profile) {
    console.error(
      `Unknown Temporal profile "${profileName}". Available: ${Object.keys(chantConfig.temporal?.profiles ?? {}).join(', ')}`,
    );
    process.exit(1);
  }

  const apiKey =
    typeof profile.apiKey === 'object' && profile.apiKey !== null
      ? process.env[(profile.apiKey as { env: string }).env]
      : (profile.apiKey as string | undefined);

  const connection = await NativeConnection.connect({
    address: profile.address,
    ...(profile.tls && {
      tls: typeof profile.tls === 'object' ? profile.tls : {},
      metadata: apiKey ? { Authorization: `Bearer ${apiKey}` } : {},
    }),
  });

  const worker = await Worker.create({
    connection,
    namespace: profile.namespace,
    taskQueue: profile.taskQueue ?? "hello",
    workflowsPath: fileURLToPath(new URL('./workflow.js', import.meta.url)),
    activities,
  });

  console.log(`Worker ready — polling task queue: ${profile.taskQueue ?? "hello"}`);
  await worker.run();
}

run().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
