/**
 * The composite catalog matches what this lexicon exports (#2662, #3104).
 *
 * `catalog.ts` is generated by `npm run generate:composite-catalogs -- sql` and
 * is what `chant serve mcp` lists and check-lexicon counts.
 */

import { describe, expect, test } from "vitest";
import { isCompositeDefinition } from "@intentius/chant/composite";
import * as composites from "./index";
import { compositeCatalog } from "./catalog";
import { sqlPlugin } from "../plugin";

const exported = Object.entries(composites)
  .filter(([, value]) => isCompositeDefinition(value))
  .map(([name]) => name)
  .sort();
const catalogued = compositeCatalog.map((entry) => entry.name).sort();

describe("the sql composite catalog", () => {
  test("every exported composite has an entry, and every entry names an exported composite", () => {
    expect(exported).toEqual(["CdcMirror", "EventsTable", "ReplacingTable", "RollupView", "ShardedTable"]);
    expect(catalogued, "regenerate with `npm run generate:composite-catalogs -- sql`").toEqual(exported);
  });

  test("every entry says what it is and what it bundles", () => {
    const bundles = Object.fromEntries(compositeCatalog.map((entry) => [entry.name, entry.bundles]));
    expect(bundles).toEqual({
      CdcMirror: ["ClickHouseTable", "ClickHouseView"],
      EventsTable: ["ClickHouseTable"],
      ReplacingTable: ["ClickHouseTable"],
      RollupView: ["ClickHouseTable", "ClickHouseView"],
      ShardedTable: ["ClickHouseTable"],
    });
    for (const entry of compositeCatalog) {
      expect(entry.lexicon, entry.name).toBe("sql");
      expect(entry.description.length, entry.name).toBeGreaterThan(0);
      expect(entry.params.find((p) => p.name === "name")?.required, entry.name).toBe(true);
    }
  });

  test("the plugin contributes it", () => {
    expect(sqlPlugin.composites?.()).toBe(compositeCatalog);
  });
});
