// Generated by scripts/generate-composite-catalogs.ts (#2662) from this
// lexicon's composite exports. Do not edit by hand: run
// `npm run generate:composite-catalogs`. catalog.test.ts holds it to the exports.
import type { CompositeEntry } from "@intentius/chant/lexicon";

export const compositeCatalog: CompositeEntry[] = [
  {
    "name": "CdcMirror",
    "lexicon": "sql",
    "description": "A ReplacingMergeTree mirror of a CDC-fed source table, with a view of the rows not deleted.",
    "bundles": [
      "ClickHouseTable",
      "ClickHouseView"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "The mirror table's name."
      },
      {
        "name": "columns",
        "type": "string",
        "required": true,
        "description": "The source table's columns, as SQL, without the version and deleted columns."
      },
      {
        "name": "primaryKey",
        "type": "string",
        "required": true,
        "description": "The source table's primary key, the mirror's sort key: `id` or `(tenant_id, id)`."
      },
      {
        "name": "version",
        "type": "string",
        "required": false,
        "description": "The version column the pipeline writes (default `_version`, UInt64)."
      },
      {
        "name": "deleted",
        "type": "string",
        "required": false,
        "description": "The deleted flag the pipeline writes (default `_is_deleted`, UInt8, 1 for a delete)."
      },
      {
        "name": "partitionBy",
        "type": "string",
        "required": false,
        "description": "A `PARTITION BY` expression."
      }
    ]
  },
  {
    "name": "EventsTable",
    "lexicon": "sql",
    "description": "An append-only MergeTree events table, partitioned by its timestamp and expired by TTL.",
    "bundles": [
      "ClickHouseTable"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "The table's name, `name` or `database.name`."
      },
      {
        "name": "columns",
        "type": "string",
        "required": true,
        "description": "Every column except the timestamp, as SQL: `user_id UUID, kind LowCardinality(String)`."
      },
      {
        "name": "orderBy",
        "type": "string",
        "required": true,
        "description": "The sort key."
      },
      {
        "name": "timestamp",
        "type": "string",
        "required": false,
        "description": "The timestamp column (default `ts`)."
      },
      {
        "name": "timestampType",
        "type": "string",
        "required": false,
        "description": "The timestamp's type (default `DateTime`): a Date, DateTime or DateTime64."
      },
      {
        "name": "ttlDays",
        "type": "number",
        "required": false,
        "description": "Days a row is kept (default 90)."
      },
      {
        "name": "partitionBy",
        "type": "string",
        "required": false,
        "description": "The partition key (default `toYYYYMM(<timestamp>)`)."
      }
    ]
  },
  {
    "name": "ReplacingTable",
    "lexicon": "sql",
    "description": "A ReplacingMergeTree table that keeps the highest version of each row, with its version column.",
    "bundles": [
      "ClickHouseTable"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "The table's name, `name` or `database.name`."
      },
      {
        "name": "columns",
        "type": "string",
        "required": true,
        "description": "Every column except the version column, as SQL: `id UInt64, email String`."
      },
      {
        "name": "orderBy",
        "type": "string",
        "required": true,
        "description": "The sort key, which is also the key rows are deduplicated by: `id` or `(tenant_id, id)`."
      },
      {
        "name": "version",
        "type": "string",
        "required": false,
        "description": "The version column (default `version`)."
      },
      {
        "name": "versionType",
        "type": "string",
        "required": false,
        "description": "The version column's type (default `UInt64`): a UInt, Date, DateTime or DateTime64."
      },
      {
        "name": "partitionBy",
        "type": "string",
        "required": false,
        "description": "A `PARTITION BY` expression."
      }
    ]
  },
  {
    "name": "RollupView",
    "lexicon": "sql",
    "description": "A materialized view that rolls a source table up into a target table it declares beside it.",
    "bundles": [
      "ClickHouseTable",
      "ClickHouseView"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "The target table's name."
      },
      {
        "name": "source",
        "type": "ClickHouseRelation",
        "required": true,
        "description": "The table or view the rollup reads, as the entity: `events`."
      },
      {
        "name": "columns",
        "type": "string",
        "required": true,
        "description": "The target's columns, as SQL: `day Date, kind LowCardinality(String), n UInt64`."
      },
      {
        "name": "select",
        "type": "string",
        "required": true,
        "description": "The select list, each item aliased to a target column: `toDate(ts) AS day, kind, count() AS n`."
      },
      {
        "name": "groupBy",
        "type": "string",
        "required": true,
        "description": "The grouping key: `day, kind`."
      },
      {
        "name": "orderBy",
        "type": "string",
        "required": false,
        "description": "The target's sort key (default `groupBy` in parentheses)."
      },
      {
        "name": "engine",
        "type": "string",
        "required": false,
        "description": "The target's engine (default `SummingMergeTree`)."
      },
      {
        "name": "partitionBy",
        "type": "string",
        "required": false,
        "description": "The target's partition key."
      }
    ]
  },
  {
    "name": "ShardedTable",
    "lexicon": "sql",
    "description": "A ReplicatedMergeTree table on every node of a cluster and the Distributed table over it.",
    "bundles": [
      "ClickHouseTable"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "The Distributed table's name, unqualified."
      },
      {
        "name": "cluster",
        "type": "string",
        "required": true,
        "description": "The cluster both tables are created on, as the server's `remote_servers` names it."
      },
      {
        "name": "columns",
        "type": "string",
        "required": true,
        "description": "The columns, as SQL."
      },
      {
        "name": "orderBy",
        "type": "string",
        "required": true,
        "description": "The local table's sort key."
      },
      {
        "name": "shardingKey",
        "type": "string",
        "required": false,
        "description": "The expression that picks a shard for an inserted row (default `rand()`)."
      },
      {
        "name": "partitionBy",
        "type": "string",
        "required": false,
        "description": "The local table's partition key."
      }
    ]
  }
];
