// Generated by scripts/generate-composite-catalogs.ts (#2662) from this
// lexicon's composite exports. Do not edit by hand: run
// `npm run generate:composite-catalogs`. catalog.test.ts holds it to the exports.
import type { CompositeEntry } from "@intentius/chant/lexicon";

export const compositeCatalog: CompositeEntry[] = [
  {
    "name": "BunPipeline",
    "lexicon": "gitlab",
    "description": "NodePipeline preset for Bun projects.",
    "bundles": [
      "Default",
      "Job"
    ],
    "params": [
      {
        "name": "defaults",
        "type": "{ defaults?: Partial<ConstructorParameters<typeof Default>[0]>; build?: Partial<ConstructorParameters<typeof Job>[0]>...",
        "required": false,
        "description": "Per-member defaults for customizing the generated resources."
      },
      {
        "name": "nodeVersion",
        "type": "string",
        "required": false,
        "description": "Node.js version."
      },
      {
        "name": "installCommand",
        "type": "string",
        "required": false,
        "description": "Override auto-detected install command"
      },
      {
        "name": "buildScript",
        "type": "string",
        "required": false,
        "description": "Build script name (runs via package manager)."
      },
      {
        "name": "buildArtifactPaths",
        "type": "string[]",
        "required": false,
        "description": "Artifact paths from build."
      },
      {
        "name": "artifactExpiry",
        "type": "string",
        "required": false,
        "description": "Artifact expiry."
      },
      {
        "name": "testScript",
        "type": "string",
        "required": false,
        "description": "Test script name."
      },
      {
        "name": "packageManager",
        "type": "\"npm\" | \"pnpm\" | \"bun\"",
        "required": false,
        "description": "Package manager."
      }
    ]
  },
  {
    "name": "DockerBuild",
    "lexicon": "gitlab",
    "description": "Bundles Job.",
    "bundles": [
      "Job"
    ],
    "params": [
      {
        "name": "stage",
        "type": "string",
        "required": false,
        "description": "Job stage."
      },
      {
        "name": "tag",
        "type": "string",
        "required": false,
        "description": "Image tag."
      },
      {
        "name": "dockerfile",
        "type": "string",
        "required": false,
        "description": "Dockerfile path."
      },
      {
        "name": "context",
        "type": "string",
        "required": false,
        "description": "Build context."
      },
      {
        "name": "registry",
        "type": "string",
        "required": false,
        "description": "Container registry."
      },
      {
        "name": "image",
        "type": "string",
        "required": false,
        "description": "Full image name."
      },
      {
        "name": "tagLatest",
        "type": "boolean",
        "required": false,
        "description": "Tag as :latest on default branch."
      },
      {
        "name": "buildArgs",
        "type": "Record<string, string>",
        "required": false,
        "description": "Extra docker build --build-arg flags"
      },
      {
        "name": "rules",
        "type": "InstanceType<typeof Rule>[]",
        "required": false,
        "description": "Job rules."
      },
      {
        "name": "dockerVersion",
        "type": "string",
        "required": false,
        "description": "Docker version."
      },
      {
        "name": "defaults",
        "type": "{ build?: Partial<ConstructorParameters<typeof Job>[0]>; }",
        "required": false,
        "description": "Per-member defaults for customizing the build job."
      }
    ]
  },
  {
    "name": "MrPlanReport",
    "lexicon": "gitlab",
    "description": "A CI job that publishes `chant lifecycle plan` as the GitLab merge-request plan widget.",
    "bundles": [
      "Job"
    ],
    "params": [
      {
        "name": "environment",
        "type": "string",
        "required": true,
        "description": "Lifecycle environment to plan against — the `<environment>` argument of `chant lifecycle plan`."
      },
      {
        "name": "lexicon",
        "type": "string",
        "required": false,
        "description": "Restrict the plan to one lexicon (the optional `[lexicon]` argument)."
      },
      {
        "name": "stage",
        "type": "string",
        "required": false,
        "description": "Stage for the plan job."
      },
      {
        "name": "image",
        "type": "string",
        "required": false,
        "description": "Image to run chant in."
      },
      {
        "name": "ownedOnly",
        "type": "boolean",
        "required": false,
        "description": "Plan against chant-owned resources only (passes `--owned`)."
      },
      {
        "name": "reportFile",
        "type": "string",
        "required": false,
        "description": "Artifact filename the report is written to."
      },
      {
        "name": "before",
        "type": "string[]",
        "required": false,
        "description": "Commands to run before the plan — typically cloud-credential setup, since the plan queries the live system to classify create/update/delete."
      },
      {
        "name": "defaults",
        "type": "{ plan?: Partial<ConstructorParameters<typeof Job>[0]>; }",
        "required": false,
        "description": "Per-member defaults for customizing the generated job."
      }
    ]
  },
  {
    "name": "NodePipeline",
    "lexicon": "gitlab",
    "description": "Bundles Default, Job.",
    "bundles": [
      "Default",
      "Job"
    ],
    "params": [
      {
        "name": "nodeVersion",
        "type": "string",
        "required": false,
        "description": "Node.js version."
      },
      {
        "name": "packageManager",
        "type": "\"npm\" | \"pnpm\" | \"bun\"",
        "required": false,
        "description": "Package manager."
      },
      {
        "name": "buildScript",
        "type": "string",
        "required": false,
        "description": "Build script name (runs via package manager)."
      },
      {
        "name": "testScript",
        "type": "string",
        "required": false,
        "description": "Test script name."
      },
      {
        "name": "buildArtifactPaths",
        "type": "string[]",
        "required": false,
        "description": "Artifact paths from build."
      },
      {
        "name": "artifactExpiry",
        "type": "string",
        "required": false,
        "description": "Artifact expiry."
      },
      {
        "name": "installCommand",
        "type": "string",
        "required": false,
        "description": "Override auto-detected install command"
      },
      {
        "name": "defaults",
        "type": "{ defaults?: Partial<ConstructorParameters<typeof Default>[0]>; build?: Partial<ConstructorParameters<typeof Job>[0]>...",
        "required": false,
        "description": "Per-member defaults for customizing the generated resources."
      }
    ]
  },
  {
    "name": "PnpmPipeline",
    "lexicon": "gitlab",
    "description": "NodePipeline preset for pnpm projects.",
    "bundles": [
      "Default",
      "Job"
    ],
    "params": [
      {
        "name": "defaults",
        "type": "{ defaults?: Partial<ConstructorParameters<typeof Default>[0]>; build?: Partial<ConstructorParameters<typeof Job>[0]>...",
        "required": false,
        "description": "Per-member defaults for customizing the generated resources."
      },
      {
        "name": "nodeVersion",
        "type": "string",
        "required": false,
        "description": "Node.js version."
      },
      {
        "name": "installCommand",
        "type": "string",
        "required": false,
        "description": "Override auto-detected install command"
      },
      {
        "name": "buildScript",
        "type": "string",
        "required": false,
        "description": "Build script name (runs via package manager)."
      },
      {
        "name": "buildArtifactPaths",
        "type": "string[]",
        "required": false,
        "description": "Artifact paths from build."
      },
      {
        "name": "artifactExpiry",
        "type": "string",
        "required": false,
        "description": "Artifact expiry."
      },
      {
        "name": "testScript",
        "type": "string",
        "required": false,
        "description": "Test script name."
      },
      {
        "name": "packageManager",
        "type": "\"npm\" | \"pnpm\" | \"bun\"",
        "required": false,
        "description": "Package manager."
      }
    ]
  },
  {
    "name": "PythonPipeline",
    "lexicon": "gitlab",
    "description": "Bundles Default, Job.",
    "bundles": [
      "Default",
      "Job"
    ],
    "params": [
      {
        "name": "pythonVersion",
        "type": "string",
        "required": false,
        "description": "Python version."
      },
      {
        "name": "testCommand",
        "type": "string",
        "required": false,
        "description": "Test command."
      },
      {
        "name": "lintCommand",
        "type": "string | null",
        "required": false,
        "description": "Lint command."
      },
      {
        "name": "requirementsFile",
        "type": "string",
        "required": false,
        "description": "Requirements file."
      },
      {
        "name": "usePoetry",
        "type": "boolean",
        "required": false,
        "description": "Use poetry instead of pip."
      },
      {
        "name": "defaults",
        "type": "{ defaults?: Partial<ConstructorParameters<typeof Default>[0]>; test?: Partial<ConstructorParameters<typeof Job>[0]>;...",
        "required": false,
        "description": "Per-member defaults for customizing the generated resources."
      }
    ]
  },
  {
    "name": "ReviewApp",
    "lexicon": "gitlab",
    "description": "Bundles Job.",
    "bundles": [
      "Job"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Base name for the jobs (e.g. \"review\" → review-deploy, review-stop in YAML)."
      },
      {
        "name": "deployScript",
        "type": "string | string[]",
        "required": true,
        "description": "Deploy script command(s)."
      },
      {
        "name": "stopScript",
        "type": "string | string[]",
        "required": false,
        "description": "Stop script command(s)."
      },
      {
        "name": "urlPattern",
        "type": "string",
        "required": false,
        "description": "Environment URL pattern."
      },
      {
        "name": "autoStopIn",
        "type": "string",
        "required": false,
        "description": "Auto-stop timer."
      },
      {
        "name": "image",
        "type": "InstanceType<typeof Image>",
        "required": false,
        "description": "Override image for both jobs."
      },
      {
        "name": "stage",
        "type": "string",
        "required": false,
        "description": "Job stage."
      },
      {
        "name": "defaults",
        "type": "{ deploy?: Partial<ConstructorParameters<typeof Job>[0]>; stop?: Partial<ConstructorParameters<typeof Job>[0]>; }",
        "required": false,
        "description": "Per-member defaults for customizing the deploy and stop jobs."
      }
    ]
  }
];
