// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { wfj010 } from "./wfj010";
import { wfj011 } from "./wfj011";

export const postSynthChecks: PostSynthCheck[] = [
  wfj010,
  wfj011,
];
