default:
    @just --list

generate:
    bun run src/codegen/generate-cli.ts

validate:
    bun run src/validate-cli.ts

docs:
    bun run src/codegen/docs-cli.ts
    bun install --cwd docs
    bun --cwd docs dev

docs-build:
    bun run src/codegen/docs-cli.ts
    bun install --cwd docs
    bun --cwd docs build

package: generate validate
