// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { argo002 } from "./argo002";
import { argo003 } from "./argo003";
import { argo005 } from "./argo005";
import { wk8005 } from "./wk8005";
import { wk8006 } from "./wk8006";
import { wk8041 } from "./wk8041";
import { wk8042 } from "./wk8042";
import { wk8101 } from "./wk8101";
import { wk8102 } from "./wk8102";
import { wk8103 } from "./wk8103";
import { wk8104 } from "./wk8104";
import { wk8105 } from "./wk8105";
import { wk8201 } from "./wk8201";
import { wk8202 } from "./wk8202";
import { wk8203 } from "./wk8203";
import { wk8204 } from "./wk8204";
import { wk8205 } from "./wk8205";
import { wk8207 } from "./wk8207";
import { wk8208 } from "./wk8208";
import { wk8209 } from "./wk8209";
import { wk8301 } from "./wk8301";
import { wk8302 } from "./wk8302";
import { wk8303 } from "./wk8303";
import { wk8304 } from "./wk8304";
import { wk8305 } from "./wk8305";
import { wk8306 } from "./wk8306";
import { wk8401 } from "./wk8401";
import { wk8402 } from "./wk8402";
import { wk8403 } from "./wk8403";

export const postSynthChecks: PostSynthCheck[] = [
  argo002,
  argo003,
  argo005,
  wk8005,
  wk8006,
  wk8041,
  wk8042,
  wk8101,
  wk8102,
  wk8103,
  wk8104,
  wk8105,
  wk8201,
  wk8202,
  wk8203,
  wk8204,
  wk8205,
  wk8207,
  wk8208,
  wk8209,
  wk8301,
  wk8302,
  wk8303,
  wk8304,
  wk8305,
  wk8306,
  wk8401,
  wk8402,
  wk8403,
];
