/**
 * TypeScript declaration file generator — produces index.d.ts with all
 * Kubernetes resource and property type classes.
 */

import type { K8sParseResult, ParsedDefinitionType } from "../spec/parse";
import { k8sShortName } from "../spec/parse";
import type { NamingStrategy } from "./naming";
import { propertyTypeName, extractDefName } from "./naming";
import {
  writeResourceClass,
  resolveConstructorType,
  type DtsProperty,
  type DtsAttribute,
} from "@intentius/chant/codegen/generate-typescript";

interface ResourceEntry {
  tsName: string;
  isProperty: boolean;
  properties: DtsProperty[];
  attributes: DtsAttribute[];
  remap: Map<string, string>;
}

/**
 * Generate the complete .d.ts file content.
 */
export function generateTypeScriptDeclarations(
  results: K8sParseResult[],
  naming: NamingStrategy,
  definitionTypes: ParsedDefinitionType[] = [],
): string {
  const lines: string[] = [];
  lines.push("// Code generated by chant k8s generate. DO NOT EDIT.");

  const resources: ResourceEntry[] = [];

  for (const r of results) {
    const typeName = r.resource.typeName;
    const tsName = naming.resolve(typeName);
    if (!tsName) continue;

    const shortName = k8sShortName(typeName);
    const remap = new Map<string, string>();
    for (const pt of r.propertyTypes) {
      const defName = extractDefName(pt.name, shortName);
      remap.set(pt.name, propertyTypeName(tsName, defName));
    }
    for (const e of r.enums) {
      const defName = extractDefName(e.name, shortName);
      remap.set(e.name, propertyTypeName(tsName, defName));
    }

    const dtsProps: DtsProperty[] = r.resource.properties.map((p) => ({
      name: p.name,
      type: p.tsType,
      required: p.required,
      description: p.description,
    }));
    const dtsAttrs: DtsAttribute[] = r.resource.attributes.map((a) => ({
      name: a.name,
      type: a.tsType,
    }));

    resources.push({ tsName, isProperty: !!r.isProperty, properties: dtsProps, attributes: dtsAttrs, remap });

    for (const alias of naming.aliases(typeName)) {
      resources.push({ tsName: alias, isProperty: !!r.isProperty, properties: dtsProps, attributes: dtsAttrs, remap });
    }
  }

  // Sort alphabetically
  resources.sort((a, b) => a.tsName.localeCompare(b.tsName));

  // Resource classes
  const resourceEntries = resources.filter((r) => !r.isProperty);
  const propertyEntries = resources.filter((r) => r.isProperty);

  if (resourceEntries.length > 0) {
    lines.push("");
    lines.push("// --- Kubernetes Resource classes ---");
    for (const re of resourceEntries) {
      writeResourceClass(lines, re.tsName, re.properties, re.attributes, re.remap);
    }
  }

  if (propertyEntries.length > 0) {
    lines.push("");
    lines.push("// --- Property type classes ---");
    for (const pe of propertyEntries) {
      writeMembersInterface(lines, pe.tsName, undefined, pe.properties, pe.remap);
      lines.push(`export declare class ${pe.tsName} {`);
      lines.push(`  constructor(props: ${pe.tsName});`);
      lines.push("}");
    }
  }

  // chant #3093 — every other object definition a resource reaches. Declared
  // as interfaces: nothing constructs them at runtime, an author writes them
  // as object literals.
  if (definitionTypes.length > 0) {
    const classNames = new Set(resources.map((r) => r.tsName));
    lines.push("");
    lines.push("// --- Definition interfaces ---");
    for (const dt of definitionTypes) {
      if (classNames.has(dt.name)) {
        throw new Error(`k8s codegen: definition ${dt.defKey} would be declared as ${dt.name}, which is already a class`);
      }
      const props: DtsProperty[] = dt.properties.map((p) => ({
        name: p.name,
        type: p.tsType,
        required: p.required,
        description: p.description,
      }));
      writeMembersInterface(lines, dt.name, dt.description, props, undefined);
    }
  }

  lines.push("");
  return lines.join("\n");
}

const IDENT = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/**
 * Write the members of a property type or definition as an interface. For a
 * property type the interface merges with its class, so `new Container({...})`
 * and a `{...}` literal both check against the same members, and so does a
 * field typed `Container`. A class with only a constructor has no members, and
 * an empty instance type accepts any object (chant #3093).
 */
function writeMembersInterface(
  lines: string[],
  tsName: string,
  description: string | undefined,
  props: DtsProperty[],
  remap: Map<string, string> | undefined,
): void {
  lines.push("");
  if (description) lines.push(`/** ${jsdoc(description)} */`);
  if (props.length === 0) {
    lines.push(`export interface ${tsName} {}`);
    return;
  }
  // Required first, then optional, each alphabetical — the constructor order.
  const sorted = [...props].sort((a, b) => {
    if (a.required !== b.required) return a.required ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  lines.push(`export interface ${tsName} {`);
  for (const p of sorted) {
    if (p.description) lines.push(`  /** ${jsdoc(p.description)} */`);
    const key = IDENT.test(p.name) ? p.name : JSON.stringify(p.name);
    lines.push(`  ${key}${p.required ? "" : "?"}: ${resolveConstructorType(p.type, remap)};`);
  }
  lines.push("}");
}

/** A description made safe for a one-line JSDoc comment. */
function jsdoc(text: string): string {
  return text.replace(/\*\//g, "*\\/");
}
