// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { tmp001 } from "./tmp001-retention-too-short";
import { tmp002 } from "./tmp002-allowall-without-note";
import { tmp010 } from "./tmp010-cron-syntax";
import { tmp011 } from "./tmp011-namespace-reference";

export const postSynthChecks: PostSynthCheck[] = [
  tmp001,
  tmp002,
  tmp010,
  tmp011,
];
