// mock-cell.ts — nginx stub that impersonates a GitLab cell for local routing tests.
//
// The mock responds on port 8181 (workhorse) which is what the cell-registry.json
// in the routing-rules ConfigMap points to. It returns:
//   - Body:   "cell=<name>\n"
//   - Header: X-Cell: <name>
// so the validation script can assert that the correct cell was selected.
//
// Service name MUST match cell-registry.json format:
//   gitlab-cell-<name>-webservice-default  in namespace cell-<name>
// This is the same name the real GitLab Helm chart uses for the webservice service.

import { Deployment, Service, ConfigMap } from "@intentius/chant-lexicon-k8s";
import { MOCK_GITLAB_IMAGE } from "./cluster";

export function createMockCell(cellName: string) {
  const ns = `cell-${cellName}`;
  const appLabel = `mock-gitlab-${cellName}`;
  const labels = {
    "app.kubernetes.io/name": appLabel,
    "gitlab.example.com/cell": cellName,
  };

  // Nginx config: listen ONLY on port 8181 (workhorse).
  // cell-registry.json points to port 8181. Listening on 8080 too would mask
  // the bug where cell-registry.json accidentally uses port 8080 (puma) —
  // that misconfiguration must fail loudly so the smoke test catches it.
  const nginxConfig = new ConfigMap({
    metadata: { name: appLabel, namespace: ns },
    data: {
      "default.conf": `
server {
  listen 8181;
  server_name _;
  location / {
    add_header X-Cell "${cellName}";
    add_header X-Cell-Port "8181";
    return 200 "cell=${cellName}\\n";
  }
  location /healthz {
    return 200 "ok\\n";
  }
}
`,
    },
  });

  const deployment = new Deployment({
    metadata: { name: appLabel, namespace: ns, labels },
    spec: {
      replicas: 1,
      selector: { matchLabels: { "app.kubernetes.io/name": appLabel } },
      template: {
        metadata: { labels: { "app.kubernetes.io/name": appLabel } },
        spec: {
          containers: [{
            name: "mock-gitlab",
            image: MOCK_GITLAB_IMAGE,
            imagePullPolicy: "IfNotPresent",
            ports: [
              { name: "workhorse", containerPort: 8181 },
            ],
            resources: {
              requests: { cpu: "10m", memory: "32Mi" },
              limits: { cpu: "100m", memory: "64Mi" },
            },
            // Override the default.conf to listen on port 8181 only.
            volumeMounts: [{ name: "nginx-conf", mountPath: "/etc/nginx/conf.d" }],
          }],
          volumes: [{ name: "nginx-conf", configMap: { name: appLabel } }],
        },
      },
    },
  });

  // Service name MUST be gitlab-cell-<name>-webservice-default — this is the name
  // referenced in cell-registry.json generated by src/system/routing-rules.ts.
  const service = new Service({
    metadata: {
      name: `gitlab-cell-${cellName}-webservice-default`,
      namespace: ns,
      labels,
    },
    spec: {
      selector: { "app.kubernetes.io/name": appLabel },
      ports: [
        // Port 8181 only — matches cell-registry.json. Requests to port 8080
        // will get a connection-refused, catching any misconfiguration early.
        { name: "workhorse", port: 8181, targetPort: "workhorse" },
      ],
    },
  });

  return { nginxConfig, deployment, service };
}
