// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { sys010 } from "./sys010-key-over-plain-http";

export const postSynthChecks: PostSynthCheck[] = [
  sys010,
];
