// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { graf101 } from "./graf101";
import { graf102 } from "./graf102";
import { graf103 } from "./graf103";
import { graf104 } from "./graf104";
import { graf105 } from "./graf105";
import { graf106 } from "./graf106";
import { graf107 } from "./graf107";
import { graf108 } from "./graf108";
import { graf110 } from "./graf110";
import { graf111 } from "./graf111";
import { graf112 } from "./graf112";
import { graf113 } from "./graf113";
import { graf114 } from "./graf114";
import { graf115 } from "./graf115";

export const postSynthChecks: PostSynthCheck[] = [
  graf101,
  graf102,
  graf103,
  graf104,
  graf105,
  graf106,
  graf107,
  graf108,
  graf110,
  graf111,
  graf112,
  graf113,
  graf114,
  graf115,
];
