// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { wgl010 } from "./wgl010";
import { wgl011 } from "./wgl011";
import { wgl012 } from "./wgl012";
import { wgl013 } from "./wgl013";
import { wgl014 } from "./wgl014";
import { wgl015 } from "./wgl015";
import { wgl016 } from "./wgl016";
import { wgl017 } from "./wgl017";
import { wgl018 } from "./wgl018";
import { wgl019 } from "./wgl019";
import { wgl020 } from "./wgl020";
import { wgl021 } from "./wgl021";
import { wgl022 } from "./wgl022";
import { wgl023 } from "./wgl023";
import { wgl024 } from "./wgl024";
import { wgl025 } from "./wgl025";
import { wgl026 } from "./wgl026";
import { wgl027 } from "./wgl027";
import { wgl028 } from "./wgl028";
import { wgl029 } from "./wgl029";
import { wgl030 } from "./wgl030";
import { wgl031 } from "./wgl031";
import { wgl032 } from "./wgl032";
import { wgl033 } from "./wgl033";
import { wgl034 } from "./wgl034";
import { wgl035 } from "./wgl035";
import { wgl036 } from "./wgl036";
import { wgl037 } from "./wgl037";
import { wgl038 } from "./wgl038";
import { wgl039 } from "./wgl039";
import { wgl040 } from "./wgl040";
import { wgl041 } from "./wgl041";
import { wgl042 } from "./wgl042";
import { wgl043 } from "./wgl043";
import { wgl044 } from "./wgl044";
import { wgl045 } from "./wgl045";
import { wgl046 } from "./wgl046";
import { wgl047 } from "./wgl047";
import { wgl048 } from "./wgl048";

export const postSynthChecks: PostSynthCheck[] = [
  wgl010,
  wgl011,
  wgl012,
  wgl013,
  wgl014,
  wgl015,
  wgl016,
  wgl017,
  wgl018,
  wgl019,
  wgl020,
  wgl021,
  wgl022,
  wgl023,
  wgl024,
  wgl025,
  wgl026,
  wgl027,
  wgl028,
  wgl029,
  wgl030,
  wgl031,
  wgl032,
  wgl033,
  wgl034,
  wgl035,
  wgl036,
  wgl037,
  wgl038,
  wgl039,
  wgl040,
  wgl041,
  wgl042,
  wgl043,
  wgl044,
  wgl045,
  wgl046,
  wgl047,
  wgl048,
];
