import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { scanProject, type ProjectScan } from "./scan";

/**
 * Generate a _.d.ts file content from a project scan.
 * Produces typed declarations for the barrel's $ proxy.
 */
export function generateBarrelTypes(scan: ProjectScan): string {
  const lines: string[] = [];

  lines.push("// _.d.ts (auto-generated by chant lint)");

  if (scan.lexiconPackage) {
    lines.push(`import type * as _lexicon from "${scan.lexiconPackage}";`);
  }

  lines.push("declare const _barrel: {");

  for (const exp of scan.exports) {
    let typeName: string;
    if (!exp.className) {
      typeName = "unknown";
    } else if (scan.lexiconPackage) {
      typeName = `_lexicon.${exp.className}`;
    } else {
      typeName = exp.className;
    }
    lines.push(`  ${exp.name}: ${typeName};`);
  }

  lines.push("};");
  lines.push("export declare const $: typeof _barrel;");
  lines.push("");

  return lines.join("\n");
}

/**
 * Scan a project directory and write the _.d.ts file.
 */
export function syncProject(dir: string): void {
  const scan = scanProject(dir);
  const content = generateBarrelTypes(scan);
  writeFileSync(join(dir, "_.d.ts"), content, "utf-8");
}
