# Generated by tools/largeset-gen (issue #1750). Do not edit; regenerate.
#
# Root e04, role outlier.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 6.59.0"
    }
  }
}

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true
}

module "shared" {
  source = "oci://localhost:4890/largeset/shared?tag=1.0.0"

  name   = "e04"
  prefix = "ls"

  # The outlier: one more resource than every other estate, so its plan
  # for the bump differs from the group's.
  with_queue = true
}
