/**
 * TypeScript declaration file generator — produces index.d.ts with all
 * k3s entity classes.
 */

import type { K3sParseResult } from "./parse";
import type { NamingStrategy } from "./naming";
import {
  writeResourceClass,
  type DtsProperty,
  type DtsAttribute,
} from "@intentius/chant/codegen/generate-typescript";

interface ResourceEntry {
  tsName: string;
  properties: DtsProperty[];
  attributes: DtsAttribute[];
  remap: Map<string, string>;
}

/**
 * Generate the complete .d.ts file content.
 */
export function generateTypeScriptDeclarations(
  results: K3sParseResult[],
  naming: NamingStrategy,
): string {
  const lines: string[] = [];
  lines.push("// Code generated by chant k3s generate. DO NOT EDIT.");

  const resources: ResourceEntry[] = [];

  for (const r of results) {
    const typeName = r.resource.typeName;
    const tsName = naming.resolve(typeName);
    if (!tsName) continue;

    const dtsProps: DtsProperty[] = r.resource.properties.map((p) => ({
      name: p.name,
      type: p.tsType,
      required: p.required,
      description: p.description,
    }));
    const dtsAttrs: DtsAttribute[] = r.resource.attributes.map((a) => ({
      name: a.name,
      type: a.tsType,
    }));

    resources.push({ tsName, properties: dtsProps, attributes: dtsAttrs, remap: new Map() });
  }

  resources.sort((a, b) => a.tsName.localeCompare(b.tsName));

  lines.push("");
  lines.push("// --- k3s Entity classes ---");
  for (const re of resources) {
    writeResourceClass(lines, re.tsName, re.properties, re.attributes, re.remap);
  }

  lines.push("");

  return lines.join("\n");
}
