/**
 * Slurm serializer.
 *
 * Routes entities by entityType prefix:
 *   Slurm::Conf::* → slurm.conf (primary output)
 *   Slurm::Rest::* → jobs/<name>.json (files in SerializerResult)
 *
 * slurm.conf format:
 *   - One key=value per line for Cluster global settings
 *   - One NodeName=... stanza per Node
 *   - One PartitionName=... stanza per Partition
 *   - Licenses= line aggregated from all License entities
 *
 * The Rest JSON files are the request bodies for slurmrestd endpoints.
 */

import type { Declarable } from "@intentius/chant/declarable";
import type { Serializer, SerializerResult } from "@intentius/chant/serializer";

// ── Helpers ────────────────────────────────────────────────────────

function getProps(entity: Declarable): Record<string, unknown> {
  if ("props" in entity && typeof entity.props === "object" && entity.props !== null) {
    return entity.props as Record<string, unknown>;
  }
  return {};
}

function entityType(entity: Declarable): string {
  return (entity as Record<string, unknown>).entityType as string;
}

// ── slurm.conf emission ────────────────────────────────────────────

/**
 * Emit the slurm.conf global settings from a Cluster entity.
 * All props are emitted as KEY=value lines, skipping undefined/null.
 */
function emitCluster(props: Record<string, unknown>): string[] {
  const lines: string[] = [];
  // Emit ClusterName and ControlMachine first
  const first = ["ClusterName", "ControlMachine"];
  for (const key of first) {
    if (props[key] !== undefined && props[key] !== null) {
      lines.push(`${key}=${props[key]}`);
    }
  }
  // Emit remaining props in insertion order
  for (const [key, value] of Object.entries(props)) {
    if (first.includes(key)) continue;
    if (value === undefined || value === null) continue;
    lines.push(`${key}=${value}`);
  }
  return lines;
}

/**
 * Emit a NodeName= stanza line from a Node entity.
 */
function emitNode(props: Record<string, unknown>): string {
  const parts: string[] = [];
  // NodeName must come first
  if (props.NodeName !== undefined) {
    parts.push(`NodeName=${props.NodeName}`);
  }
  for (const [key, value] of Object.entries(props)) {
    if (key === "NodeName" || value === undefined || value === null) continue;
    parts.push(`${key}=${value}`);
  }
  return parts.join(" ");
}

/**
 * Emit a PartitionName= stanza line from a Partition entity.
 */
function emitPartition(props: Record<string, unknown>): string {
  const parts: string[] = [];
  if (props.PartitionName !== undefined) {
    parts.push(`PartitionName=${props.PartitionName}`);
  }
  for (const [key, value] of Object.entries(props)) {
    if (key === "PartitionName" || value === undefined || value === null) continue;
    parts.push(`${key}=${value}`);
  }
  return parts.join(" ");
}

/**
 * Aggregate all License entities into a single Licenses= line.
 * Slurm expects: Licenses=name1:count1,name2:count2
 */
function aggregateLicenses(licenses: Array<Record<string, unknown>>): string | null {
  if (licenses.length === 0) return null;
  const entries = licenses
    .map((p) => `${p.LicenseName}:${p.Count}`)
    .join(",");
  return `Licenses=${entries}`;
}

/**
 * Emit a gres.conf line from a GresNode entity.
 */
function emitGresNode(props: Record<string, unknown>): string {
  const parts: string[] = [];
  if (props.NodeName !== undefined) parts.push(`NodeName=${props.NodeName}`);
  if (props.Name !== undefined) parts.push(`Name=${props.Name}`);
  if (props.Type !== undefined) parts.push(`Type=${props.Type}`);
  if (props.File !== undefined) parts.push(`File=${props.File}`);
  if (props.Count !== undefined) parts.push(`Count=${props.Count}`);
  if (props.AutoDetect !== undefined) parts.push(`AutoDetect=${props.AutoDetect}`);
  if (props.Cores !== undefined) parts.push(`Cores=${props.Cores}`);
  if (props.Links !== undefined) parts.push(`Links=${props.Links}`);
  return parts.join(" ");
}

/**
 * Build the cgroup.conf content from all CgroupConf entities.
 * Booleans are emitted as lowercase true/false.
 */
function serializeCgroupConf(entities: Map<string, unknown>): string {
  const lines: string[] = [
    "# cgroup.conf — generated by chant. DO NOT EDIT directly.",
    "# Source of truth: the chant TypeScript project.",
    "",
  ];
  for (const [, entity] of entities) {
    const props = getProps(entity as Declarable);
    for (const [key, value] of Object.entries(props)) {
      if (value === undefined || value === null) continue;
      if (typeof value === "boolean") {
        lines.push(`${key}=${value}`);
      } else {
        lines.push(`${key}=${value}`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

/**
 * Build the topology.conf content from all Switch entities.
 * SwitchName is emitted first in each stanza.
 */
function serializeTopologyConf(entities: Map<string, unknown>): string {
  const lines: string[] = [
    "# topology.conf — generated by chant. DO NOT EDIT directly.",
    "# Source of truth: the chant TypeScript project.",
    "",
  ];
  for (const [, entity] of entities) {
    const props = getProps(entity as Declarable);
    const parts: string[] = [];
    if (props.SwitchName !== undefined) parts.push(`SwitchName=${props.SwitchName}`);
    if (props.Nodes !== undefined) parts.push(`Nodes=${props.Nodes}`);
    if (props.Switches !== undefined) parts.push(`Switches=${props.Switches}`);
    if (props.LinkSpeed !== undefined) parts.push(`LinkSpeed=${props.LinkSpeed}`);
    lines.push(parts.join(" "));
  }
  return lines.join("\n") + "\n";
}

/**
 * Build the slurm.conf content from all Slurm::Conf::* entities.
 */
function serializeSlurmConf(entities: Map<string, Declarable>): string {
  const lines: string[] = [
    "# slurm.conf — generated by chant. DO NOT EDIT directly.",
    "# Source of truth: the chant TypeScript project.",
    "",
  ];

  const licenseProps: Array<Record<string, unknown>> = [];

  for (const [, entity] of entities) {
    const et = entityType(entity);
    if (!et.startsWith("Slurm::Conf::")) continue;

    const props = getProps(entity);

    if (et === "Slurm::Conf::Cluster") {
      // Check for Licenses in Cluster props — if present, extract and handle separately
      const clusterProps = { ...props };
      const inlineLicenses = clusterProps.Licenses as string | undefined;
      delete clusterProps.Licenses;

      const clusterLines = emitCluster(clusterProps);
      lines.push(...clusterLines);

      // Inline Licenses= from Cluster props takes precedence
      if (inlineLicenses) {
        lines.push(`Licenses=${inlineLicenses}`);
      }

    } else if (et === "Slurm::Conf::Node") {
      lines.push(emitNode(props));

    } else if (et === "Slurm::Conf::Partition") {
      lines.push(emitPartition(props));

    } else if (et === "Slurm::Conf::License") {
      licenseProps.push(props);
    }
    // Slurm::Conf::GresNode is routed to gres.conf — excluded here
  }

  // Emit aggregated Licenses= if License entities present
  const licenseLine = aggregateLicenses(licenseProps);
  if (licenseLine) {
    lines.push("");
    lines.push(licenseLine);
  }

  return lines.join("\n") + "\n";
}

// ── REST JSON emission ─────────────────────────────────────────────

/**
 * Serialize a Slurm::Rest::* entity to its REST API JSON body.
 */
function serializeRestEntity(props: Record<string, unknown>): string {
  // Clean undefined values
  const cleaned: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined && value !== null) {
      cleaned[key] = value;
    }
  }
  return JSON.stringify(cleaned, null, 2);
}

// ── Serializer ─────────────────────────────────────────────────────

export const slurmSerializer: Serializer = {
  name: "slurm",
  rulePrefix: "SLR",

  serialize(
    entities: Map<string, Declarable>,
    _outputs?: unknown,
  ): string | SerializerResult {
    // Separate entities by type
    const confEntities = new Map<string, Declarable>();
    const restEntities = new Map<string, Declarable>();
    const gresNodeEntities = new Map<string, Declarable>();
    const cgroupConfEntities = new Map<string, Declarable>();
    const switchEntities = new Map<string, Declarable>();

    for (const [name, entity] of entities) {
      const et = entityType(entity);
      if (et === "Slurm::Conf::GresNode") {
        gresNodeEntities.set(name, entity);
      } else if (et === "Slurm::Conf::CgroupConf") {
        cgroupConfEntities.set(name, entity);
      } else if (et === "Slurm::Conf::Switch") {
        switchEntities.set(name, entity);
      } else if (et.startsWith("Slurm::Conf::")) {
        confEntities.set(name, entity);
      } else if (et.startsWith("Slurm::Rest::")) {
        restEntities.set(name, entity);
      }
    }

    const primary = serializeSlurmConf(confEntities);

    if (
      restEntities.size === 0 &&
      gresNodeEntities.size === 0 &&
      cgroupConfEntities.size === 0 &&
      switchEntities.size === 0
    ) {
      return primary;
    }

    const files: Record<string, string> = {};

    // Emit each REST entity as a separate JSON file under jobs/
    for (const [name, entity] of restEntities) {
      const props = getProps(entity);
      const et = entityType(entity);

      // Choose subdirectory by resource type
      let subdir: string;
      if (et === "Slurm::Rest::Job") {
        subdir = "jobs";
      } else if (et === "Slurm::Rest::Reservation") {
        subdir = "reservations";
      } else if (et === "Slurm::Rest::QoS") {
        subdir = "qos";
      } else {
        subdir = "rest";
      }

      files[`${subdir}/${name}.json`] = serializeRestEntity(props);
    }

    // Emit gres.conf when GresNode entities are present
    if (gresNodeEntities.size > 0) {
      const gresLines = [
        "# gres.conf — generated by chant. DO NOT EDIT directly.",
        "# Source of truth: the chant TypeScript project.",
        "",
      ];
      for (const [, entity] of gresNodeEntities) {
        gresLines.push(emitGresNode(getProps(entity)));
      }
      files["gres.conf"] = gresLines.join("\n") + "\n";
    }

    // Emit cgroup.conf when CgroupConf entities are present
    if (cgroupConfEntities.size > 0) {
      files["cgroup.conf"] = serializeCgroupConf(cgroupConfEntities as Map<string, unknown>);
    }

    // Emit topology.conf when Switch entities are present
    if (switchEntities.size > 0) {
      files["topology.conf"] = serializeTopologyConf(switchEntities as Map<string, unknown>);
    }

    return { primary, files };
  },
};
