/**
 * Generation for the augur lexicon: there is nothing to generate.
 *
 * Every lexicon that models a substrate fetches one upstream schema and emits
 * typed resource classes from it. augur models no substrate. Its subject is the
 * request a behaviour engine is handed, and that shape is this repository's own
 * (`../request.ts`) — there is no registry to fetch, no version to pin, and no
 * vendor whose schema this would track. The one resource it declares, `Profile`,
 * is two properties written by hand in `../resources.ts` and does not become
 * truer for having been emitted by a pipeline.
 *
 * So `core`'s `generatePipeline` is not called at all, and this returns the
 * empty result the packaging pipeline needs to assemble a bundle. The registry
 * is still written, empty, because `../validate.ts` reads it and
 * `writeBundleSpec` derives `dist/meta.json` from it. An empty registry is the
 * honest statement that this lexicon exports no generated resource classes —
 * the same statement `lexicons/terraform/src/codegen/generate.ts` makes, for a
 * different reason.
 */

import { writeGeneratedArtifacts } from "@intentius/chant/codegen/generate";
import type { GenerateResult } from "@intentius/chant/codegen/generate";
import { dirname } from "path";
import { fileURLToPath } from "url";

/** Filename of the generated registry, read back by `../validate.ts`. */
export const LEXICON_JSON_FILENAME = "lexicon-augur.json";

const EMPTY_INDEX_TS = `// Code generated by chant generate. DO NOT EDIT.
// The augur lexicon models no upstream schema, so there are no resource
// classes to generate. Its one resource is hand-written in src/resources.ts.
// See src/codegen/generate.ts.
export {};
`;

const EMPTY_TYPES_DTS = `// Code generated by chant generate. DO NOT EDIT.
export {};
`;

export async function generate(options?: { verbose?: boolean; force?: boolean }): Promise<GenerateResult> {
  const result: GenerateResult = {
    lexiconJSON: `${JSON.stringify({}, null, 2)}\n`,
    typesDTS: EMPTY_TYPES_DTS,
    indexTS: EMPTY_INDEX_TS,
    resources: 0,
    properties: 0,
    enums: 0,
    warnings: [],
  };

  if (options?.verbose) {
    console.error("augur generates no types: the engine's request shape is chant's own, not an upstream schema");
  }

  return result;
}

/** Write generated files to the package directory. */
export function writeGeneratedFiles(result: GenerateResult, pkgDir?: string): void {
  // This file lives in src/codegen/, so the package root is three levels up.
  const dir = pkgDir ?? dirname(dirname(dirname(fileURLToPath(import.meta.url))));
  writeGeneratedArtifacts({
    baseDir: dir,
    files: {
      [LEXICON_JSON_FILENAME]: result.lexiconJSON,
      "index.d.ts": result.typesDTS,
      "index.ts": result.indexTS,
    },
  });
}
