import { describe, test, expect } from "vitest";
import { flywaySerializer } from "./serializer";
import { FlywayProject, FlywayConfig, Environment, FlywayDesktopConfig, RedgateCompareConfig } from "./generated/index";

describe("flywaySerializer", () => {
  test("has correct name and prefix", () => {
    expect(flywaySerializer.name).toBe("flyway");
    expect(flywaySerializer.rulePrefix).toBe("WFW");
  });

  test("serializes empty project", () => {
    const entities = new Map<string, any>();
    const result = flywaySerializer.serialize(entities);
    expect(typeof result).toBe("string");
  });

  test("serializes FlywayProject at root level", () => {
    const project = new FlywayProject({
      id: "test-project",
      name: "test-project",
      databaseType: "postgresql",
    });

    const entities = new Map<string, any>([["project", project]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain('id = "test-project"');
    expect(result).toContain('name = "test-project"');
    // databaseType is chant-internal metadata, not emitted to TOML
    expect(result).not.toContain("databaseType");
  });

  test("serializes FlywayConfig under [flyway]", () => {
    const config = new FlywayConfig({
      locations: ["filesystem:sql/migrations"],
      defaultSchema: "public",
      encoding: "UTF-8",
      validateMigrationNaming: true,
      cleanDisabled: true,
    });

    const entities = new Map<string, any>([["config", config]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[flyway]");
    expect(result).toContain('locations = ["filesystem:sql/migrations"]');
    expect(result).toContain('defaultSchema = "public"');
    expect(result).toContain("validateMigrationNaming = true");
    expect(result).toContain("cleanDisabled = true");
  });

  test("serializes Environment under [environments.<name>]", () => {
    const dev = new Environment({
      url: "jdbc:postgresql://localhost:5432/devdb",
      user: "dev_user",
      schemas: ["public"],
      displayName: "dev",
    });

    const entities = new Map<string, any>([["dev", dev]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[environments.dev]");
    expect(result).toContain('url = "jdbc:postgresql://localhost:5432/devdb"');
    expect(result).toContain('user = "dev_user"');
    expect(result).toContain('schemas = ["public"]');
  });

  test("serializes multiple environments", () => {
    const dev = new Environment({
      url: "jdbc:postgresql://localhost:5432/devdb",
      user: "dev_user",
      schemas: ["public"],
      displayName: "dev",
    });
    const prod = new Environment({
      url: "jdbc:postgresql://prod-host:5432/proddb",
      user: "prod_user",
      schemas: ["public", "audit"],
      displayName: "prod",
    });

    const entities = new Map<string, any>([
      ["dev", dev],
      ["prod", prod],
    ]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[environments.dev]");
    expect(result).toContain("[environments.prod]");
    expect(result).toContain('schemas = ["public", "audit"]');
  });

  test("serializes complete project", () => {
    const project = new FlywayProject({
      id: "my-app",
      name: "my-app",
      databaseType: "postgresql",
    });
    const config = new FlywayConfig({
      locations: ["filesystem:sql"],
      defaultSchema: "public",
      cleanDisabled: true,
    });
    const dev = new Environment({
      url: "jdbc:postgresql://localhost:5432/db",
      user: "admin",
      schemas: ["public"],
      displayName: "dev",
    });

    const entities = new Map<string, any>([
      ["project", project],
      ["config", config],
      ["dev", dev],
    ]);
    const result = flywaySerializer.serialize(entities) as string;

    // Should have header
    expect(result).toContain("# Generated by Chant");

    // Should have all sections
    expect(result).toContain('id = "my-app"');
    expect(result).toContain("[flyway]");
    expect(result).toContain("[environments.dev]");
  });

  test("serializes placeholders under [flyway.placeholders]", () => {
    const config = new FlywayConfig({
      locations: ["filesystem:sql"],
      placeholders: {
        appName: "myapp",
        schema: "public",
      },
    });

    const entities = new Map<string, any>([["config", config]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[flyway.placeholders]");
    expect(result).toContain('appName = "myapp"');
    expect(result).toContain('schema = "public"');
  });

  test("serializes FlywayDesktopConfig under [flywayDesktop]", () => {
    const desktop = new FlywayDesktopConfig({
      developmentEnvironment: "development",
      shadowEnvironment: "shadow",
    });

    const entities = new Map<string, any>([["desktop", desktop]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[flywayDesktop]");
    expect(result).toContain('developmentEnvironment = "development"');
    expect(result).toContain('shadowEnvironment = "shadow"');
  });

  test("serializes RedgateCompareConfig under [redgateCompare]", () => {
    const compare = new RedgateCompareConfig({
      filterFile: "./Filter.scpf",
    });

    const entities = new Map<string, any>([["compare", compare]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[redgateCompare]");
    expect(result).toContain('filterFile = "./Filter.scpf"');
  });

  test("serializes FlywayDesktopConfig with generate sub-object", () => {
    const desktop = new FlywayDesktopConfig({
      developmentEnvironment: "development",
      shadowEnvironment: "shadow",
      generate: { undoScripts: true },
    });

    const entities = new Map<string, any>([["desktop", desktop]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[flywayDesktop]");
    expect(result).toContain("[flywayDesktop.generate]");
    expect(result).toContain("undoScripts = true");
  });

  test("serializes per-environment flyway overrides under [environments.*.flyway]", () => {
    const dev = new Environment({
      url: "jdbc:postgresql://localhost:5432/dev",
      schemas: ["public"],
      displayName: "dev",
      flyway: {
        cleanDisabled: false,
        locations: ["filesystem:sql"],
      },
    });

    const entities = new Map<string, any>([["dev", dev]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[environments.dev]");
    expect(result).toContain("[environments.dev.flyway]");
    expect(result).toContain("cleanDisabled = false");
    expect(result).toContain('locations = ["filesystem:sql"]');
  });

  test("serializes per-environment flyway placeholders under [environments.*.flyway.placeholders]", () => {
    const prod = new Environment({
      url: "jdbc:postgresql://prod:5432/db",
      schemas: ["public"],
      displayName: "prod",
      flyway: {
        validateOnMigrate: true,
        placeholders: {
          appName: "myapp",
          logLevel: "warn",
        },
      },
    });

    const entities = new Map<string, any>([["prod", prod]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain("[environments.prod]");
    expect(result).toContain("[environments.prod.flyway]");
    expect(result).toContain("validateOnMigrate = true");
    expect(result).toContain("[environments.prod.flyway.placeholders]");
    expect(result).toContain('appName = "myapp"');
    expect(result).toContain('logLevel = "warn"');
  });

  test("serializes complete Desktop project with all sections", () => {
    const project = new FlywayProject({
      id: "desktop-app",
      name: "desktop-app",
      databaseType: "postgresql",
    });
    const config = new FlywayConfig({
      locations: ["filesystem:migrations"],
      schemaModelLocation: "./schema-model",
    });
    const dev = new Environment({
      url: "jdbc:postgresql://localhost:5432/devdb",
      schemas: ["public"],
      displayName: "development",
    });
    const shadow = new Environment({
      url: "jdbc:postgresql://localhost:5432/shadowdb",
      schemas: ["public"],
      provisioner: "clean",
      displayName: "shadow",
    });
    const desktop = new FlywayDesktopConfig({
      developmentEnvironment: "development",
      shadowEnvironment: "shadow",
    });

    const entities = new Map<string, any>([
      ["project", project],
      ["config", config],
      ["dev", dev],
      ["shadow", shadow],
      ["desktop", desktop],
    ]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain('id = "desktop-app"');
    expect(result).toContain("[flyway]");
    expect(result).toContain("[environments.development]");
    expect(result).toContain("[environments.shadow]");
    expect(result).toContain('provisioner = "clean"');
    expect(result).toContain("[flywayDesktop]");
    expect(result).toContain('developmentEnvironment = "development"');
    expect(result).toContain('shadowEnvironment = "shadow"');
  });

  test("serializes resolver references as strings", () => {
    const dev = new Environment({
      url: "jdbc:postgresql://localhost:5432/db",
      user: "admin",
      password: "${vault.password}",
      schemas: ["public"],
      displayName: "dev",
    });

    const entities = new Map<string, any>([["dev", dev]]);
    const result = flywaySerializer.serialize(entities) as string;

    expect(result).toContain('password = "${vault.password}"');
  });
});
