/**
 * Flyway generation pipeline.
 *
 * Unlike AWS/K8s/GitLab which fetch upstream schemas, Flyway types are
 * hand-authored. The generate step validates the hand-authored definitions
 * and writes generated artifacts.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const pkgDir = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

export interface FlywayGenerateResult {
  resources: number;
  properties: number;
  warnings: Array<{ file: string; error: string }>;
}

/**
 * Run the Flyway generation pipeline.
 *
 * Since Flyway types are hand-authored, this validates the
 * lexicon JSON and index files exist and are consistent.
 */
export async function generate(opts?: { verbose?: boolean }): Promise<FlywayGenerateResult> {
  const generatedDir = join(pkgDir, "src", "generated");
  const warnings: Array<{ file: string; error: string }> = [];

  // Read and validate the lexicon JSON
  let lexiconJSON: Record<string, unknown>;
  try {
    const content = readFileSync(join(generatedDir, "lexicon-flyway.json"), "utf-8");
    lexiconJSON = JSON.parse(content);
  } catch (e) {
    throw new Error(`Failed to read lexicon-flyway.json: ${e}`);
  }

  // Count resources and properties
  let resources = 0;
  let properties = 0;
  for (const entry of Object.values(lexiconJSON)) {
    const e = entry as Record<string, unknown>;
    if (e.kind === "resource") resources++;
    else if (e.kind === "property") properties++;
  }

  // Generate a minimal index.d.ts from the hand-authored index.ts exports
  const indexTS = readFileSync(join(generatedDir, "index.ts"), "utf-8");
  const exportNames = [...indexTS.matchAll(/^export const (\w+)/gm)].map(m => m[1]);
  const dtsLines = [
    "// Generated by chant flyway generate. DO NOT EDIT.",
    "",
    ...exportNames.map(name => `export declare const ${name}: any;`),
    "",
  ];
  writeFileSync(join(generatedDir, "index.d.ts"), dtsLines.join("\n"));

  if (opts?.verbose) {
    console.error(`Flyway lexicon: ${resources} resources, ${properties} property types`);
  }

  return { resources, properties, warnings };
}
