/**
 * Flyway generation pipeline.
 *
 * Unlike AWS/K8s/GitLab which fetch upstream schemas, Flyway types are
 * hand-authored. The generate step validates the hand-authored definitions
 * and writes generated artifacts.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { writeResourceClass, writePropertyClass, writeEnumType } from "@intentius/chant/codegen/generate-typescript";
import { PROPERTIES_BY_CLASS } from "../properties";
import { DatabaseType } from "../variables";

const pkgDir = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

export interface FlywayGenerateResult {
  resources: number;
  properties: number;
  warnings: Array<{ file: string; error: string }>;
}

/**
 * Run the Flyway generation pipeline.
 *
 * Since Flyway types are hand-authored, this validates the
 * lexicon JSON and index files exist and are consistent.
 */
export async function generate(opts?: { verbose?: boolean }): Promise<FlywayGenerateResult> {
  const generatedDir = join(pkgDir, "src", "generated");
  const warnings: Array<{ file: string; error: string }> = [];

  // Read and validate the lexicon JSON
  let lexiconJSON: Record<string, { resourceType: string; kind: string; attrs?: Record<string, string> }>;
  try {
    const content = readFileSync(join(generatedDir, "lexicon-flyway.json"), "utf-8");
    lexiconJSON = JSON.parse(content);
  } catch (e) {
    throw new Error(`Failed to read lexicon-flyway.json: ${e}`);
  }

  // Count resources and properties
  let resources = 0;
  let properties = 0;
  for (const entry of Object.values(lexiconJSON)) {
    if (entry.kind === "resource") resources++;
    else if (entry.kind === "property") properties++;
  }

  // Type remap table for Flyway-specific types
  const remap = new Map<string, string>([
    ["DatabaseTypeValue", "DatabaseTypeValue"],
    ["EnvironmentFlyway", "EnvironmentFlyway"],
    ["Record<string, string>", "Record<string, string>"],
    ["Record<string, unknown>", "Record<string, unknown>"],
  ]);

  // Generate a typed index.d.ts from property definitions and lexicon JSON
  const lines: string[] = [
    "// Generated by chant flyway generate. DO NOT EDIT.",
  ];

  // Write DatabaseTypeValue enum type
  writeEnumType(lines, "DatabaseTypeValue", Object.values(DatabaseType));

  // Read index.ts to get the export order
  const indexTS = readFileSync(join(generatedDir, "index.ts"), "utf-8");
  const exportNames = [...indexTS.matchAll(/^export const (\w+)/gm)].map(m => m[1]);

  for (const tsName of exportNames) {
    const entry = lexiconJSON[tsName];
    if (!entry) {
      warnings.push({ file: "index.ts", error: `Export "${tsName}" not found in lexicon-flyway.json` });
      continue;
    }

    const props = PROPERTIES_BY_CLASS[tsName] ?? [];

    if (entry.kind === "resource") {
      const attrs = entry.attrs
        ? Object.entries(entry.attrs).map(([attrName, attrType]) => ({ name: attrName, type: attrType === "name" ? "string" : attrType }))
        : [];
      writeResourceClass(lines, tsName, props, attrs, remap);
    } else {
      writePropertyClass(lines, tsName, props, remap);
    }
  }

  lines.push("");
  writeFileSync(join(generatedDir, "index.d.ts"), lines.join("\n"));

  if (opts?.verbose) {
    console.error(`Flyway lexicon: ${resources} resources, ${properties} property types`);
  }

  return { resources, properties, warnings };
}
