// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { prom101 } from "./prom101";
import { prom102 } from "./prom102";
import { prom103 } from "./prom103";
import { prom104 } from "./prom104";
import { prom105 } from "./prom105";
import { prom106 } from "./prom106";
import { prom107 } from "./prom107";
import { prom201 } from "./prom201";
import { prom202 } from "./prom202";
import { prom203 } from "./prom203";
import { prom204 } from "./prom204";
import { prom205 } from "./prom205";
import { prom206 } from "./prom206";
import { prom207 } from "./prom207";
import { prom208 } from "./prom208";
import { prom209 } from "./prom209";
import { prom210 } from "./prom210";

export const postSynthChecks: PostSynthCheck[] = [
  prom101,
  prom102,
  prom103,
  prom104,
  prom105,
  prom106,
  prom107,
  prom201,
  prom202,
  prom203,
  prom204,
  prom205,
  prom206,
  prom207,
  prom208,
  prom209,
  prom210,
];
