// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { prom101 } from "./prom101";
import { prom102 } from "./prom102";
import { prom103 } from "./prom103";
import { prom104 } from "./prom104";
import { prom105 } from "./prom105";
import { prom106 } from "./prom106";
import { prom107 } from "./prom107";
import { prom201 } from "./prom201";
import { prom202 } from "./prom202";
import { prom203 } from "./prom203";
import { prom204 } from "./prom204";
import { prom205 } from "./prom205";
import { prom206 } from "./prom206";
import { prom207 } from "./prom207";
import { prom208 } from "./prom208";
import { prom209 } from "./prom209";
import { prom210 } from "./prom210";
import { prom211 } from "./prom211";
import { prom212 } from "./prom212";
import { prom213 } from "./prom213";
import { prom214 } from "./prom214";
import { prom215 } from "./prom215";
import { prom216 } from "./prom216";
import { prom217 } from "./prom217";
import { prom218 } from "./prom218";
import { prom219 } from "./prom219";
import { prom220 } from "./prom220";
import { prom221 } from "./prom221";
import { prom222 } from "./prom222";
import { prom223 } from "./prom223";
import { prom224 } from "./prom224";
import { prom301 } from "./prom301";

export const postSynthChecks: PostSynthCheck[] = [
  prom101,
  prom102,
  prom103,
  prom104,
  prom105,
  prom106,
  prom107,
  prom201,
  prom202,
  prom203,
  prom204,
  prom205,
  prom206,
  prom207,
  prom208,
  prom209,
  prom210,
  prom211,
  prom212,
  prom213,
  prom214,
  prom215,
  prom216,
  prom217,
  prom218,
  prom219,
  prom220,
  prom221,
  prom222,
  prom223,
  prom224,
  prom301,
];
