/**
 * Affected Terragrunt units (#3415) on the `affected/` fixture, with
 * Terragrunt's own selection taken from `../__fixtures__/terragrunt/affected-cases.ts`
 * and discovery from `recorded/affected-find.json` (Terragrunt 1.1.6, stacks
 * generated). Nothing here runs Terragrunt; `affected.acceptance.test.ts` does.
 */

import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, it } from "vitest";
import { AFFECTED_CASES } from "../__fixtures__/terragrunt/affected-cases";
import {
  describeTerragruntAffectedReason,
  findTerragruntAffected,
  parseTerragruntFind,
  readTerragruntStackFile,
  terragruntAffected,
  terragruntAffectedDiffArgs,
  terragruntAffectedFindArgs,
  terragruntModuleDirs,
  type TerragruntExec,
} from "./index";

const fixtures = join(dirname(fileURLToPath(import.meta.url)), "../__fixtures__/terragrunt");
const discovered = parseTerragruntFind(readFileSync(join(fixtures, "recorded/affected-find.json"), "utf8"));

const tmps: string[] = [];
afterAll(() => {
  for (const t of tmps) rmSync(t, { recursive: true, force: true });
});
function copyFixture(): string {
  const dir = join(mkdtempSync(join(tmpdir(), "chant-tg-affected-")), "repo");
  tmps.push(dirname(dir));
  cpSync(join(fixtures, "affected"), dir, { recursive: true });
  renameSync(join(dir, "gitignore"), join(dir, ".gitignore"));
  return dir;
}

describe("affected units, table-driven", () => {
  for (const c of AFFECTED_CASES) {
    it(c.name, () => {
      const dir = copyFixture();
      c.change(dir);
      // Discovery at head: a unit whose terragrunt.hcl is gone is not listed; generated units are.
      const units = discovered.filter((u) => u.path.includes("/.terragrunt-stack/") || existsSync(join(dir, u.path, "terragrunt.hcl")));
      const got = terragruntAffected({ dir, units, terragruntSelected: c.terragrunt, changedFiles: c.changed });
      expect(got.units).toEqual(c.expected);
      expect(got.notes).toEqual([]);
    });
  }

  it("each supplement selects a unit Terragrunt's own range does not", () => {
    for (const name of ["supplement 1", "supplement 2", "supplement 3"]) {
      const c = AFFECTED_CASES.find((x) => x.name.startsWith(name))!;
      expect(c.terragrunt).toEqual([]);
      expect(c.expected.length).toBeGreaterThan(0);
    }
  });
});

describe("affected units, edges", () => {
  it("notes a unit Terragrunt selected that discovery left out, and keeps it out", () => {
    const dir = copyFixture();
    const units = discovered.filter((u) => u.path !== "live/dev/vpc");
    const got = terragruntAffected({ dir, units, terragruntSelected: ["live/dev/vpc"], changedFiles: ["live/dev/vpc/terragrunt.hcl"] });
    expect(got.units).toEqual([]);
    expect(got.notes).toEqual(["live/dev/vpc: Terragrunt's git range selected it, but discovery left it out, so it is not affected here"]);
  });

  it("notes a changed template whose units are not generated yet", () => {
    const dir = copyFixture();
    const units = discovered.filter((u) => !u.path.includes("/.terragrunt-stack/"));
    const got = terragruntAffected({ dir, units, terragruntSelected: [], changedFiles: ["catalog/units/web/terragrunt.hcl"] });
    expect(got.units).toEqual([]);
    expect(got.notes).toEqual([
      'live/stg/.terragrunt-stack/web: generated by unit "web" in live/stg/terragrunt.stack.hcl from the changed template catalog/units/web, but discovery did not list it; run `terragrunt stack generate` before discovery',
    ]);
  });

  it("a stack template selects every unit generated under it", () => {
    const dir = copyFixture();
    mkdirSync(join(dir, "live/qa"));
    writeFileSync(join(dir, "live/qa/terragrunt.stack.hcl"), 'stack "svc" {\n  source = "../../catalog/stacks/svc"\n  path = "svc"\n}\n');
    const units = [
      { path: "live/qa/.terragrunt-stack/svc/.terragrunt-stack/web", dependencies: [] },
      { path: "live/qa/.terragrunt-stack/svc/.terragrunt-stack/db", dependencies: [] },
      { path: "live/dev/vpc", dependencies: [] },
    ];
    const got = terragruntAffected({ dir, units, terragruntSelected: [], changedFiles: ["catalog/stacks/svc/terragrunt.stack.hcl"] });
    expect(got.units.map((u) => [u.path, u.reasons.map((r) => `${r.kind} via ${r.via}`)])).toEqual([
      ["live/qa/.terragrunt-stack/svc/.terragrunt-stack/db", ["stack-template via catalog/stacks/svc"]],
      ["live/qa/.terragrunt-stack/svc/.terragrunt-stack/web", ["stack-template via catalog/stacks/svc"]],
    ]);
  });

  it("module directories come from the .tf files Terragrunt reports reading, outside the unit", () => {
    expect(terragruntModuleDirs({ path: "live/a", dependencies: [], reading: ["root.hcl", "live/a/local.tf", "modules/x/main.tf", "modules/x/vars.tofu", "_envcommon/a.hcl"] })).toEqual([
      "modules/x",
    ]);
    expect(terragruntModuleDirs({ path: "live/a", dependencies: [] })).toEqual([]);
  });
});

describe("stack files", () => {
  it("reads unit and stack blocks, their local templates and where they generate", () => {
    const text = [
      'unit "web" {',
      '  source = "../../catalog/units/web"',
      '  path   = "web"',
      '  values = { path = "ignored", source = "ignored" }',
      "}",
      'unit "flat" {',
      '  source = "${get_terragrunt_dir()}/../../catalog/units/flat"',
      '  path = "flat"',
      "  no_dot_terragrunt_stack = true",
      "}",
      'unit "remote" {',
      '  source = "git::https://example.com/catalog.git//units/web?ref=v1.2.0"',
      '  path = "remote"',
      "}",
      'stack "svc" {',
      '  source = "../../catalog//stacks/svc"',
      '  path = "svc"',
      "}",
    ].join("\n");
    expect(readTerragruntStackFile("/repo", "live/stg/terragrunt.stack.hcl", text)).toEqual([
      { type: "unit", name: "web", template: "catalog/units/web", generated: "live/stg/.terragrunt-stack/web" },
      { type: "unit", name: "flat", template: "catalog/units/flat", generated: "live/stg/flat" },
      { type: "unit", name: "remote", generated: "live/stg/.terragrunt-stack/remote" },
      { type: "stack", name: "svc", template: "catalog/stacks/svc", generated: "live/stg/.terragrunt-stack/svc" },
    ]);
  });
});

describe("the affected runner", () => {
  it("asks Terragrunt for the range with no filters file and the discovery excludes", () => {
    expect(terragruntAffectedFindArgs({ base: "origin/main", exclude: ["sandbox/**"] })).toEqual([
      "find",
      "--json",
      "--no-color",
      "--no-filters-file",
      "--filter",
      "[origin/main...HEAD]",
      "--filter",
      "!./catalog/**",
      "--filter",
      "!./**/.terragrunt-cache/**",
      "--filter",
      "!./sandbox/**",
    ]);
    expect(terragruntAffectedDiffArgs({ base: "abc", head: "def" })).toEqual(["diff", "--name-only", "--no-renames", "--relative", "abc...def"]);
  });

  it("runs git and terragrunt, and joins them with discovery", async () => {
    const dir = copyFixture();
    const calls: string[] = [];
    const exec: TerragruntExec = async (file, args) => {
      calls.push(`${file} ${args[0]}`);
      if (file === "git") return { code: 0, stdout: "modules/app/policy.json\nlive/dev/vpc/terragrunt.hcl\n", stderr: "" };
      return { code: 0, stdout: JSON.stringify([{ type: "unit", path: "live/dev/vpc" }]), stderr: "" };
    };
    const got = await findTerragruntAffected({ dir, base: "main", units: discovered, exec });
    expect(calls).toEqual(["git diff", "terragrunt find"]);
    expect(got.units.map((u) => [u.path, u.reasons.map(describeTerragruntAffectedReason)])).toEqual([
      ["live/dev/app", ["modules/app/policy.json changed under its module modules/app, which Terragrunt does not track"]],
      ["live/dev/vpc", ["Terragrunt's git range selected it (live/dev/vpc/terragrunt.hcl)"]],
      ["live/prod/app", ["modules/app/policy.json changed under its module modules/app, which Terragrunt does not track"]],
    ]);
  });

  it("fails with the command when git fails", async () => {
    const exec: TerragruntExec = async () => ({ code: 128, stdout: "", stderr: "fatal: bad revision 'nope...HEAD'" });
    await expect(findTerragruntAffected({ dir: "/nowhere", base: "nope", units: [], exec })).rejects.toThrow(/git diff .* failed \(exit 128\): fatal: bad revision/);
  });
});
