// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { fly010 } from "./fly010-machine-requires-image";

export const postSynthChecks: PostSynthCheck[] = [
  fly010,
];
