// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { ren010 } from "./ren010-native-runtime-requires-commands";
import { ren011 } from "./ren011-service-requires-source";
import { ren012 } from "./ren012-free-plan-cannot-scale";

export const postSynthChecks: PostSynthCheck[] = [
  ren010,
  ren011,
  ren012,
];
