# GCP Config Connector lexicon

generate:
    bun run src/codegen/generate-cli.ts

bundle:
    bun run src/package-cli.ts

validate:
    bun run src/validate-cli.ts

docs:
    bun run src/codegen/docs-cli.ts

test:
    bun test

prepack: generate bundle validate
