import { SecretManagerSecret, SecretManagerSecretVersion } from "@intentius/chant-lexicon-gcp";
import { cells, shared } from "../config";

const SECRET_KEYS = ["db-password", "redis-password", "redis-cache-password", "root-password", "rails-secret"];

// Per-cell Secret Manager secrets — flat arrays so chant discovery can find them.
export const cellSecrets = cells.flatMap(c =>
  SECRET_KEYS.map(key => new SecretManagerSecret({
    metadata: { name: `gitlab-${c.name}-${key}` },
    replication: { automatic: true },
  }))
);

export const cellSecretVersions = cells.flatMap(c =>
  SECRET_KEYS.map(key => new SecretManagerSecretVersion({
    metadata: { name: `gitlab-${c.name}-${key}-v1` },
    secretRef: { name: `gitlab-${c.name}-${key}` },
    secretData: { value: "PLACEHOLDER" },
  }))
);

// Shared SMTP secret
export const smtpSecret = new SecretManagerSecret({
  metadata: { name: "gitlab-smtp-password" },
  replication: { automatic: true },
});

// Topology service DB password — generated by load-outputs.sh and uploaded to Secret Manager
export const topologyDbSecret = new SecretManagerSecret({
  metadata: { name: "gitlab-topology-db-password" },
  replication: { automatic: true },
});

export const topologyDbSecretVersion = new SecretManagerSecretVersion({
  metadata: { name: "gitlab-topology-db-password-v1" },
  secretRef: { name: "gitlab-topology-db-password" },
  secretData: { value: "PLACEHOLDER" },
});

// Grafana admin password — generated by load-outputs.sh and uploaded to Secret Manager.
// ESO syncs this into K8s secret "grafana-admin" in the system namespace.
export const grafanaAdminSmSecret = new SecretManagerSecret({
  metadata: { name: "gitlab-grafana-admin-password" },
  replication: { automatic: true },
});

export const grafanaAdminSmSecretVersion = new SecretManagerSecretVersion({
  metadata: { name: "gitlab-grafana-admin-password-v1" },
  secretRef: { name: "gitlab-grafana-admin-password" },
  secretData: { value: "PLACEHOLDER" },
});
