// Generated by scripts/generate-composite-catalogs.ts (#2662) from this
// lexicon's composite exports. Do not edit by hand: run
// `npm run generate:composite-catalogs`. catalog.test.ts holds it to the exports.
import type { CompositeEntry } from "@intentius/chant/lexicon";

export const compositeCatalog: CompositeEntry[] = [
  {
    "name": "Slo",
    "lexicon": "prometheus",
    "description": "An SLO, built to recording rules and multiwindow multi-burn-rate alerts.",
    "bundles": [
      "RuleGroup"
    ],
    "params": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "The SLO's name, the `slo` label on every series and alert it builds and part of its group names."
      },
      {
        "name": "objective",
        "type": "number",
        "required": true,
        "description": "The target share of good events, strictly between 0 and 1, e.g. `0.995`."
      },
      {
        "name": "window",
        "type": "string",
        "required": true,
        "description": "The rolling window the objective holds over, a Prometheus duration, e.g. `28d` or `30d`."
      },
      {
        "name": "sli",
        "type": "SloSli",
        "required": true,
        "description": "The SLI: good (or error) events over total events, with `{{window}}` for the range."
      },
      {
        "name": "description",
        "type": "string",
        "required": false,
        "description": "A sentence for the alerts' description, e.g. what the SLO measures."
      },
      {
        "name": "alerting",
        "type": "SloAlerting",
        "required": false,
        "description": "Burn-rate alerts (default: both tiers with the Workbook's windows)."
      },
      {
        "name": "labels",
        "type": "LabelSet",
        "required": false,
        "description": "Labels added to every rule, e.g. `team` or `service`."
      },
      {
        "name": "interval",
        "type": "string",
        "required": false,
        "description": "Evaluation interval of the group (default: Prometheus's `evaluation_interval`)."
      }
    ]
  }
];
