// Code generated by chant generate. DO NOT EDIT.
import type { PostSynthCheck } from "@intentius/chant/lint/post-synth";
import { azr010 } from "./azr010";
import { azr011 } from "./azr011";
import { azr012 } from "./azr012";
import { azr013 } from "./azr013";
import { azr014 } from "./azr014";
import { azr015 } from "./azr015";
import { azr016 } from "./azr016";
import { azr017 } from "./azr017";
import { azr018 } from "./azr018";
import { azr019 } from "./azr019";
import { azr020 } from "./azr020";
import { azr021 } from "./azr021";
import { azr022 } from "./azr022";
import { azr023 } from "./azr023";
import { azr024 } from "./azr024";
import { azr025 } from "./azr025";
import { azr026 } from "./azr026";
import { azr027 } from "./azr027";
import { azr028 } from "./azr028";
import { azr029 } from "./azr029";

export const postSynthChecks: PostSynthCheck[] = [
  azr010,
  azr011,
  azr012,
  azr013,
  azr014,
  azr015,
  azr016,
  azr017,
  azr018,
  azr019,
  azr020,
  azr021,
  azr022,
  azr023,
  azr024,
  azr025,
  azr026,
  azr027,
  azr028,
  azr029,
];
