/**
 * TypeScript declaration file generator — produces index.d.ts with all
 * k3d entity classes.
 */

import type { K3dParseResult } from "./parse";
import { k3dShortName } from "./parse";
import type { NamingStrategy } from "./naming";
import { propertyTypeName, extractDefName } from "./naming";
import {
  writeResourceClass,
  writeEnumType,
  type DtsProperty,
  type DtsAttribute,
} from "@intentius/chant/codegen/generate-typescript";

interface ResourceEntry {
  tsName: string;
  properties: DtsProperty[];
  attributes: DtsAttribute[];
  remap: Map<string, string>;
}

interface EnumEntry {
  tsName: string;
  values: string[];
}

/**
 * Generate the complete .d.ts file content.
 */
export function generateTypeScriptDeclarations(
  results: K3dParseResult[],
  naming: NamingStrategy,
): string {
  const lines: string[] = [];
  lines.push("// Code generated by chant k3d generate. DO NOT EDIT.");

  const resources: ResourceEntry[] = [];
  const enums: EnumEntry[] = [];

  for (const r of results) {
    const typeName = r.resource.typeName;
    const tsName = naming.resolve(typeName);
    if (!tsName) continue;

    const shortName = k3dShortName(typeName);
    const remap = new Map<string, string>();
    for (const pt of r.propertyTypes) {
      const defName = extractDefName(pt.name, shortName);
      remap.set(pt.name, propertyTypeName(tsName, defName));
    }
    for (const e of r.enums) {
      const defName = extractDefName(e.name, shortName);
      remap.set(e.name, propertyTypeName(tsName, defName));
    }

    const dtsProps: DtsProperty[] = r.resource.properties.map((p) => ({
      name: p.name,
      type: p.tsType,
      required: p.required,
      description: p.description,
    }));
    const dtsAttrs: DtsAttribute[] = r.resource.attributes.map((a) => ({
      name: a.name,
      type: a.tsType,
    }));

    resources.push({ tsName, properties: dtsProps, attributes: dtsAttrs, remap });

    for (const alias of naming.aliases(typeName)) {
      resources.push({ tsName: alias, properties: dtsProps, attributes: dtsAttrs, remap });
    }

    for (const e of r.enums) {
      const defName = extractDefName(e.name, shortName);
      const eName = propertyTypeName(tsName, defName);
      enums.push({ tsName: eName, values: e.values });
    }
  }

  resources.sort((a, b) => a.tsName.localeCompare(b.tsName));
  enums.sort((a, b) => a.tsName.localeCompare(b.tsName));

  lines.push("");
  lines.push("// --- k3d Entity classes ---");
  for (const re of resources) {
    writeResourceClass(lines, re.tsName, re.properties, re.attributes, re.remap);
  }

  if (enums.length > 0) {
    lines.push("");
    lines.push("// --- Enum types ---");
    for (const ee of enums) {
      writeEnumType(lines, ee.tsName, ee.values);
    }
  }

  lines.push("");

  return lines.join("\n");
}
