/**
 * Cedar lexicon packaging — delegates to core's packagePipeline.
 */

import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import {
  packagePipeline,
  type PackageOptions,
  type PackageResult,
} from "@intentius/chant/codegen/package";
import type { GenerateResult } from "@intentius/chant/codegen/generate";
import { generate } from "./generate";

export type { PackageOptions, PackageResult };

const pkgDir = dirname(dirname(fileURLToPath(import.meta.url)));

/**
 * Packaging runs ahead of codegen here, deliberately.
 *
 * `dist/manifest.json` is a tier-1 requirement, and the interesting spec for
 * this lexicon is the *user's* Cedar schema rather than one global upstream —
 * so `generate()` stays a stub until #1650 decides which schema syntax is
 * canonical. Feeding the pipeline an empty registry keeps the bundle real
 * (manifest, rules, integrity, OKF) while it describes no entity types yet.
 * The throw is reported, not swallowed: once #1650 lands, generation either
 * succeeds or this path stops being taken.
 */
async function generateOrEmpty(opts: { verbose?: boolean; force?: boolean }): Promise<GenerateResult> {
  try {
    return await generate(opts);
  } catch (error) {
    if (opts.verbose) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`cedar generate() is not implemented yet (#1650) — packaging an empty registry: ${message}`);
    }
    return {
      lexiconJSON: JSON.stringify({}, null, 2),
      typesDTS: "// Generated by @intentius/chant-lexicon-cedar — no entity types yet (#1650).\nexport {};\n",
      indexTS: "export {};\n",
      resources: 0,
      properties: 0,
      enums: 0,
      warnings: [],
    };
  }
}

/**
 * Package the Cedar lexicon into a distributable BundleSpec.
 */
export async function packageLexicon(opts: PackageOptions = {}): Promise<PackageResult> {
  const pkgJson = JSON.parse(readFileSync(join(pkgDir, "..", "package.json"), "utf-8")) as {
    version?: string;
  };

  return packagePipeline(
    {
      generate: (genOpts) => generateOrEmpty(genOpts),

      buildManifest: () => ({
        name: "cedar",
        version: pkgJson.version ?? "0.0.0",
        chantVersion: ">=0.1.0",
        namespace: "Cedar",
        intrinsics: [],
        pseudoParameters: {},
      }),

      srcDir: pkgDir,

      // Skills, initTemplates and the docs site are #1654.
      collectSkills: () => new Map(),

      version: pkgJson.version ?? "0.0.0",
    },
    opts,
  );
}
