import { describe, test, expect } from "vitest";
import { renderMarkdown } from "./report";
import type { AuditFinding } from "./core";

const FINDINGS: AuditFinding[] = [
  {
    checkId: "GHA033",
    severity: "warning",
    message: "Workflow declares permissions: write-all — replace it with specific scopes.",
    file: ".github/workflows/ci.yml",
    lexicon: "github",
  },
  {
    checkId: "GHA021",
    severity: "warning",
    message: 'Job "build" uses actions/checkout@v4 — pin to a full commit SHA.',
    file: ".github/workflows/ci.yml",
    lexicon: "github",
    entity: "build",
  },
  {
    checkId: "GHA036",
    severity: "error",
    message: "Untrusted input interpolated into a run: shell command.",
    file: ".github/workflows/pr.yml",
    lexicon: "github",
    entity: "comment",
  },
  {
    checkId: "GHA022",
    severity: "info",
    message: 'Job "build" has no timeout-minutes.',
    file: ".github/workflows/ci.yml",
    lexicon: "github",
  },
];

describe("renderMarkdown", () => {
  test("renders a stable tiered report", () => {
    expect(renderMarkdown(FINDINGS, { target: "owner/repo" })).toMatchInlineSnapshot(`
      "# CI security audit

      Target: owner/repo

      4 findings — 3 merge-worthy, 1 report-only (1 error, 2 warning, 1 info).

      ## Merge-worthy findings

      ### GHA036 — Untrusted input interpolated into run: (error)

      Pass untrusted \`\${{ }}\` values via an \`env:\` var and reference \`"$VAR"\`, never inline in the script.

      Authority: [GitHub — Understanding the risk of script injections](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections)

      - \`.github/workflows/pr.yml\` (\`comment\`) — Untrusted input interpolated into a run: shell command.

      ### GHA021 — actions/checkout not pinned to a SHA (warning)

      Pin \`actions/checkout\` to a full 40-char commit SHA.

      Authority: [OSSF Scorecard — Pinned-Dependencies](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) · [GitHub — Using third-party actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)

      - \`.github/workflows/ci.yml\` (\`build\`) — Job "build" uses actions/checkout@v4 — pin to a full commit SHA.

      ### GHA033 — Blanket write-all permissions (warning)

      Replace \`write-all\` with the specific scopes the jobs need (default \`contents: read\`).

      Authority: [OSSF Scorecard — Token-Permissions](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) · [GitHub — Automatic token authentication](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication)

      - \`.github/workflows/ci.yml\` — Workflow declares permissions: write-all — replace it with specific scopes.

      ## Report-only (hygiene)

      | Rule | Title | File | Detail |
      | --- | --- | --- | --- |
      | GHA022 | Job without timeout-minutes | \`.github/workflows/ci.yml\` | Job "build" has no timeout-minutes. |

      ---
      Generated by [chant audit](https://intentius.io/chant/).
      "
    `);
  });

  test("clean report when there are no findings", () => {
    const out = renderMarkdown([]);
    expect(out).toContain("No issues found.");
    expect(out).toContain("chant audit");
    expect(out).not.toContain("Merge-worthy");
  });

  test("omits a tier section when it has no findings", () => {
    const out = renderMarkdown([FINDINGS[2]]); // one merge-worthy error only
    expect(out).toContain("## Merge-worthy findings");
    expect(out).not.toContain("## Report-only");
  });
});
