/**
 * Markdown report generator for audit findings.
 *
 * Renders a shareable report: a header with counts, a **merge-worthy** section
 * (security/correctness findings worth a PR, with remediation and authority
 * citations) and a compact **report-only** hygiene table. Deterministic
 * ordering keeps snapshots stable. Pure string output — no I/O.
 */

import type { AuditFinding } from "./core";
import { RULE_CATALOG, type RuleMeta, type Tier } from "./catalog";
import type { Severity } from "../lint/rule";

export interface RenderOptions {
  /** Repo URL or path shown in the header. */
  target?: string;
}

const SEVERITY_WEIGHT: Record<Severity, number> = { error: 0, warning: 1, info: 2 };

/** Catalog lookup with a safe fallback for any uncatalogued id. */
function metaFor(id: string): RuleMeta {
  return (
    RULE_CATALOG[id] ?? {
      id,
      tier: "report-only" as Tier,
      fixKind: "guidance",
      title: id,
      remediation: "",
      yamlBased: true,
    }
  );
}

interface EnrichedFinding extends AuditFinding {
  meta: RuleMeta;
}

function enrich(findings: AuditFinding[]): EnrichedFinding[] {
  return findings.map((f) => ({ ...f, meta: metaFor(f.checkId) }));
}

/** Sort findings by severity, then check id, then file — stable for snapshots. */
function sortFindings(a: EnrichedFinding, b: EnrichedFinding): number {
  const sev = SEVERITY_WEIGHT[a.severity] - SEVERITY_WEIGHT[b.severity];
  if (sev !== 0) return sev;
  if (a.checkId !== b.checkId) return a.checkId < b.checkId ? -1 : 1;
  return a.file < b.file ? -1 : a.file > b.file ? 1 : 0;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}

function renderMergeWorthy(findings: EnrichedFinding[]): string[] {
  const lines: string[] = ["## Merge-worthy findings", ""];

  // Group by check id, preserving severity/id order.
  const byRule = new Map<string, EnrichedFinding[]>();
  for (const f of [...findings].sort(sortFindings)) {
    const list = byRule.get(f.checkId) ?? [];
    list.push(f);
    byRule.set(f.checkId, list);
  }

  for (const [checkId, group] of byRule) {
    const m = group[0].meta;
    lines.push(`### ${checkId} — ${m.title} (${group[0].severity})`);
    if (m.remediation) lines.push("", m.remediation);
    if (m.authority?.length) {
      const links = m.authority.map((a) => `[${a.name}](${a.url})`).join(" · ");
      lines.push("", `Authority: ${links}`);
    }
    lines.push("");
    for (const f of [...group].sort((x, y) => (x.file < y.file ? -1 : x.file > y.file ? 1 : 0))) {
      const where = f.entity ? `\`${f.file}\` (\`${f.entity}\`)` : `\`${f.file}\``;
      lines.push(`- ${where} — ${escapeCell(f.message)}`);
    }
    lines.push("");
  }

  return lines;
}

function renderReportOnly(findings: EnrichedFinding[]): string[] {
  const lines: string[] = ["## Report-only (hygiene)", "", "| Rule | Title | File | Detail |", "| --- | --- | --- | --- |"];
  for (const f of [...findings].sort(sortFindings)) {
    lines.push(`| ${f.checkId} | ${escapeCell(f.meta.title)} | \`${f.file}\` | ${escapeCell(f.message)} |`);
  }
  lines.push("");
  return lines;
}

/** Render an audit report as Markdown. */
export function renderMarkdown(findings: AuditFinding[], opts: RenderOptions = {}): string {
  const enriched = enrich(findings);
  const mergeWorthy = enriched.filter((f) => f.meta.tier === "merge-worthy");
  const reportOnly = enriched.filter((f) => f.meta.tier === "report-only");

  const errors = enriched.filter((f) => f.severity === "error").length;
  const warnings = enriched.filter((f) => f.severity === "warning").length;
  const infos = enriched.filter((f) => f.severity === "info").length;

  const lines: string[] = ["# CI security audit"];
  if (opts.target) lines.push("", `Target: ${opts.target}`);
  lines.push("");

  if (enriched.length === 0) {
    lines.push("No issues found.", "");
    lines.push("---", "Generated by [chant audit](https://intentius.io/chant/).", "");
    return lines.join("\n");
  }

  lines.push(
    `${enriched.length} finding${enriched.length === 1 ? "" : "s"} — ` +
      `${mergeWorthy.length} merge-worthy, ${reportOnly.length} report-only ` +
      `(${errors} error, ${warnings} warning, ${infos} info).`,
    "",
  );

  if (mergeWorthy.length > 0) lines.push(...renderMergeWorthy(mergeWorthy));
  if (reportOnly.length > 0) lines.push(...renderReportOnly(reportOnly));

  lines.push("---", "Generated by [chant audit](https://intentius.io/chant/).", "");
  return lines.join("\n");
}
